In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("jobs.csv")

In [3]:
df.head()

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit
0,trưởng phòng kinh doanh,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,lên đến 1 năm,NaN,"kinh doanh, bán hàng, nội ngoại thất, xây dựng",15 tr - 50 tr vnd,15.0,50.0,vnd
1,nhân viên qc ngành cơ khí,nhân viên chính thức,nhân viên,hồ chí minh,trên 1 năm,"production planning staff, chuyên viên iso, th...","vận hành sản xuất, sản xuất, qc), quản lý chất...",8 tr - 11 tr vnd,8.0,11.0,vnd
2,trưởng phòng đấu thầu,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,5 - 7 năm,"trưởng phòng xây dựng, trưởng phòng đấu thầu, ...","điện, xây dựng, điện tử, điện lạnh, dầu khí, đ...",20 tr - 30 tr vnd,20.0,30.0,vnd
3,home textile designer,nhân viên chính thức,nhân viên,hưng yên,5 - 15 năm,NaN,"dệt may, nghệ thuật, da giày, thiết kế, mỹ thu...","800 - 1,500 usd",20.0,37.5,usd
4,nhân viên kinh doanh,nhân viên chính thức,nhân viên,hồ chí minh,trên 1 năm,NaN,"tư vấn, bán sỉ, bán lẻ, kinh doanh, bán hàng",10 tr - 50 tr vnd,10.0,50.0,vnd

In [4]:
df.shape

(85470, 11)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 85470 entries, 0 to 85469
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       85463 non-null  str
 1   job_type        85470 non-null  str
 2   position_level  85470 non-null  str
 3   city            85438 non-null  str
 4   experience      85470 non-null  str
 5   skills          74176 non-null  str
 6   job_fields      77845 non-null  str
 7   salary          85470 non-null  str
 8   salary_min      85470 non-null  float64
 9   salary_max      85470 non-null  float64
 10  unit            85470 non-null  str
dtypes: float64(2), str(9)
memory usage: 7.2 MB

In [6]:
df.describe(include="all")

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit
count,85463,85470,85470,85438,85470,74176,77845,85470,85470.000000,85470.000000,85470
unique,23576,27,26,466,181,20484,7491,2069,NaN,NaN,2
top,nhân viên kinh doanh,full-time,"nhân viên, chuyên viên",hà nội,không yêu cầu,"tư vấn bán hàng, chăm sóc khách hàng","bán hàng, chăm sóc khách hàng, kinh doanh",10 - 15 triệu vnđ,NaN,NaN,vnd
freq,1782,37135,34385,26224,36050,1036,2310,2009,NaN,NaN,84757
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.875715,19.191847,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.763057,16.023232,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,12.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,15.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,21.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900.000000,700.000000,NaN

In [7]:
df.isnull().sum()

job_title             7
job_type              0
position_level        0
city                 32
experience            0
skills            11294
job_fields         7625
salary                0
salary_min            0
salary_max            0
unit                  0
dtype: int64

In [8]:
df["city"].value_counts()

city
hà nội                   26224
hồ chí minh              25958
bình dương                3722
đồng nai                  2324
hải phòng                 1663
                         ...
thanh hoá  2 nơi khác        1
tuân nguyễnnguyn             1
phường 19                    1
japan                        1
vpbank cn ba đình            1
Name: count, Length: 466, dtype: int64

In [9]:
df["experience"].value_counts()

experience
không yêu cầu                                                                                           36050
1 - 2 năm                                                                                                7191
trên 1 năm                                                                                               7038
trên 2 năm                                                                                               4206
1 - 3 năm                                                                                                3163
                                                                                                        ...
6 - 3 năm                                                                                                   1
trên 1 năm\r\n- đã từng làm ở công ty diễn họa có khách hàng là các chủ đầu tư lớn là một điểm cộng.        1
23 - 02 năm                                                                                                 1
30 - 2 năm                                                                                                  1
7 - 1 năm                                                                                                   1
Name: count, Length: 181, dtype: int64

In [10]:
df["job_fields"].value_counts()

job_fields
bán hàng, chăm sóc khách hàng, kinh doanh                                                         2310
kế toán, kiểm toán                                                                                1867
bán hàng, kinh doanh                                                                              1400
ngân hàng, chăm sóc khách hàng, kinh doanh, tài chính, bán hàng                                   1255
, bán hàng - kinh doanh, bán sỉ - bán lẻ - quản lý cửa hàng, chăm sóc khách hàng                   943
                                                                                                  ...
chăm sóc khách hàng, kinh doanh, hành chính, văn phòng, quản lý, nhà hàng, khách sạn, bán hàng       1
chăm sóc khách hàng, dược phẩm, kinh doanh, hành chính, văn phòng, bán hàng, mỹ phẩm                 1
ngân hàng, kinh doanh, đấu thầu, xây dựng, tài chính, bán hàng, dự án, it phần mềm                   1
chế biến, sản xuất, marketing, kinh doanh, hoá sinh, spa, lắp ráp, bán hàng, làm đẹp                 1
chế biến, sản xuất, dệt may, hành chính, thiết kế, văn phòng, da giày, lắp ráp                       1
Name: count, Length: 7491, dtype: int64

In [11]:
df[["salary_min", "salary_max"]].describe()

         salary_min    salary_max
count  85470.000000  85470.000000
mean      11.875715     19.191847
std       14.763057     16.023232
min        0.000000      0.000000
25%        8.000000     12.000000
50%       10.000000     15.000000
75%       15.000000     21.000000
max      900.000000    700.000000

In [12]:
raw_df = df.copy()

In [13]:
clean_df = df.copy()

In [14]:
raw_df = df.copy()

In [15]:
clean_df["city"].value_counts()

city
hà nội                   26224
hồ chí minh              25958
bình dương                3722
đồng nai                  2324
hải phòng                 1663
                         ...
thanh hoá  2 nơi khác        1
tuân nguyễnnguyn             1
phường 19                    1
japan                        1
vpbank cn ba đình            1
Name: count, Length: 466, dtype: int64

In [17]:
def audit(df):

    """One-glance quality report for any DataFrame."""

    return pd.DataFrame({
        "dtype": df.dtypes,
        "n_missing": df.isna().sum(),
        "pct_missing": (df.isna().mean() * 100).round(1),
        "n_unique": df.nunique(),
        "sample": df.iloc[0]
    })

audit(df).sort_values("pct_missing", ascending=False)

,dtype,n_missing,pct_missing,n_unique,sample
skills,str,11294,13.2,20484,NaN
job_fields,str,7625,8.9,7491,"kinh doanh, bán hàng, nội ngoại thất, xây dựng"
job_title,str,7,0.0,23576,trưởng phòng kinh doanh
position_level,str,0,0.0,26,"trưởng nhóm , giám sát"
job_type,str,0,0.0,27,nhân viên chính thức
experience,str,0,0.0,181,lên đến 1 năm
city,str,32,0.0,466,hồ chí minh
salary,str,0,0.0,2069,15 tr - 50 tr vnd
salary_min,float64,0,0.0,190,15.0
salary_max,float64,0,0.0,175,50.0
unit,str,0,0.0,2,vnd

In [18]:

city_counts = df["city"].value_counts()

In [19]:
print(city_counts.to_string())

city
hà nội                                                                                26224
hồ chí minh                                                                           25958
bình dương                                                                             3722
đồng nai                                                                               2324
hải phòng                                                                              1663
long an                                                                                1612
đà nẵng                                                                                1386
hưng yên                                                                               1119
bắc ninh                                                                               1042
tây ninh                                                                                696
cần thơ                                                                                 679
hải dương                                                                               620
vũng tàu                                                                                616
nghệ an                                                                                 571
quảng ninh                                                                              529
bắc giang                                                                               511
điện biên                                                                               508
hà nam                                                                                  487
kiên giang                                                                              462
thái bình                                                                               457
lâm đồng                                                                                439
khánh hòa                                                                               434
an giang                                                                                394
bình phước                                                                              335
bà rịa  vũng tàu                                                                        329
hà hội                                                                                  325
nam định                                                                                322
thanh hóa                                                                               317
thái nguyên                                                                             315
phú thọ                                                                                 312
đắk lắk                                                                                 296
biên hòa                                                                                294
quảng nam                                                                               288
tiền giang                                                                              287
vĩnh phúc                                                                               279
thủ dầu một                                                                             267
bến tre                                                                                 262
toàn quốc                                                                               244
phú yên                                                                                 225
bình định                                                                               221
quảng ngãi                                                                              219
đồng tháp                                                                               218
quận 1                                                                                  218
sóc trăng                                                                               214
cà mau                                                                                  210
ninh bình                                                                               207
bình thuận                                                                              196
kon tum                                                                                 179
bạc liêu                                                                                178
thừa thiên huế                                                                          176
gia lai                                                                                 170
hậu giang                                                                               159
hà tĩnh                                                                                 153
hòa bình                                                                                141
sơn la                                                                                  140
vĩnh long                                                                               132
quảng bình                                                                              129
yên bái                                                                                 125
nha trang                                                                               123
ho chi minh city                                                                        119
lạng sơn                                                                                116
cầu giấy                                                                                 98
ninh thuận                                                                               96
hạ long                                                                                  91
lào cai                                                                                  90
thủ đức                                                                                  88
quận tân bình                                                                            85
quận 12                                                                                  85
việt nam                                                                                 75
tp thủ đức                                                                               74
hải an                                                                                   73
thanh xuân                                                                               72
hà giang                                                                                 71
tp huế                                                                                   70
phan thiết                                                                               68
tuyên quang                                                                              67
đắk nông                                                                                 61
quận 9                                                                                   61
long biên                                                                                61
vietnam                                                                                  60
quận 7                                                                                   60
bắc từ liêm                                                                              56
số 74 phạm văn đồng                                                                      55
hoàng mai                                                                                47
nam từ liêm                                                                              47
cao bằng                                                                                 46
quận 3                                                                                   45
quận bình tân                                                                            45
trà vinh                                                                                 42
quận phú nhuận                                                                           40
quảng trị                                                                                39
hanoi                                                                                    39
huế                                                                                      37
bình tân                                                                                 37
dak lak                                                                                  36
nước ngoài                                                                               36
toà nhà golden king nguyễn lương bằng quận 7                                             35
đống đa                                                                                  35
ba đình                                                                                  34
hà đông                                                                                  34
bắc kạn                                                                                  33
lai châu                                                                                 33
quận 10                                                                                  30
quận gò vấp                                                                              28
quận hải châu                                                                            28
toàn tỉnh                                                                                28
mỹ tho                                                                                   27
phú nhuận                                                                                27
tòa nhà mb 21 cát linh                                                                   26
quận 2                                                                                   25
bình thạnh                                                                               24
hiệp bình phước                                                                          23
nhật bản                                                                                 22
miền nam                                                                                 22
ho chi minh                                                                              22
hai bà trưng                                                                             22
toà nhà tng 54a nguyễn chí thanh                                                         21
thanh hoá                                                                                20
số 107 phố xuân quỳnh trung hòa                                                      19
bd                                                                                       19
quốc tế                                                                                  18
bến cát                                                                                  18
dĩ an                                                                                    18
q bình thạnh                                                                             18
quận hà đông                                                                             18
duy tiên                                                                                 17
miền bắc                                                                                 17
quận 5                                                                                   17
tân bình                                                                                 17
hóc môn                                                                                  16
cần giuộc                                                                                16
huyện bình chánh                                                                         15
qtân bình                                                                                14
quận 11                                                                                  14
phường cổ nhuế 2                                                                         14
nhơn trạch                                                                               14
dak nông                                                                                 13
thanh trì                                                                                13
kcx linh trung 2                                                                         13
nguyễn xiển                                                                              13
quận đống đa                                                                             13
2604 quốc lộ 1a xã bình chánh                                                            13
quận bình thạnh                                                                          13
huyện củ chi                                                                             12
tan binh dist                                                                            12
hoàn kiếm                                                                                11
qbình tân                                                                                11
q10                                                                                      11
dist 1                                                                                   11
q2                                                                                       11
quận hoàng mai                                                                           11
phú quốc                                                                                 11
quận 8                                                                                   11
thành phố thủ đức                                                                        11
dist 3                                                                                   10
số 5 ngõ 70 nguyễn hoàng                                                                 10
đức hòa                                                                                  10
quận bắc từ liêm                                                                         10
california fitness  yoga                                                                 10
các văn phòng đại diện tại các quận                                                      10
thủ đức                                                                                10
huyện phú xuyên                                                                          10
số 04 lê liễu                                                                            10
q12                                                                                      10
hải châu                                                                                 10
online                                                                                    9
lotte mall tây hồ                                                                         9
thuận thành                                                                               9
bắc ninh                                                                                 9
hội an                                                                                    9
huyện yên mỹ                                                                              9
q cầu giấy                                                                                9
toàn khu vực                                                                              9
phường bình thuận                                                                         9
tân phú                                                                                   9
quận tây hồ                                                                               9
hà huy giáp                                                                               8
pphú lợi                                                                                  8
kcn amata                                                                                 8
quận thanh xuân                                                                           8
cai lậy                                                                                   8
quận tân phú                                                                              8
toà nhà tng 54a nguyễn chí than                                                           8
252 hạ hội tân lậpmiền bắc                                                                8
q3                                                                                        8
cổ nhuế gần mega market phạm văn đồng                                                     7
văn lâm                                                                                   7
tân uyên                                                                                  7
tây nguyên                                                                                7
long thành                                                                                7
trảng bàng                                                                                7
fpt shop thành phố vĩnh long                                                              7
tỉnh đaklak                                                                               7
cờ đỏ                                                                                     7
hòa thành                                                                                 7
gò vấp                                                                                    7
tại nhà                                                                                   7
tp bến cát                                                                                7
thành phố quy nhơn                                                                        7
khu đô thị an phú an khánh                                                                7
quận 4                                                                                    7
thuận an                                                                                  7
69b thụy khuê                                                                             7
tp thủ đức bên cạnh trường mầm non kcnc quận 9                                            7
bắc cạn                                                                                   6
phú vang                                                                                  6
tất cả các quậnhuyện                                                                      6
đường số 4                                                                                6
tỉnh lào cai                                                                              6
phú lương                                                                                 6
quận hai bà trưng                                                                         6
p hiệp bình phước                                                                         6
thành phố phú quốc                                                                        6
hoài đức                                                                                  6
lotte tây hồvincom bà triệutttm the gardensavico long biên                                6
hậu lộc                                                                                   6
tòa chung cư ban cơ yếu chính phủ                                                         6

In [20]:
city_mapping = {

    # =========================
    # HANOI
    # =========================

    "hà nội": "Hanoi",
    "hanoi": "Hanoi",
    "ha noi": "Hanoi",
    "hà nộ": "Hanoi",
    "hà hội": "Hanoi",

    # Hanoi districts / areas
    "cầu giấy": "Hanoi",
    "q cầu giấy": "Hanoi",
    "quận cầu giấy": "Hanoi",
    "thanh xuân": "Hanoi",
    "quận thanh xuân": "Hanoi",
    "hoàng mai": "Hanoi",
    "quận hoàng mai": "Hanoi",
    "hai bà trưng": "Hanoi",
    "quận hai bà trưng": "Hanoi",
    "ba đình": "Hanoi",
    "quận ba đình": "Hanoi",
    "quận ba đình": "Hanoi",
    "đống đa": "Hanoi",
    "quận đống đa": "Hanoi",
    "hoàng kiếm": "Hanoi",
    "hoàn kiếm": "Hanoi",
    "quận hoàn kiếm": "Hanoi",
    "hà đông": "Hanoi",
    "quận hà đông": "Hanoi",
    "hà đông": "Hanoi",
    "nam từ liêm": "Hanoi",
    "bắc từ liêm": "Hanoi",
    "quận bắc từ liêm": "Hanoi",
    "từ liêm": "Hanoi",
    "long biên": "Hanoi",
    "huyện gia lâm": "Hanoi",
    "thanh trì": "Hanoi",
    "huyện mê linh": "Hanoi",
    "huyện phú xuyên": "Hanoi",
    "phú xuyên": "Hanoi",
    "huyện yên mỹ": "Hung Yen",  # see note below
    "trung hòa": "Hanoi",
    "trung văn": "Hanoi",
    "đại kim": "Hanoi",
    "phương liệt": "Hanoi",
    "kim mã": "Hanoi",
    "kim mã": "Hanoi",
    "cổ nhuế": "Hanoi",
    "cổ nhuế 1": "Hanoi",
    "cổ nhuế 2": "Hanoi",
    "phường cổ nhuế 1": "Hanoi",
    "phường cổ nhuế 2": "Hanoi",
    "phường dịch vọng hậu": "Hanoi",
    "phường võ thị sáu": "Hanoi",
    "phường 13 quận 10": "Ho Chi Minh City",  # exception
    "lotte mall tây hồ": "Hanoi",
    "quận tây hồ": "Hanoi",
    "tây hồ": "Hanoi",
    "quận hai bà trưng": "Hanoi",
    "hoàng mai": "Hanoi",
}

In [21]:
city_mapping = {
    "hà nội": "Hanoi",
    "hanoi": "Hanoi",
    "ha noi": "Hanoi",

    "hồ chí minh": "Ho Chi Minh City",
    "ho chi minh": "Ho Chi Minh City",
    "ho chi minh city": "Ho Chi Minh City",
    "hcm": "Ho Chi Minh City",

    "đà nẵng": "Da Nang",
    "da nang": "Da Nang",

    "hải phòng": "Hai Phong",
    "tp hai phong": "Hai Phong",

    "cần thơ": "Can Tho",

    "bình dương": "Binh Duong",
    "bd": "Binh Duong",

    "đồng nai": "Dong Nai",
    "dong nai province": "Dong Nai",
    "biên hòa": "Dong Nai",
}

In [22]:
clean_df["city"] = clean_df["city"].replace(city_mapping)

In [23]:
print(clean_df["city"].value_counts().to_string())

city
Hanoi                                                                                 26267
Ho Chi Minh City                                                                      26099
Binh Duong                                                                             3741
Dong Nai                                                                               2623
Hai Phong                                                                              1668
long an                                                                                1612
Da Nang                                                                                1391
hưng yên                                                                               1119
bắc ninh                                                                               1042
tây ninh                                                                                696
Can Tho                                                                                 679
hải dương                                                                               620
vũng tàu                                                                                616
nghệ an                                                                                 571
quảng ninh                                                                              529
bắc giang                                                                               511
điện biên                                                                               508
hà nam                                                                                  487
kiên giang                                                                              462
thái bình                                                                               457
lâm đồng                                                                                439
khánh hòa                                                                               434
an giang                                                                                394
bình phước                                                                              335
bà rịa  vũng tàu                                                                        329
hà hội                                                                                  325
nam định                                                                                322
thanh hóa                                                                               317
thái nguyên                                                                             315
phú thọ                                                                                 312
đắk lắk                                                                                 296
quảng nam                                                                               288
tiền giang                                                                              287
vĩnh phúc                                                                               279
thủ dầu một                                                                             267
bến tre                                                                                 262
toàn quốc                                                                               244
phú yên                                                                                 225
bình định                                                                               221
quảng ngãi                                                                              219
đồng tháp                                                                               218
quận 1                                                                                  218
sóc trăng                                                                               214
cà mau                                                                                  210
ninh bình                                                                               207
bình thuận                                                                              196
kon tum                                                                                 179
bạc liêu                                                                                178
thừa thiên huế                                                                          176
gia lai                                                                                 170
hậu giang                                                                               159
hà tĩnh                                                                                 153
hòa bình                                                                                141
sơn la                                                                                  140
vĩnh long                                                                               132
quảng bình                                                                              129
yên bái                                                                                 125
nha trang                                                                               123
lạng sơn                                                                                116
cầu giấy                                                                                 98
ninh thuận                                                                               96
hạ long                                                                                  91
lào cai                                                                                  90
thủ đức                                                                                  88
quận tân bình                                                                            85
quận 12                                                                                  85
việt nam                                                                                 75
tp thủ đức                                                                               74
hải an                                                                                   73
thanh xuân                                                                               72
hà giang                                                                                 71
tp huế                                                                                   70
phan thiết                                                                               68
tuyên quang                                                                              67
đắk nông                                                                                 61
quận 9                                                                                   61
long biên                                                                                61
vietnam                                                                                  60
quận 7                                                                                   60
bắc từ liêm                                                                              56
số 74 phạm văn đồng                                                                      55
hoàng mai                                                                                47
nam từ liêm                                                                              47
cao bằng                                                                                 46
quận 3                                                                                   45
quận bình tân                                                                            45
trà vinh                                                                                 42
quận phú nhuận                                                                           40
quảng trị                                                                                39
huế                                                                                      37
bình tân                                                                                 37
dak lak                                                                                  36
nước ngoài                                                                               36
toà nhà golden king nguyễn lương bằng quận 7                                             35
đống đa                                                                                  35
ba đình                                                                                  34
hà đông                                                                                  34
bắc kạn                                                                                  33
lai châu                                                                                 33
quận 10                                                                                  30
quận gò vấp                                                                              28
quận hải châu                                                                            28
toàn tỉnh                                                                                28
mỹ tho                                                                                   27
phú nhuận                                                                                27
tòa nhà mb 21 cát linh                                                                   26
quận 2                                                                                   25
bình thạnh                                                                               24
hiệp bình phước                                                                          23
nhật bản                                                                                 22
miền nam                                                                                 22
hai bà trưng                                                                             22
toà nhà tng 54a nguyễn chí thanh                                                         21
thanh hoá                                                                                20
số 107 phố xuân quỳnh trung hòa                                                      19
quốc tế                                                                                  18
bến cát                                                                                  18
dĩ an                                                                                    18
q bình thạnh                                                                             18
quận hà đông                                                                             18
duy tiên                                                                                 17
miền bắc                                                                                 17
quận 5                                                                                   17
tân bình                                                                                 17
hóc môn                                                                                  16
cần giuộc                                                                                16
huyện bình chánh                                                                         15
qtân bình                                                                                14
quận 11                                                                                  14
phường cổ nhuế 2                                                                         14
nhơn trạch                                                                               14
dak nông                                                                                 13
thanh trì                                                                                13
kcx linh trung 2                                                                         13
nguyễn xiển                                                                              13
quận đống đa                                                                             13
2604 quốc lộ 1a xã bình chánh                                                            13
quận bình thạnh                                                                          13
huyện củ chi                                                                             12
tan binh dist                                                                            12
hoàn kiếm                                                                                11
qbình tân                                                                                11
q10                                                                                      11
dist 1                                                                                   11
q2                                                                                       11
quận hoàng mai                                                                           11
phú quốc                                                                                 11
quận 8                                                                                   11
thành phố thủ đức                                                                        11
dist 3                                                                                   10
số 5 ngõ 70 nguyễn hoàng                                                                 10
đức hòa                                                                                  10
quận bắc từ liêm                                                                         10
california fitness  yoga                                                                 10
các văn phòng đại diện tại các quận                                                      10
thủ đức                                                                                10
huyện phú xuyên                                                                          10
số 04 lê liễu                                                                            10
q12                                                                                      10
hải châu                                                                                 10
online                                                                                    9
lotte mall tây hồ                                                                         9
thuận thành                                                                               9
bắc ninh                                                                                 9
hội an                                                                                    9
huyện yên mỹ                                                                              9
q cầu giấy                                                                                9
toàn khu vực                                                                              9
phường bình thuận                                                                         9
tân phú                                                                                   9
quận tây hồ                                                                               9
hà huy giáp                                                                               8
pphú lợi                                                                                  8
kcn amata                                                                                 8
quận thanh xuân                                                                           8
cai lậy                                                                                   8
quận tân phú                                                                              8
toà nhà tng 54a nguyễn chí than                                                           8
252 hạ hội tân lậpmiền bắc                                                                8
q3                                                                                        8
cổ nhuế gần mega market phạm văn đồng                                                     7
văn lâm                                                                                   7
tân uyên                                                                                  7
tây nguyên                                                                                7
long thành                                                                                7
trảng bàng                                                                                7
fpt shop thành phố vĩnh long                                                              7
tỉnh đaklak                                                                               7
cờ đỏ                                                                                     7
hòa thành                                                                                 7
gò vấp                                                                                    7
tại nhà                                                                                   7
tp bến cát                                                                                7
thành phố quy nhơn                                                                        7
khu đô thị an phú an khánh                                                                7
quận 4                                                                                    7
thuận an                                                                                  7
69b thụy khuê                                                                             7
tp thủ đức bên cạnh trường mầm non kcnc quận 9                                            7
bắc cạn                                                                                   6
phú vang                                                                                  6
tất cả các quậnhuyện                                                                      6
đường số 4                                                                                6
tỉnh lào cai                                                                              6
phú lương                                                                                 6
quận hai bà trưng                                                                         6
p hiệp bình phước                                                                         6
thành phố phú quốc                                                                        6
hoài đức                                                                                  6
lotte tây hồvincom bà triệutttm the gardensavico long biên                                6
hậu lộc                                                                                   6
tòa chung cư ban cơ yếu chính phủ                                                         6
tpthủ đức                                                                                 6
kim động                                                                                  6
tp buôn ma thuột                                                                          6
kv đông nam bộ                                                                            5
q4                                                                                        5

In [24]:
city_mapping = {

    # =========================
    # HANOI
    # =========================

    "hà nội": "Hanoi",
    "hanoi": "Hanoi",
    "ha noi": "Hanoi",
    "hà nộ": "Hanoi",
    "hà hội": "Hanoi",

    # Hanoi districts / areas
    "cầu giấy": "Hanoi",
    "q cầu giấy": "Hanoi",
    "quận cầu giấy": "Hanoi",
    "thanh xuân": "Hanoi",
    "quận thanh xuân": "Hanoi",
    "hoàng mai": "Hanoi",
    "quận hoàng mai": "Hanoi",
    "hai bà trưng": "Hanoi",
    "quận hai bà trưng": "Hanoi",
    "ba đình": "Hanoi",
    "quận ba đình": "Hanoi",
    "quận ba đình": "Hanoi",
    "đống đa": "Hanoi",
    "quận đống đa": "Hanoi",
    "hoàng kiếm": "Hanoi",
    "hoàn kiếm": "Hanoi",
    "quận hoàn kiếm": "Hanoi",
    "hà đông": "Hanoi",
    "quận hà đông": "Hanoi",
    "hà đông": "Hanoi",
    "nam từ liêm": "Hanoi",
    "bắc từ liêm": "Hanoi",
    "quận bắc từ liêm": "Hanoi",
    "từ liêm": "Hanoi",
    "long biên": "Hanoi",
    "huyện gia lâm": "Hanoi",
    "thanh trì": "Hanoi",
    "huyện mê linh": "Hanoi",
    "huyện phú xuyên": "Hanoi",
    "phú xuyên": "Hanoi",
    "huyện yên mỹ": "Hung Yen",  # see note below
    "trung hòa": "Hanoi",
    "trung văn": "Hanoi",
    "đại kim": "Hanoi",
    "phương liệt": "Hanoi",
    "kim mã": "Hanoi",
    "kim mã": "Hanoi",
    "cổ nhuế": "Hanoi",
    "cổ nhuế 1": "Hanoi",
    "cổ nhuế 2": "Hanoi",
    "phường cổ nhuế 1": "Hanoi",
    "phường cổ nhuế 2": "Hanoi",
    "phường dịch vọng hậu": "Hanoi",
    "phường võ thị sáu": "Hanoi",
    "phường 13 quận 10": "Ho Chi Minh City",  # exception
    "lotte mall tây hồ": "Hanoi",
    "quận tây hồ": "Hanoi",
    "tây hồ": "Hanoi",
    "quận hai bà trưng": "Hanoi",
    "hoàng mai": "Hanoi",
}

In [25]:
clean_df["city"] = clean_df["city"].replace(city_mapping)

In [26]:
city_mapping.update({

    # Main names
    "hồ chí minh": "Ho Chi Minh City",
    "ho chi minh": "Ho Chi Minh City",
    "ho chi minh city": "Ho Chi Minh City",
    "hcm": "Ho Chi Minh City",
    "tp hồ chí minh": "Ho Chi Minh City",
    "tp.hcm": "Ho Chi Minh City",

    # District 1
    "quận 1": "Ho Chi Minh City",
    "q1": "Ho Chi Minh City",
    "dist 1": "Ho Chi Minh City",
    "quận 1": "Ho Chi Minh City",

    # District 2
    "quận 2": "Ho Chi Minh City",
    "q2": "Ho Chi Minh City",

    # District 3
    "quận 3": "Ho Chi Minh City",
    "q3": "Ho Chi Minh City",
    "dist 3": "Ho Chi Minh City",

    # District 4
    "quận 4": "Ho Chi Minh City",
    "q4": "Ho Chi Minh City",

    # District 5
    "quận 5": "Ho Chi Minh City",

    # District 6
    "quận 6": "Ho Chi Minh City",

    # District 7
    "quận 7": "Ho Chi Minh City",
    "q7": "Ho Chi Minh City",

    # District 8
    "quận 8": "Ho Chi Minh City",

    # District 9
    "quận 9": "Ho Chi Minh City",
    "q9": "Ho Chi Minh City",
    "district 9": "Ho Chi Minh City",

    # District 10
    "quận 10": "Ho Chi Minh City",
    "q10": "Ho Chi Minh City",

    # District 11
    "quận 11": "Ho Chi Minh City",

    # District 12
    "quận 12": "Ho Chi Minh City",
    "q12": "Ho Chi Minh City",

    # Bình Thạnh
    "bình thạnh": "Ho Chi Minh City",
    "quận bình thạnh": "Ho Chi Minh City",
    "q bình thạnh": "Ho Chi Minh City",
    "qbình thạnh": "Ho Chi Minh City",

    # Tân Bình
    "tân bình": "Ho Chi Minh City",
    "quận tân bình": "Ho Chi Minh City",
    "qtân bình": "Ho Chi Minh City",
    "tan binh dist": "Ho Chi Minh City",
    "q tân bình": "Ho Chi Minh City",

    # Phú Nhuận
    "phú nhuận": "Ho Chi Minh City",
    "quận phú nhuận": "Ho Chi Minh City",
    "q phú nhuận": "Ho Chi Minh City",
    "qphú nhuận": "Ho Chi Minh City",

    # Gò Vấp
    "gò vấp": "Ho Chi Minh City",
    "quận gò vấp": "Ho Chi Minh City",

    # Bình Tân
    "bình tân": "Ho Chi Minh City",
    "quận bình tân": "Ho Chi Minh City",
    "qbình tân": "Ho Chi Minh City",

    # Tân Phú
    "tân phú": "Ho Chi Minh City",
    "quận tân phú": "Ho Chi Minh City",
    "qtân phú": "Ho Chi Minh City",

    # Hóc Môn / Củ Chi / Bình Chánh
    "hóc môn": "Ho Chi Minh City",
    "huyện củ chi": "Ho Chi Minh City",
    "củ chi": "Ho Chi Minh City",
    "huyện bình chánh": "Ho Chi Minh City",

    # Thủ Đức
    "thủ đức": "Ho Chi Minh City",
    "tp thủ đức": "Ho Chi Minh City",
    "tpthủ đức": "Ho Chi Minh City",
    "thành phố thủ đức": "Ho Chi Minh City",
    "thủ đức": "Ho Chi Minh City",
    "thu duc city": "Ho Chi Minh City",
    "quận thủ đức": "Ho Chi Minh City",

    # Specific HCMC locations
    "hiệp bình phước": "Ho Chi Minh City",
    "p hiệp bình phước": "Ho Chi Minh City",
    "phường hiệp bình phước": "Ho Chi Minh City",
    "bình thọ": "Ho Chi Minh City",
    "kcx linh trung 1": "Ho Chi Minh City",
    "kcx linh trung 2": "Ho Chi Minh City",
    "nguyễn xiển": "Ho Chi Minh City",
    "tân đông hiệp": "Ho Chi Minh City",
})

In [27]:
clean_df["city"] = clean_df["city"].replace(city_mapping)

In [28]:
city_mapping.update({

    # Da Nang
    "đà nẵng": "Da Nang",
    "da nang": "Da Nang",
    "quận hải châu": "Da Nang",
    "hải châu": "Da Nang",
    "q hải châu": "Da Nang",
    "liên chiểu": "Da Nang",
    "hòa vang": "Da Nang",

    # Hai Phong
    "hải phòng": "Hai Phong",
    "tp hai phong": "Hai Phong",
    "hải an": "Hai Phong",
    "quận hải an": "Hai Phong",
    "kiến an": "Hai Phong",

    # Can Tho
    "cần thơ": "Can Tho",
    "ninh kiều": "Can Tho",
    "quận ninh kiều": "Can Tho",

    # Hue
    "thừa thiên huế": "Hue",
    "tp huế": "Hue",
    "huế": "Hue",
    "tỉnh tt huế": "Hue",

    # Ba Ria - Vung Tau
    "vũng tàu": "Ba Ria - Vung Tau",
    "bà rịa  vũng tàu": "Ba Ria - Vung Tau",

    # Dong Nai
    "đồng nai": "Dong Nai",
    "dong nai province": "Dong Nai",
    "biên hòa": "Dong Nai",
    "long khánh": "Dong Nai",
    "tp long khánh": "Dong Nai",
    "thành phố long khánh": "Dong Nai",
    "nhơn trạch": "Dong Nai",
    "kcn nhơn trạch 3": "Dong Nai",
    "long thành": "Dong Nai",
    "huyện thống nhất": "Dong Nai",

    # Binh Duong
    "bình dương": "Binh Duong",
    "bd": "Binh Duong",
    "thủ dầu một": "Binh Duong",
    "bến cát": "Binh Duong",
    "tp bến cát": "Binh Duong",
    "dĩ an": "Binh Duong",
    "tp dĩ an": "Binh Duong",
    "thành phố dĩ an": "Binh Duong",
    "tân uyên": "Binh Duong",
    "thuận an": "Binh Duong",

    # Long An
    "long an": "Long An",
    "cần giuộc": "Long An",
    "đức hòa": "Long An",
    "đức hoà": "Long An",
    "huyện đức hòa": "Long An",
    "bến lức": "Long An",
    "đức huệ": "Long An",
    "cần đước": "Long An",

    # Hung Yen
    "hưng yên": "Hung Yen",
    "hung yen province": "Hung Yen",
    "huyện yên mỹ": "Hung Yen",
    "văn lâm": "Hung Yen",
    "huyện văn lâm": "Hung Yen",
    "kim động": "Hung Yen",

    # Bac Ninh
    "bắc ninh": "Bac Ninh",
    "bắc ninh": "Bac Ninh",
    "bn": "Bac Ninh",
    "từ sơn": "Bac Ninh",

    # Tay Ninh
    "tây ninh": "Tay Ninh",
    "trảng bàng": "Tay Ninh",
    "tràng bảng": "Tay Ninh",
    "gò dầu": "Tay Ninh",
    "hòa thành": "Tay Ninh",

    # Nghe An
    "nghệ an": "Nghe An",
    "tp vinh": "Nghe An",

    # Quang Ninh
    "quảng ninh": "Quang Ninh",
    "hạ long": "Quang Ninh",
    "cẩm phả": "Quang Ninh",

    # Bac Giang
    "bắc giang": "Bac Giang",

    # Dien Bien
    "điện biên": "Dien Bien",

    # Ha Nam
    "hà nam": "Ha Nam",
    "duy tiên": "Ha Nam",
    "tp phủ lý": "Ha Nam",

    # Kien Giang
    "kiên giang": "Kien Giang",
    "phú quốc": "Kien Giang",
    "thành phố phú quốc": "Kien Giang",
    "rạch giá": "Kien Giang",

    # Thai Binh
    "thái bình": "Thai Binh",

    # Lam Dong
    "lâm đồng": "Lam Dong",
    "đà lạt": "Lam Dong",

    # Khanh Hoa
    "khánh hòa": "Khanh Hoa",
    "khánh hoà": "Khanh Hoa",
    "nha trang": "Khanh Hoa",

    # An Giang
    "an giang": "An Giang",

    # Binh Phuoc
    "bình phước": "Binh Phuoc",
    "đồng xoài": "Binh Phuoc",
    "chơn thành": "Binh Phuoc",
    "lộc ninh": "Binh Phuoc",

    # Nam Dinh
    "nam định": "Nam Dinh",

    # Thanh Hoa
    "thanh hóa": "Thanh Hoa",
    "thanh hoá": "Thanh Hoa",
    "tp thanh hoá": "Thanh Hoa",

    # Thai Nguyen
    "thái nguyên": "Thai Nguyen",
    "tp sông công": "Thai Nguyen",

    # Phu Tho
    "phú thọ": "Phu Tho",
    "việt trì": "Phu Tho",
    "tp việt trì": "Phu Tho",

    # Dak Lak
    "đắk lắk": "Dak Lak",
    "dak lak": "Dak Lak",
    "đak lak": "Dak Lak",
    "tỉnh đaklak": "Dak Lak",
    "buôn ma thuột": "Dak Lak",
    "tp buôn ma thuột": "Dak Lak",
    "tp bmt": "Dak Lak",

    # Quang Nam
    "quảng nam": "Quang Nam",
    "hội an": "Quang Nam",

    # Tien Giang
    "tiền giang": "Tien Giang",
    "cai lậy": "Tien Giang",
    "tp gò công": "Tien Giang",

    # Vinh Phuc
    "vĩnh phúc": "Vinh Phuc",
    "phúc yên": "Vinh Phuc",

    # Ben Tre
    "bến tre": "Ben Tre",

    # Phu Yen
    "phú yên": "Phu Yen",

    # Binh Dinh
    "bình định": "Binh Dinh",
    "quy nhơn": "Binh Dinh",
    "tp quy nhơn": "Binh Dinh",
    "tpquy nhơn": "Binh Dinh",
    "thành phố quy nhơn": "Binh Dinh",

    # Quang Ngai
    "quảng ngãi": "Quang Ngai",

    # Dong Thap
    "đồng tháp": "Dong Thap",

    # Soc Trang
    "sóc trăng": "Soc Trang",

    # Ca Mau
    "cà mau": "Ca Mau",

    # Ninh Binh
    "ninh bình": "Ninh Binh",

    # Binh Thuan
    "bình thuận": "Binh Thuan",
    "phan thiết": "Binh Thuan",

    # Kon Tum
    "kon tum": "Kon Tum",

    # Bac Lieu
    "bạc liêu": "Bac Lieu",

    # Gia Lai
    "gia lai": "Gia Lai",

    # Hau Giang
    "hậu giang": "Hau Giang",
    "vị thanh": "Hau Giang",

    # Ha Tinh
    "hà tĩnh": "Ha Tinh",

    # Hoa Binh
    "hòa bình": "Hoa Binh",
    "hoà bình": "Hoa Binh",
    "tỉnh hòa bình": "Hoa Binh",
    "thành phố hoà bình": "Hoa Binh",

    # Son La
    "sơn la": "Son La",

    # Vinh Long
    "vĩnh long": "Vinh Long",

    # Quang Binh
    "quảng bình": "Quang Binh",
    "lệ thủy": "Quang Binh",

    # Yen Bai
    "yên bái": "Yen Bai",

    # Lang Son
    "lạng sơn": "Lang Son",

    # Lao Cai
    "lào cai": "Lao Cai",
    "tỉnh lào cai": "Lao Cai",
    "tp lào cai": "Lao Cai",

    # Ninh Thuan
    "ninh thuận": "Ninh Thuan",

    # Ha Giang
    "hà giang": "Ha Giang",

    # Dak Nong
    "đắk nông": "Dak Nong",
    "dak nông": "Dak Nong",

    # Tuyen Quang
    "tuyên quang": "Tuyen Quang",

    # Cao Bang
    "cao bằng": "Cao Bang",

    # Bac Kan
    "bắc kạn": "Bac Kan",
    "bắc cạn": "Bac Kan",

    # Lai Chau
    "lai châu": "Lai Chau",

    # Tra Vinh
    "trà vinh": "Tra Vinh",

    # Quang Tri
    "quảng trị": "Quang Tri",

    # Ha Tinh etc.
    "hậu lộc": "Thanh Hoa",
})

In [29]:
clean_df["city"] = clean_df["city"].replace(city_mapping)

In [30]:
special_mapping = {

    "toàn quốc": "Nationwide",
    "việt nam": "Vietnam",
    "vietnam": "Vietnam",
    "viet nam": "Vietnam",

    "miền bắc": "Northern Vietnam",
    "khu vực miền bắc": "Northern Vietnam",
    "các công trình xây dựng miền bắc": "Northern Vietnam",

    "miền nam": "Southern Vietnam",
    "kv nam trung bộ": "South Central Vietnam",

    "miền trung": "Central Vietnam",
    "tây nguyên": "Central Highlands",
    "kv tây nguyên": "Central Highlands",

    "nước ngoài": "Overseas",
    "quốc tế": "International",

    "online": "Remote",
    "online tại nhà": "Remote",
    "tại nhà": "Remote",

    "toàn tỉnh": "Province-wide",
    "toàn khu vực": "Region-wide",
    "tất cả các quận huyện": "Multiple districts",
    "tất cả các quậnhuyện": "Multiple districts",
    "tất cả các huyện": "Multiple districts",
}

In [31]:
clean_df["city"] = clean_df["city"].replace(special_mapping)

In [32]:
print(clean_df["city"].value_counts().to_string())

city
Ho Chi Minh City                                                                      27472
Hanoi                                                                                 27315
Binh Duong                                                                             4074
Dong Nai                                                                               2664
Hai Phong                                                                              1749
Long An                                                                                1646
Da Nang                                                                                1441
Hung Yen                                                                               1149
Bac Ninh                                                                               1060
Ba Ria - Vung Tau                                                                       945
Tay Ninh                                                                                718
Can Tho                                                                                 681
Quang Ninh                                                                              623
hải dương                                                                               620
Nghe An                                                                                 573
Khanh Hoa                                                                               558
Bac Giang                                                                               511
Ha Nam                                                                                  509
Dien Bien                                                                               508
Kien Giang                                                                              479
Thai Binh                                                                               457
Lam Dong                                                                                442
An Giang                                                                                394
Dak Lak                                                                                 358
Thanh Hoa                                                                               343
Binh Phuoc                                                                              341
Nam Dinh                                                                                322
Thai Nguyen                                                                             319
Phu Tho                                                                                 316
Tien Giang                                                                              299
Quang Nam                                                                               297
Hue                                                                                     287
Vinh Phuc                                                                               282
Binh Thuan                                                                              264
Ben Tre                                                                                 262
Nationwide                                                                              244
Binh Dinh                                                                               234
Phu Yen                                                                                 225
Quang Ngai                                                                              219
Dong Thap                                                                               218
Soc Trang                                                                               214
Ca Mau                                                                                  210
Ninh Binh                                                                               207
Kon Tum                                                                                 179
Bac Lieu                                                                                178
Gia Lai                                                                                 170
Hau Giang                                                                               161
Ha Tinh                                                                                 153
Hoa Binh                                                                                150
Son La                                                                                  140
Vietnam                                                                                 140
Vinh Long                                                                               132
Quang Binh                                                                              131
Yen Bai                                                                                 125
Lang Son                                                                                116
Lao Cai                                                                                  99
Ninh Thuan                                                                               96
Dak Nong                                                                                 74
Ha Giang                                                                                 71
Tuyen Quang                                                                              67
số 74 phạm văn đồng                                                                      55
Cao Bang                                                                                 46
Tra Vinh                                                                                 42
Quang Tri                                                                                39
Bac Kan                                                                                  39
Overseas                                                                                 36
toà nhà golden king nguyễn lương bằng quận 7                                             35
Lai Chau                                                                                 33
Province-wide                                                                            28
mỹ tho                                                                                   27
tòa nhà mb 21 cát linh                                                                   26
Northern Vietnam                                                                         26
nhật bản                                                                                 22
Southern Vietnam                                                                         22
toà nhà tng 54a nguyễn chí thanh                                                         21
số 107 phố xuân quỳnh trung hòa                                                      19
International                                                                            18
Remote                                                                                   18
Multiple districts                                                                       16
2604 quốc lộ 1a xã bình chánh                                                            13
số 5 ngõ 70 nguyễn hoàng                                                                 10
california fitness  yoga                                                                 10
các văn phòng đại diện tại các quận                                                      10
số 04 lê liễu                                                                            10
thuận thành                                                                               9
Region-wide                                                                               9
phường bình thuận                                                                         9
Central Highlands                                                                         8
hà huy giáp                                                                               8
pphú lợi                                                                                  8
kcn amata                                                                                 8
toà nhà tng 54a nguyễn chí than                                                           8
252 hạ hội tân lậpmiền bắc                                                                8
cổ nhuế gần mega market phạm văn đồng                                                     7
fpt shop thành phố vĩnh long                                                              7
cờ đỏ                                                                                     7
khu đô thị an phú an khánh                                                                7
69b thụy khuê                                                                             7
tp thủ đức bên cạnh trường mầm non kcnc quận 9                                            7
phú vang                                                                                  6
đường số 4                                                                                6
phú lương                                                                                 6
hoài đức                                                                                  6
lotte tây hồvincom bà triệutttm the gardensavico long biên                                6
tòa chung cư ban cơ yếu chính phủ                                                         6
kv đông nam bộ                                                                            5
kcn quang minh mê linh                                                                    5
vpbank ứng hòa                                                                            5
phường tân chánh hiệp                                                                     5
hải hà                                                                                    5
41 thép mới                                                                               5
dự án quận tây hồ                                                                         5
91 nguyễn chí thanh                                                                       5
bình xuyên                                                                                5
kcn long đức                                                                              5
bình tân khu tên lửa                                                                      5
161 võ nguyễn giáp                                                                        5
169 nguyễn ngọc vũ                                                                        5
hòa cường                                                                                 5
ưu tiên khu vực ứng viên sinh sống                                                        5
lào cai  3 nơi khác                                                                       5
hokkaido                                                                                  4
bình thuận\r\n\r\nbình thuận                                                              4
lai vung                                                                                  4
châu thành                                                                                4
miền tây                                                                                  4
minh đức cách cầu vượt quán giỏi 100 m                                                    4
kcn vsip 2                                                                                4
nam sơn                                                                                   4
tx dĩ an                                                                                  4
hớn quản                                                                                  4
fpt shop tp rạch giá                                                                      4
q 12                                                                                      4
235 nguyễn trãi                                                                           4
không phải đến công ty                                                                    4
khu đt hc                                                                                 4
đông hải 2                                                                                4
tòa nhà hòa bình green city                                                               4
kiên thành                                                                                4
phường hiệp ninh                                                                          4
q tân phú                                                                                 4
công viên phần mềm quang trung                                                            4
phường cầu kho                                                                            4
rạch sỏi rạch giá                                                                         4
tân châu                                                                                  4
505 minh khai                                                                             4
Central Vietnam                                                                           4
q bình tân  đối diện cn1 trong kcn tân bình                                               4
8c vũ thạnh                                                                               4
gò công tây                                                                               4
phường khuê trung                                                                         4
kiến tường                                                                                4
kcn vsip ii                                                                               4
đại lộ thăng long                                                                         4
68 nguyễn huệ                                                                             4
an dương                                                                                  4
dầu tiếng                                                                                 4
văn phòng công ty cổ phần tập đoàn xd hoà bình                                            4
phường minh đức                                                                           4
khác                                                                                      3
South Central Vietnam                                                                     3
yokohama                                                                                  3
fpt shop vĩnh thuận                                                                       3
kcn ninh hiệp                                                                             3
tỉnh tiền giang                                                                           3
đông hưng thuận                                                                           3
vĩnh thạnh                                                                                3
bắc từ liêm  đối diện công viên hòa bình                                                  3
tỉnh quảng trị                                                                            3
phú giáo                                                                                  3
ngô quyền                                                                                 3
phú tân                                                                                   3
hải tân                                                                                   3
huyện bình giang                                                                          3
ba gps                                                                                    3
thanh oai                                                                                 3
thanh hoá tp thanh hoá                                                                    3
44 hoàng sĩ khải phường 14 quận 8                                                         3
tân phước                                                                                 3
phường an thới                                                                            3
bàu bàng                                                                                  3
tỉnh lộ 43 thủ đức hướng cầu gò dưa                                                       3
fpt shop tháp mười                                                                        3
fpt shop tp cao lãnh                                                                      3
kcn phú mỹ 3                                                                              3
đường thủ khoa huân – p thành nhất – tp buôn ma thuột                                     3
khu ngoại giao đoàn                                                                       3
kcn thăng long                                                                            3
tòa nhà trung yên 1 số 1a vũ phạm hàm cầu giấy                                            3
phiệp bình phước                                                                          3
số 35 lê văn lương                                                                        3
31 võ văn vân                                                                             3
miền nam  3 nơi khác                                                                      3
thái lan                                                                                  2
malaysia                                                                                  2
tokyo                                                                                     2
dak lak\r\ndak nông                                                                       2
tiền giang\r\n\r\ntiền giang\r\n\r\ntiền giang\r\n\r\ntiền giang\r\n\r\ntiền giang        2
bình phước\r\n\r\nbình phước                                                              2
bình phước\r\n\r\nbình phước\r\n\r\nbình phước\r\n\r\nbình phước\r\n\r\nbình phước        2
fpt shop huyện châu thành                                                                 2
phường 17                                                                                 2
830000                                                                                    2
fpt shop trần văn thời                                                                    2
52 dien bien phu street                                                                   2
p 22                                                                                      2
bình long                                                                                 2
cửa hàng keira tống 97 phố huế                                                            2
phường 26                                                                                 2
công ty cổ phần xnk tập đoàn nông sản việt nam                                            2
p cổ nhuế 2                                                                               2
fpt shop thị xã giá rai                                                                   2
thành phố đài bắc                                                                         2
quận bình tân khu tên lửa                                                                 2
879 quốc lộ 13 hiệp bình phước thủ đức                                                    2
công ty thành thành công 158 hồ bá kiện phường 15 quận 10                                 2
phường an lạc                                                                             2

In [33]:
mapping_batch_1 = {
    # Hanoi
    "số 74 phạm văn đồng": "Hanoi",
    "tòa nhà mb 21 cát linh": "Hanoi",
    "toà nhà tng 54a nguyễn chí thanh": "Hanoi",
    "toà nhà tng 54a nguyễn chí than": "Hanoi",
    "số 107 phố xuân quỳnh trung hòa": "Hanoi",
    "số 5 ngõ 70 nguyễn hoàng": "Hanoi",
    "cổ nhuế gần mega market phạm văn đồng": "Hanoi",
    "69b thụy khuê": "Hanoi",
    "khu ngoại giao đoàn": "Hanoi",
    "kcn quang minh mê linh": "Hanoi",
    "vpbank ứng hòa": "Hanoi",
    "tòa nhà trung yên 1 số 1a vũ phạm hàm cầu giấy": "Hanoi",
    "số 35 lê văn lương": "Hanoi",
    "505 minh khai": "Hanoi",
    "đại lộ thăng long": "Hanoi",
    "vpbank cn ba đình": "Hanoi",

    # HCMC
    "toà nhà golden king nguyễn lương bằng quận 7": "Ho Chi Minh City",
    "2604 quốc lộ 1a xã bình chánh": "Ho Chi Minh City",
    "hà huy giáp": "Ho Chi Minh City",
    "khu đô thị an phú an khánh": "Ho Chi Minh City",
    "tp thủ đức bên cạnh trường mầm non kcnc quận 9": "Ho Chi Minh City",
    "q 12": "Ho Chi Minh City",
    "q tân phú": "Ho Chi Minh City",
    "công viên phần mềm quang trung": "Ho Chi Minh City",
    "phường cầu kho": "Ho Chi Minh City",
    "q bình tân  đối diện cn1 trong kcn tân bình": "Ho Chi Minh City",
    "879 quốc lộ 13 hiệp bình phước thủ đức": "Ho Chi Minh City",
    "phường an lạc": "Ho Chi Minh City",

    # Other obvious locations
    "kcn amata": "Dong Nai",
    "kcn long đức": "Dong Nai",
    "bình xuyên": "Vinh Phuc",
    "phú vang": "Hue",
    "cờ đỏ": "Can Tho",
    "tx dĩ an": "Binh Duong",
    "phú giáo": "Binh Duong",
    "bàu bàng": "Binh Duong",
    "thị xã bến cát": "Binh Duong",
    "hớn quản": "Binh Phuoc",
    "bình long": "Binh Phuoc",
    "phước long": "Binh Phuoc",
    "dầu tiếng": "Binh Duong",
    "hải hà": "Quang Ninh",
    "lai vung": "Dong Thap",
    "gò công tây": "Tien Giang",
    "kiến tường": "Long An",
    "tân châu": "An Giang",
    "phường hiệp ninh": "Tay Ninh",
    "hoài đức": "Hanoi",
    "thanh oai": "Hanoi",
    "hải dương": "Hai Duong",
    "mỹ tho": "Tien Giang",
}

In [34]:
clean_df["city"] = clean_df["city"].replace(mapping_batch_1)

In [35]:
clean_df["city"].value_counts()

city
Ho Chi Minh City         27566
Hanoi                    27505
Binh Duong                4090
Dong Nai                  2677
Hai Phong                 1749
                         ...
lào cai  6 nơi khác          1
thanh hoá  2 nơi khác        1
tuân nguyễnnguyn             1
phường 19                    1
japan                        1
Name: count, Length: 205, dtype: int64

In [36]:
clean_df["city"].value_counts().tail(100)

city
fpt shop tp rạch giá      4
235 nguyễn trãi           4
không phải đến công ty    4
khu đt hc                 4
đông hải 2                4
                         ..
lào cai  6 nơi khác       1
thanh hoá  2 nơi khác     1
tuân nguyễnnguyn          1
phường 19                 1
japan                     1
Name: count, Length: 100, dtype: int64

In [37]:
print(clean_df["city"].value_counts().to_string())

city
Ho Chi Minh City                                                                      27566
Hanoi                                                                                 27505
Binh Duong                                                                             4090
Dong Nai                                                                               2677
Hai Phong                                                                              1749
Long An                                                                                1650
Da Nang                                                                                1441
Hung Yen                                                                               1149
Bac Ninh                                                                               1060
Ba Ria - Vung Tau                                                                       945
Tay Ninh                                                                                722
Can Tho                                                                                 688
Quang Ninh                                                                              628
Hai Duong                                                                               620
Nghe An                                                                                 573
Khanh Hoa                                                                               558
Bac Giang                                                                               511
Ha Nam                                                                                  509
Dien Bien                                                                               508
Kien Giang                                                                              479
Thai Binh                                                                               457
Lam Dong                                                                                442
An Giang                                                                                398
Dak Lak                                                                                 358
Binh Phuoc                                                                              348
Thanh Hoa                                                                               343
Tien Giang                                                                              330
Nam Dinh                                                                                322
Thai Nguyen                                                                             319
Phu Tho                                                                                 316
Quang Nam                                                                               297
Hue                                                                                     293
Vinh Phuc                                                                               287
Binh Thuan                                                                              264
Ben Tre                                                                                 262
Nationwide                                                                              244
Binh Dinh                                                                               234
Phu Yen                                                                                 225
Dong Thap                                                                               222
Quang Ngai                                                                              219
Soc Trang                                                                               214
Ca Mau                                                                                  210
Ninh Binh                                                                               207
Kon Tum                                                                                 179
Bac Lieu                                                                                178
Gia Lai                                                                                 170
Hau Giang                                                                               161
Ha Tinh                                                                                 153
Hoa Binh                                                                                150
Son La                                                                                  140
Vietnam                                                                                 140
Vinh Long                                                                               132
Quang Binh                                                                              131
Yen Bai                                                                                 125
Lang Son                                                                                116
Lao Cai                                                                                  99
Ninh Thuan                                                                               96
Dak Nong                                                                                 74
Ha Giang                                                                                 71
Tuyen Quang                                                                              67
Cao Bang                                                                                 46
Tra Vinh                                                                                 42
Quang Tri                                                                                39
Bac Kan                                                                                  39
Overseas                                                                                 36
Lai Chau                                                                                 33
Province-wide                                                                            28
Northern Vietnam                                                                         26
nhật bản                                                                                 22
Southern Vietnam                                                                         22
International                                                                            18
Remote                                                                                   18
Multiple districts                                                                       16
california fitness  yoga                                                                 10
các văn phòng đại diện tại các quận                                                      10
số 04 lê liễu                                                                            10
thuận thành                                                                               9
Region-wide                                                                               9
phường bình thuận                                                                         9
Central Highlands                                                                         8
pphú lợi                                                                                  8
252 hạ hội tân lậpmiền bắc                                                                8
fpt shop thành phố vĩnh long                                                              7
đường số 4                                                                                6
phú lương                                                                                 6
lotte tây hồvincom bà triệutttm the gardensavico long biên                                6
tòa chung cư ban cơ yếu chính phủ                                                         6
kv đông nam bộ                                                                            5
phường tân chánh hiệp                                                                     5
41 thép mới                                                                               5
dự án quận tây hồ                                                                         5
91 nguyễn chí thanh                                                                       5
bình tân khu tên lửa                                                                      5
161 võ nguyễn giáp                                                                        5
169 nguyễn ngọc vũ                                                                        5
hòa cường                                                                                 5
ưu tiên khu vực ứng viên sinh sống                                                        5
lào cai  3 nơi khác                                                                       5
hokkaido                                                                                  4
bình thuận\r\n\r\nbình thuận                                                              4
châu thành                                                                                4
miền tây                                                                                  4
minh đức cách cầu vượt quán giỏi 100 m                                                    4
kcn vsip 2                                                                                4
nam sơn                                                                                   4
fpt shop tp rạch giá                                                                      4
235 nguyễn trãi                                                                           4
không phải đến công ty                                                                    4
khu đt hc                                                                                 4
đông hải 2                                                                                4
tòa nhà hòa bình green city                                                               4
kiên thành                                                                                4
rạch sỏi rạch giá                                                                         4
Central Vietnam                                                                           4
8c vũ thạnh                                                                               4
phường khuê trung                                                                         4
kcn vsip ii                                                                               4
68 nguyễn huệ                                                                             4
an dương                                                                                  4
văn phòng công ty cổ phần tập đoàn xd hoà bình                                            4
phường minh đức                                                                           4
khác                                                                                      3
South Central Vietnam                                                                     3
yokohama                                                                                  3
fpt shop vĩnh thuận                                                                       3
kcn ninh hiệp                                                                             3
tỉnh tiền giang                                                                           3
đông hưng thuận                                                                           3
vĩnh thạnh                                                                                3
bắc từ liêm  đối diện công viên hòa bình                                                  3
tỉnh quảng trị                                                                            3
ngô quyền                                                                                 3
phú tân                                                                                   3
hải tân                                                                                   3
huyện bình giang                                                                          3
ba gps                                                                                    3
thanh hoá tp thanh hoá                                                                    3
44 hoàng sĩ khải phường 14 quận 8                                                         3
tân phước                                                                                 3
phường an thới                                                                            3
tỉnh lộ 43 thủ đức hướng cầu gò dưa                                                       3
fpt shop tháp mười                                                                        3
fpt shop tp cao lãnh                                                                      3
kcn phú mỹ 3                                                                              3
đường thủ khoa huân – p thành nhất – tp buôn ma thuột                                     3
kcn thăng long                                                                            3
phiệp bình phước                                                                          3
31 võ văn vân                                                                             3
miền nam  3 nơi khác                                                                      3
thái lan                                                                                  2
malaysia                                                                                  2
tokyo                                                                                     2
dak lak\r\ndak nông                                                                       2
tiền giang\r\n\r\ntiền giang\r\n\r\ntiền giang\r\n\r\ntiền giang\r\n\r\ntiền giang        2
bình phước\r\n\r\nbình phước                                                              2
bình phước\r\n\r\nbình phước\r\n\r\nbình phước\r\n\r\nbình phước\r\n\r\nbình phước        2
fpt shop huyện châu thành                                                                 2
phường 17                                                                                 2
830000                                                                                    2
fpt shop trần văn thời                                                                    2
52 dien bien phu street                                                                   2
p 22                                                                                      2
cửa hàng keira tống 97 phố huế                                                            2
phường 26                                                                                 2
công ty cổ phần xnk tập đoàn nông sản việt nam                                            2
p cổ nhuế 2                                                                               2
fpt shop thị xã giá rai                                                                   2
thành phố đài bắc                                                                         2
quận bình tân khu tên lửa                                                                 2
công ty thành thành công 158 hồ bá kiện phường 15 quận 10                                 2
times city                                                                                2
kcx sai gon linh trung 1                                                                  2
kcn quế                                                                                   2
p hòa thạnh                                                                               2
phường trung liệt                                                                         2
phường 4                                                                                  2
p thạnh mỹ lợi                                                                            2
phường tân đông hiệp                                                                      2
159 quốc lộ 1k                                                                            2
the golden palm 21 lê văn lương                                                           2
tây nam linh đàm                                                                          2
miền nam  2 nơi khác                                                                      2
attapeu                                                                                   1
đồng bằng sông hồng                                                                       1
kratie                                                                                    1
đồng bằng sông cửu long                                                                   1
kampong speu                                                                              1
bangkok                                                                                   1
hòa bình\r\nbắc cạn                                                                       1
lào cai\r\nhòa bình                                                                       1
kv bắc trung bộ\r\nkv nam trung bộ\r\nđồng bằng sông cửu long                             1
champasak                                                                                 1
gò vấp                                                                                  1
lô cn5a cụm công nghiệp gia lập xã gia lập huyện gia viễn                                 1
kcn sóng thần 1                                                                           1
công ty tnhh iljin display vina                                                           1
647 quang trung phường 11 quận gò vấp                                                     1
bình phước b                                                                              1
54a nguyễn chí thanh                                                                      1
miền nam  4 nơi khác                                                                      1
lào cai  6 nơi khác                                                                       1
thanh hoá  2 nơi khác                                                                     1
tuân nguyễnnguyn                                                                          1
phường 19                                                                                 1
japan                                                                                     1

In [38]:
mapping_batch_2 = {
    # Hanoi
    "252 hạ hội tân lậpmiền bắc": "Hanoi",
    "phú lương": "Hanoi",
    "lotte tây hồvincom bà triệutttm the gardensavico long biên": "Hanoi",
    "tòa chung cư ban cơ yếu chính phủ": "Hanoi",
    "dự án quận tây hồ": "Hanoi",
    "91 nguyễn chí thanh": "Hanoi",
    "169 nguyễn ngọc vũ": "Hanoi",
    "bắc từ liêm  đối diện công viên hòa bình": "Hanoi",
    "kcn ninh hiệp": "Hanoi",
    "kcn thăng long": "Hanoi",
    "p cổ nhuế 2": "Hanoi",
    "phường trung liệt": "Hanoi",
    "the golden palm 21 lê văn lương": "Hanoi",
    "tây nam linh đàm": "Hanoi",
    "times city": "Hanoi",
    
    # Ho Chi Minh City
    "phường tân chánh hiệp": "Ho Chi Minh City",
    "bình tân khu tên lửa": "Ho Chi Minh City",
    "161 võ nguyễn giáp": "Ho Chi Minh City",
    "44 hoàng sĩ khải phường 14 quận 8": "Ho Chi Minh City",
    "tỉnh lộ 43 thủ đức hướng cầu gò dưa": "Ho Chi Minh City",
    "phiệp bình phước": "Ho Chi Minh City",
    "31 võ văn vân": "Ho Chi Minh City",
    "quận bình tân khu tên lửa": "Ho Chi Minh City",
    "công ty thành thành công 158 hồ bá kiện phường 15 quận 10": "Ho Chi Minh City",
    "kcx sai gon linh trung 1": "Ho Chi Minh City",
    "p hòa thạnh": "Ho Chi Minh City",
    "p thạnh mỹ lợi": "Ho Chi Minh City",
    "gò vấp": "Ho Chi Minh City",
    "647 quang trung phường 11 quận gò vấp": "Ho Chi Minh City",
    
    # Hai Phong
    "đông hải 2": "Hai Phong",
    "an dương": "Hai Phong",
    "ngô quyền": "Hai Phong",
    
    # Hai Duong
    "hải tân": "Hai Duong",
    "huyện bình giang": "Hai Duong",
    
    # Binh Duong
    "pphú lợi": "Binh Duong",
    "kcn vsip 2": "Binh Duong",
    "kcn vsip ii": "Binh Duong",
    "kcn sóng thần 1": "Binh Duong",
    
    # Dong Nai
    "kcn vsip 2": "Binh Duong",  # keep this one in Binh Duong; see note below
    
    # Ba Ria - Vung Tau
    "kcn phú mỹ 3": "Ba Ria - Vung Tau",
    
    # Thanh Hoa
    "thanh hoá tp thanh hoá": "Thanh Hoa",
    
    # Tien Giang
    "tân phước": "Tien Giang",
    "tỉnh tiền giang": "Tien Giang",
    
    # Dong Thap
    "fpt shop tháp mười": "Dong Thap",
    "fpt shop tp cao lãnh": "Dong Thap",
    
    # Kien Giang
    "fpt shop tp rạch giá": "Kien Giang",
    "fpt shop vĩnh thuận": "Kien Giang",
    "rạch sỏi rạch giá": "Kien Giang",
    
    # Ca Mau
    "fpt shop trần văn thời": "Ca Mau",
    
    # Bac Lieu
    "fpt shop thị xã giá rai": "Bac Lieu",
    
    # Vinh Long
    "fpt shop thành phố vĩnh long": "Vinh Long",
    
    # Ninh Binh
    "lô cn5a cụm công nghiệp gia lập xã gia lập huyện gia viễn": "Ninh Binh",
    
    # Taiwan
    "thành phố đài bắc": "Taiwan",
    
    # Japan
    "japan": "Japan",
    "nhật bản": "Japan",
    "tokyo": "Japan",
    "yokohama": "Japan",
    "hokkaido": "Japan",
    
    # Thailand
    "thái lan": "Thailand",
    "bangkok": "Thailand",
    
    # Malaysia
    "malaysia": "Malaysia",
}

In [39]:
district_mapping = {
    "phường bình thuận": "Ho Chi Minh City",
    "đường số 4": "Unknown",
    "nam sơn": "Unknown",
    "hòa cường": "Da Nang",
    "phường khuê trung": "Da Nang",
    "phường minh đức": "Unknown",
    "vĩnh thạnh": "Unknown",
    "phú tân": "Unknown",
    "an dương": "Hai Phong",
    "ngô quyền": "Hai Phong",
    "hải tân": "Hai Duong",
    "tân phước": "Tien Giang",
}

In [40]:
clean_df["city"] = clean_df["city"].replace(mapping_batch_2)

In [41]:
clean_df["city"] = clean_df["city"].replace(district_mapping)

In [42]:
clean_df["city"] = (
    clean_df["city"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [43]:
clean_df["city"].value_counts().tail(100)

city
Ninh Binh               208
Bac Lieu                180
Kon Tum                 179
Gia Lai                 170
Hau Giang               161
                       ...
miền nam 4 nơi khác       1
lào cai 6 nơi khác        1
thanh hoá 2 nơi khác      1
tuân nguyễnnguyn          1
phường 19                 1
Name: count, Length: 100, dtype: int64

In [44]:
print(clean_df["city"].value_counts().to_string())

city
Ho Chi Minh City                                           27614
Hanoi                                                      27565
Binh Duong                                                  4107
Dong Nai                                                    2677
Hai Phong                                                   1760
Long An                                                     1650
Da Nang                                                     1450
Hung Yen                                                    1149
Bac Ninh                                                    1060
Ba Ria - Vung Tau                                            948
Tay Ninh                                                     722
Can Tho                                                      688
Quang Ninh                                                   628
Hai Duong                                                    626
Nghe An                                                      573
Khanh Hoa                                                    558
Bac Giang                                                    511
Ha Nam                                                       509
Dien Bien                                                    508
Kien Giang                                                   490
Thai Binh                                                    457
Lam Dong                                                     442
An Giang                                                     398
Dak Lak                                                      358
Binh Phuoc                                                   348
Thanh Hoa                                                    346
Tien Giang                                                   336
Nam Dinh                                                     322
Thai Nguyen                                                  319
Phu Tho                                                      316
Quang Nam                                                    297
Hue                                                          293
Vinh Phuc                                                    287
Binh Thuan                                                   264
Ben Tre                                                      262
Nationwide                                                   244
Binh Dinh                                                    234
Dong Thap                                                    228
Phu Yen                                                      225
Quang Ngai                                                   219
Soc Trang                                                    214
Ca Mau                                                       212
Ninh Binh                                                    208
Bac Lieu                                                     180
Kon Tum                                                      179
Gia Lai                                                      170
Hau Giang                                                    161
Ha Tinh                                                      153
Hoa Binh                                                     150
Son La                                                       140
Vietnam                                                      140
Vinh Long                                                    139
Quang Binh                                                   131
Yen Bai                                                      125
Lang Son                                                     116
Lao Cai                                                       99
Ninh Thuan                                                    96
Dak Nong                                                      74
Ha Giang                                                      71
Tuyen Quang                                                   67
Cao Bang                                                      46
Tra Vinh                                                      42
Quang Tri                                                     39
Bac Kan                                                       39
Overseas                                                      36
Lai Chau                                                      33
Japan                                                         32
Province-wide                                                 28
Northern Vietnam                                              26
Southern Vietnam                                              22
Unknown                                                       20
International                                                 18
Remote                                                        18
Multiple districts                                            16
california fitness yoga                                       10
các văn phòng đại diện tại các quận                           10
số 04 lê liễu                                                 10
thuận thành                                                    9
Region-wide                                                    9
Central Highlands                                              8
kv đông nam bộ                                                 5
41 thép mới                                                    5
ưu tiên khu vực ứng viên sinh sống                             5
lào cai 3 nơi khác                                             5
bình thuận bình thuận                                          4
châu thành                                                     4
miền tây                                                       4
minh đức cách cầu vượt quán giỏi 100 m                         4
235 nguyễn trãi                                                4
không phải đến công ty                                         4
khu đt hc                                                      4
tòa nhà hòa bình green city                                    4
kiên thành                                                     4
Central Vietnam                                                4
8c vũ thạnh                                                    4
68 nguyễn huệ                                                  4
văn phòng công ty cổ phần tập đoàn xd hoà bình                 4
khác                                                           3
South Central Vietnam                                          3
Thailand                                                       3
đông hưng thuận                                                3
tỉnh quảng trị                                                 3
ba gps                                                         3
phường an thới                                                 3
đường thủ khoa huân – p thành nhất – tp buôn ma thuột          3
miền nam 3 nơi khác                                            3
Malaysia                                                       2
dak lak dak nông                                               2
tiền giang tiền giang tiền giang tiền giang tiền giang         2
bình phước bình phước                                          2
bình phước bình phước bình phước bình phước bình phước         2
fpt shop huyện châu thành                                      2
phường 17                                                      2
830000                                                         2
52 dien bien phu street                                        2
p 22                                                           2
cửa hàng keira tống 97 phố huế                                 2
phường 26                                                      2
công ty cổ phần xnk tập đoàn nông sản việt nam                 2
Taiwan                                                         2
kcn quế                                                        2
phường 4                                                       2
phường tân đông hiệp                                           2
159 quốc lộ 1k                                                 2
miền nam 2 nơi khác                                            2
attapeu                                                        1
đồng bằng sông hồng                                            1
kratie                                                         1
đồng bằng sông cửu long                                        1
kampong speu                                                   1
hòa bình bắc cạn                                               1
lào cai hòa bình                                               1
kv bắc trung bộ kv nam trung bộ đồng bằng sông cửu long        1
champasak                                                      1
công ty tnhh iljin display vina                                1
bình phước b                                                   1
54a nguyễn chí thanh                                           1
miền nam 4 nơi khác                                            1
lào cai 6 nơi khác                                             1
thanh hoá 2 nơi khác                                           1
tuân nguyễnnguyn                                               1
phường 19                                                      1

In [45]:
mapping_final = {
    # Specific Vietnamese locations
    "thuận thành": "Bac Ninh",
    "minh đức cách cầu vượt quán giỏi 100 m": "Hai Phong",
    "tòa nhà hòa bình green city": "Hanoi",
    "kiên thành": "Lao Cai",
    "đông hưng thuận": "Ho Chi Minh City",
    "tỉnh quảng trị": "Quang Tri",
    "phường an thới": "Ho Chi Minh City",
    "đường thủ khoa huân – p thành nhất – tp buôn ma thuột": "Dak Lak",
    "phường tân đông hiệp": "Binh Duong",
    "159 quốc lộ 1k": "Binh Duong",
    
    # Specific businesses / locations
    "cửa hàng keira tống 97 phố huế": "Hanoi",
    
    # Countries
    "Thailand": "Thailand",
    "Malaysia": "Malaysia",
    "Taiwan": "Taiwan",
    "attapeu": "Laos",
    "kratie": "Cambodia",
    "kampong speu": "Cambodia",
    "champasak": "Laos",
}

In [46]:
clean_df["city"] = clean_df["city"].replace(mapping_final)

In [47]:
special_mapping = {
    "Multiple districts": "Multiple locations",
    "các văn phòng đại diện tại các quận": "Multiple locations",

    "Region-wide": "Region-wide",
    "Central Highlands": "Central Highlands",
    "kv đông nam bộ": "Southeast Vietnam",
    "miền tây": "Mekong Delta",
    "Central Vietnam": "Central Vietnam",
    "South Central Vietnam": "South Central Vietnam",

    "ưu tiên khu vực ứng viên sinh sống": "Location flexible",
    "không phải đến công ty": "Remote",
    
    "khác": "Other",
}

In [48]:
clean_df["city"] = clean_df["city"].replace(special_final)

NameError: name 'special_final' is not defined

In [49]:
clean_df["city"] = clean_df["city"].replace(special_mapping)

In [50]:
multiple_locations = [
    "lào cai 3 nơi khác",
    "miền nam 3 nơi khác",
    "dak lak dak nông",
    "miền nam 2 nơi khác",
    "hòa bình bắc cạn",
    "lào cai hòa bình",
    "kv bắc trung bộ kv nam trung bộ đồng bằng sông cửu long",
    "miền nam 4 nơi khác",
    "lào cai 6 nơi khác",
    "thanh hoá 2 nơi khác",
]

In [51]:
clean_df.loc[
    clean_df["city"].isin(multiple_locations),
    "city"
] = "Multiple locations"

In [52]:
repeated_mapping = {
    "bình thuận bình thuận": "Binh Thuan",
    "tiền giang tiền giang tiền giang tiền giang tiền giang": "Tien Giang",
    "bình phước bình phước": "Binh Phuoc",
    "bình phước bình phước bình phước bình phước bình phước": "Binh Phuoc",
}

In [53]:
clean_df["city"] = clean_df["city"].replace(repeated_mapping)

In [54]:
unknown_values = [
    "california fitness yoga",
    "số 04 lê liễu",
    "41 thép mới",
    "235 nguyễn trãi",
    "khu đt hc",
    "8c vũ thạnh",
    "68 nguyễn huệ",
    "ba gps",
    "fpt shop huyện châu thành",
    "phường 17",
    "830000",
    "52 dien bien phu street",
    "p 22",
    "phường 26",
    "công ty cổ phần xnk tập đoàn nông sản việt nam",
    "kcn quế",
    "phường 4",
    "54a nguyễn chí thanh",
    "tuân nguyễnnguyn",
    "phường 19",
]

clean_df.loc[
    clean_df["city"].isin(unknown_values),
    "city"
] = "Unknown"

In [55]:
clean_df["city"].value_counts()

city
Ho Chi Minh City                   27620
Hanoi                              27571
Binh Duong                          4111
Dong Nai                            2677
Hai Phong                           1764
                                   ...
Taiwan                                 2
đồng bằng sông hồng                    1
đồng bằng sông cửu long                1
công ty tnhh iljin display vina        1
bình phước b                           1
Name: count, Length: 93, dtype: int64

In [56]:
clean_df["city"].value_counts().tail(30)

city
Quang Tri                                         42
Tra Vinh                                          42
Bac Kan                                           39
Overseas                                          36
Lai Chau                                          33
Japan                                             32
Province-wide                                     28
Northern Vietnam                                  26
Remote                                            22
Southern Vietnam                                  22
International                                     18
Region-wide                                        9
Central Highlands                                  8
Southeast Vietnam                                  5
Location flexible                                  5
châu thành                                         4
Mekong Delta                                       4
Central Vietnam                                    4
văn phòng công ty cổ phần tập đoàn xd hoà bình     4
Other                                              3
South Central Vietnam                              3
Thailand                                           3
Laos                                               2
Cambodia                                           2
Malaysia                                           2
Taiwan                                             2
đồng bằng sông hồng                                1
đồng bằng sông cửu long                            1
công ty tnhh iljin display vina                    1
bình phước b                                       1
Name: count, dtype: int64

In [57]:
clean_df.loc[
    clean_df["city"].eq("châu thành"),
    "city"
] = "Unknown"

In [58]:
clean_df.loc[
    clean_df["city"].eq("văn phòng công ty cổ phần tập đoàn xd hoà bình"),
    "city"
] = "Unknown"

In [59]:
clean_df.loc[
    clean_df["city"].eq("công ty tnhh iljin display vina"),
    "city"
] = "Unknown"

In [60]:
clean_df.loc[
    clean_df["city"].eq("bình phước b"),
    "city"
] = "Binh Phuoc"

In [61]:
region_mapping = {
    "đồng bằng sông hồng": "Red River Delta",
    "đồng bằng sông cửu long": "Mekong Delta",
}

In [62]:
clean_df["city"] = clean_df["city"].replace(region_mapping)

In [63]:
final_mapping = {
    "châu thành": "Unknown",
    "văn phòng công ty cổ phần tập đoàn xd hoà bình": "Unknown",
    "công ty tnhh iljin display vina": "Unknown",
    "bình phước b": "Binh Phuoc",
    
    "đồng bằng sông hồng": "Red River Delta",
    "đồng bằng sông cửu long": "Mekong Delta",
}

clean_df["city"] = clean_df["city"].replace(final_mapping)

In [64]:
clean_df["city"].value_counts().tail(30)

city
Dak Nong                 74
Ha Giang                 71
Tuyen Quang              67
Cao Bang                 46
Multiple locations       44
Quang Tri                42
Tra Vinh                 42
Bac Kan                  39
Overseas                 36
Lai Chau                 33
Japan                    32
Province-wide            28
Northern Vietnam         26
Remote                   22
Southern Vietnam         22
International            18
Region-wide               9
Central Highlands         8
Southeast Vietnam         5
Mekong Delta              5
Location flexible         5
Central Vietnam           4
Other                     3
South Central Vietnam     3
Thailand                  3
Laos                      2
Cambodia                  2
Malaysia                  2
Taiwan                    2
Red River Delta           1
Name: count, dtype: int64

In [65]:
clean_df.to_csv("jobz_cleaned.csv", index=False, encoding="utf-8-sig")

In [66]:
print(clean_df["salary"].head(20).to_string())

0      15 tr - 50 tr vnd
1       8 tr - 11 tr vnd
2      20 tr - 30 tr vnd
3        800 - 1,500 usd
4      10 tr - 50 tr vnd
5      15 tr - 40 tr vnd
6      15 tr - 50 tr vnd
7      10 tr - 18 tr vnd
8      15 tr - 20 tr vnd
9      17 tr - 22 tr vnd
10    9,5 tr - 12 tr vnd
11     14 tr - 25 tr vnd
12     15 tr - 18 tr vnd
13      8 tr - 10 tr vnd
14     12 tr - 15 tr vnd
15     25 tr - 30 tr vnd
16     10 tr - 15 tr vnd
17     10 tr - 25 tr vnd
18    8,5 tr - 10 tr vnd
19     10 tr - 15 tr vnd

In [67]:
print(clean_df["salary"].dtype)

str

In [68]:
print(clean_df["salary"].value_counts().head(30).to_string())

salary
10 - 15 triệu vnđ    2009
8 - 15 triệu vnđ     1773
10 tr - 15 tr vnd    1713
8 - 10 triệu vnđ     1320
15 tr - 20 tr vnd    1293
10 - 20 triệu vnđ    1288
8 - 12 triệu vnđ     1278
7 - 10 triệu vnđ     1209
15 - 30 triệu vnđ    1193
đến 20 triệu vnđ     1168
15 - 20 triệu vnđ    1168
10 - 15 triệu        1128
10 - 12 triệu vnđ    1043
12 - 15 triệu vnđ    1030
15 - 25 triệu vnđ    1016
12 tr - 15 tr vnd     979
7 - 9 triệu vnđ       954
8 - 15 triệu          881
8 tr - 10 tr vnd      818
15 - 30 triệu         811
8 tr - 12 tr vnd      781
10 - 20 triệu         766
15 - 20 triệu         722
10 tr - 12 tr vnd     693
8 - 12 triệu          691
10 tr - 20 tr vnd     674
8 - 20 triệu vnđ      661
6 - 8 triệu vnđ       652
9 - 12 triệu vnđ      641
8 tr - 15 tr vnd      628

In [69]:
print(clean_df["salary"].value_counts().to_string())

salary
10 - 15 triệu vnđ                2009
8 - 15 triệu vnđ                 1773
10 tr - 15 tr vnd                1713
8 - 10 triệu vnđ                 1320
15 tr - 20 tr vnd                1293
10 - 20 triệu vnđ                1288
8 - 12 triệu vnđ                 1278
7 - 10 triệu vnđ                 1209
15 - 30 triệu vnđ                1193
đến 20 triệu vnđ                 1168
15 - 20 triệu vnđ                1168
10 - 15 triệu                    1128
10 - 12 triệu vnđ                1043
12 - 15 triệu vnđ                1030
15 - 25 triệu vnđ                1016
12 tr - 15 tr vnd                 979
7 - 9 triệu vnđ                   954
8 - 15 triệu                      881
8 tr - 10 tr vnd                  818
15 - 30 triệu                     811
8 tr - 12 tr vnd                  781
10 - 20 triệu                     766
15 - 20 triệu                     722
10 tr - 12 tr vnd                 693
8 - 12 triệu                      691
10 tr - 20 tr vnd                 674
8 - 20 triệu vnđ                  661
6 - 8 triệu vnđ                   652
9 - 12 triệu vnđ                  641
8 tr - 15 tr vnd                  628
15 tr - 25 tr vnd                 585
9 tr - 35 tr vnd                  542
20 tr - 30 tr vnd                 532
7 - 15 triệu vnđ                  521
9 tr - 12 tr vnd                  513
12 - 20 triệu vnđ                 507
13 tr - 15 tr vnd                 489
6 - 9 triệu vnđ                   489
7 tr - 9 tr vnd                   482
12 - 18 triệu vnđ                 470
20 tr - 25 tr vnd                 467
8 - 10 triệu                      458
15 - 25 triệu                     454
7 - 12 triệu vnđ                  418
12 tr - 13 tr vnd                 406
9 - 15 triệu vnđ                  397
15 tr - 30 tr vnd                 395
12 tr - 20 tr vnd                 394
20 - 30 triệu vnđ                 390
12 tr - 18 tr vnd                 373
9 - 15 triệu                      369
12 - 20 triệu                     362
12 - 15 triệu                     359
8 tr - 20 tr vnd                  352
6 - 10 triệu vnđ                  352
10 - 13 triệu vnđ                 348
8 - 20 triệu                      345
từ 10 triệu vnđ                   343
7 tr - 10 tr vnd                  338
10 - 30 triệu vnđ                 338
12 tr - 14 tr vnd                 332
9 tr - 15 tr vnd                  326
15 tr - 18 tr vnd                 325
7 - 8 triệu vnđ                   316
10 tr - 35 tr vnd                 311
10 tr - 13 tr vnd                 301
9 - 10 triệu vnđ                  298
18 tr - 25 tr vnd                 292
12 - 14 triệu vnđ                 291
10 - 12 triệu                     288
2,5 tr - 15 tr vnd                287
10 tr - 14 tr vnd                 271
7 - 10 triệu                      271
7 - 20 triệu vnđ                  271
10 - 14 triệu vnđ                 269
25 tr - 30 tr vnd                 268
9 - 11 triệu vnđ                  267
10 - 30 triệu                     266
20 - 25 triệu vnđ                 260
20 - 40 triệu vnđ                 255
13 - 15 triệu                     252
từ 8 triệu vnđ                    250
6 tr - 8 tr vnd                   245
9 - 12 triệu                      239
8 - 9 triệu vnđ                   239
20 - 30 triệu                     237
13 - 15 triệu vnđ                 236
7 - 15 triệu                      226
13 - 18 triệu vnđ                 223
9 tr - 11 tr vnd                  222
từ 20 triệu vnđ                   216
25 tr - 35 tr vnd                 215
12 tr - 16 tr vnd                 213
từ 15 triệu vnđ                   210
7 tr - 15 tr vnd                  208
15 - 18 triệu vnđ                 207
30 tr - 40 tr vnd                 201
5 - 20 triệu vnđ                  200
8 - 30 triệu                      198
10 - 25 triệu vnđ                 192
13 tr - 18 tr vnd                 184
10 - 18 triệu vnđ                 175
9 - 20 triệu vnđ                  173
12 - 16 triệu vnđ                 173
từ 12 triệu vnđ                   173
13 tr - 14 tr vnd                 172
10 tr - 30 tr vnd                 170
10 - 25 triệu                     169
8 - 11 triệu vnđ                  169
25 - 30 triệu vnđ                 168
10 - 13 triệu                     167
8 - 13 triệu vnđ                  166
trên 15 tr vnd                    163
9 - 13 triệu vnđ                  163
12 tr - 17 tr vnd                 162
14 tr - 18 tr vnd                 161
6 - 7 triệu vnđ                   161
10 tr - 18 tr vnd                 160
9 tr - 10 tr vnd                  160
16 - 45 triệu vnđ                 152
từ 9 triệu vnđ                    152
14 tr - 16 tr vnd                 151
6 - 8 triệu                       151
12 - 18 triệu                     149
9 tr - 20 tr vnd                  148
18 tr - 20 tr vnd                 146
10 - 18 triệu                     145
9 tr - 13 tr vnd                  144
5 - 7 triệu vnđ                   144
15 tr - 17 tr vnd                 143
7 tr - 8 tr vnd                   143
18 - 25 triệu vnđ                 142
30 tr - 50 tr vnd                 141
7 - 12 triệu                      140
8 tr - 30 tr vnd                  139
7 - 9 triệu                       139
8 tr - 9 tr vnd                   138
2 - 3 triệu vnđ                   138
30 - 50 triệu vnđ                 138
20 - 50 triệu                     137
6 - 15 triệu vnđ                  137
6 tr - 9 tr vnd                   136
12 - 17 triệu vnđ                 136
12 - 25 triệu vnđ                 136
15 - 17 triệu vnđ                 134
12 - 25 triệu                     130
10 tr - 25 tr vnd                 128
12 - 17 triệu                     128
13 tr - 20 tr vnd                 127
18 - 20 triệu vnđ                 126
5 tr - 15 tr vnd                  125
7 tr - 12 tr vnd                  124
20 tr - 35 tr vnd                 122
8 - 30 triệu vnđ                  122
15 - 40 triệu vnđ                 122
15 - 50 triệu vnđ                 120
trên 10 tr vnd                    119
11 tr - 13 tr vnd                 118
20 - 50 triệu vnđ                 116
6 - 15 triệu                      115
14 - 18 triệu vnđ                 115
13 tr - 17 tr vnd                 114
6 tr - 10 tr vnd                  114
20 tr - 40 tr vnd                 114
20 - 25 triệu                     114
9 - 11 triệu                      113
11 tr - 15 tr vnd                 112
15 tr - 22 tr vnd                 112
5 - 9 triệu vnđ                   110
18 - 30 triệu vnđ                 109
8 - 14 triệu vnđ                  106
13 tr - 16 tr vnd                 105
14 tr - 20 tr vnd                 104
10 - 60 triệu                     102
10 - 50 triệu vnđ                 102
25 tr - 40 tr vnd                 101
11 - 15 triệu vnđ                 100
8 tr - 11 tr vnd                   99
18 tr - 22 tr vnd                  99
6 - 10 triệu                       99
14 tr - 17 tr vnd                  98
8 - 11 triệu                       97
1 - 3 triệu vnđ                    97
trên 20 tr vnd                     96
3 - 5 triệu vnđ                    96
16 tr - 20 tr vnd                  95
5 - 100 triệu vnđ                  95
3 - 4 triệu vnđ                    95
12 tr - 25 tr vnd                  94
13 - 20 triệu                      94
16 - 20 triệu vnđ                  93
13 - 20 triệu vnđ                  92
25 - 40 triệu vnđ                  92
6 - 12 triệu                       91
11 - 13 triệu vnđ                  91
14 - 16 triệu vnđ                  91
17 tr - 20 tr vnd                  90
9 - 14 triệu vnđ                   90
14 - 20 triệu vnđ                  89
3 - 6 triệu vnđ                    89
9 tr - 14 tr vnd                   88
8 tr - 13 tr vnd                   88
15 tr - 35 tr vnd                  86
18 - 25 triệu                      86
12 - 14 triệu                      86
12 - 16 triệu                      86
20 - 40 triệu                      85
đến 15 triệu vnđ                   85
5 - 8 triệu vnđ                    85
10 tr - 11 tr vnd                  84
7 - 25 triệu                       84
10 - 50 triệu                      81
6 - 12 triệu vnđ                   81
10 - 16 triệu                      80
trên 12 tr vnd                     79
từ 7 triệu vnđ                     79
30 tr - 35 tr vnd                  78
trên 8 tr vnd                      78
10 tr - 16 tr vnd                  78
6 - 9 triệu                        78
7 - 20 triệu                       78
10 - 100 triệu                     78
9 - 20 triệu                       78
8 - 25 triệu vnđ                   78
15 - 50 triệu                      77
5 - 10 triệu vnđ                   77
20 - 35 triệu vnđ                  77
11 - 14 triệu vnđ                  77
6 - 20 triệu vnđ                   77
10 - 16 triệu vnđ                  77
6,5 tr - 9 tr vnd                  76
15 - 18 triệu                      75
13 - 18 triệu                      74
8 - 25 triệu                       73
2 - 4 triệu vnđ                    73
30 - 40 triệu vnđ                  73
12 - 30 triệu vnđ                  73
7 - 8 triệu                        72
25 - 35 triệu vnđ                  72
13 - 16 triệu vnđ                  70
30 - 100 triệu vnđ                 70
18 tr - 30 tr vnd                  69
14 - 17 triệu vnđ                  69
16 tr - 18 tr vnd                  68
7 tr - 20 tr vnd                   68
15 - 40 triệu                      68
10 - 14 triệu                      68
7 - 30 triệu vnđ                   68
5 - 6 triệu vnđ                    68
trên 25 tr vnd                     67
11 - 12 triệu vnđ                  67
7 - 13 triệu vnđ                   66
12 tr - 30 tr vnd                  65
8 - 18 triệu                       65
15 tr - 40 tr vnd                  64
9 - 10 triệu                       64
10 - 11 triệu vnđ                  64
2 - 5 triệu vnđ                    64
6,5 tr - 8 tr vnd                  63
11 tr - 14 tr vnd                  62
8 tr - 25 tr vnd                   62
7 - 30 triệu                       62
500 - 1,000 usd                    61
11 - 20 triệu                      60
từ 11 triệu vnđ                    60
40 tr - 50 tr vnd                  58
9 - 13 triệu                       58
13 - 17 triệu vnđ                  58
6 tr - 7 tr vnd                    57
9 - 14 triệu                       57
từ 35 triệu vnđ                    57
15 - 22 triệu vnđ                  57
18 - 22 triệu vnđ                  57
đến 35 triệu vnđ                   57
11 - 21 triệu vnđ                  57
19 - 57 triệu vnđ                  56
20 tr - 50 tr vnd                  55
17 tr - 25 tr vnd                  55
8 - 18 triệu vnđ                   55
14 - 18 triệu                      54
đến 12 triệu vnđ                   54
15 tr - 50 tr vnd                  53
25 - 30 triệu                      53
từ 18 triệu vnđ                    52
đến 30 triệu vnđ                   52
từ 16 triệu vnđ                    52
10 tr - 50 tr vnd                  51
20 - 100 triệu vnđ                 51
10 tr - 17 tr vnd                  50
30 tr - 45 tr vnd                  50
14 - 16 triệu                      49
9 - 30 triệu vnđ                   49
8 - 16 triệu vnđ                   48
trên 7 tr vnd                      47
8 - 9 triệu                        47
35 tr - 45 tr vnd                  46
từ 6 triệu vnđ                     46
40 tr - 60 tr vnd                  45
lên đến 15 tr vnd                  45
20 - 35 triệu                      45
10 - 17 triệu vnđ                  45
từ 25 triệu vnđ                    45
trên 30 tr vnd                     44
lên đến 20 tr vnd                  44
15 - 17 triệu                      44
14 - 20 triệu                      44
4 - 10 triệu vnđ                   44
6 tr - 15 tr vnd                   43
15 - 35 triệu                      43
8 - 13 triệu                       43
1 - 2 triệu vnđ                    43
8 tr - 14 tr vnd                   42
15 - 22 triệu                      41
11 - 13 triệu                      41
20 - 80 triệu vnđ                  41
lên đến 30 tr vnd                  40
18 tr - 23 tr vnd                  40
16 tr - 22 tr vnd                  40
8 - 50 triệu                       40
từ 14 triệu vnđ                    40
16 tr - 25 tr vnd                  39
14 tr - 15 tr vnd                  39
11 - 14 triệu                      39
từ 5 triệu vnđ                     39
đến 2 triệu vnđ                    39
7 - 50 triệu vnđ                   39
từ 13 triệu vnđ                    39
1,000 - 2,000 usd                  38
11 tr - 12 tr vnd                  38
30 tr - 60 tr vnd                  38
trên 13 tr vnd                     38
trên 9 tr vnd                      38
3 tr - 5 tr vnd                    38
35 tr - 40 tr vnd                  38
18 - 22 triệu                      38
13 - 14 triệu vnđ                  38
17 - 20 triệu vnđ                  38
17 tr - 22 tr vnd                  37
22 tr - 30 tr vnd                  37
7,5 tr - 9 tr vnd                  37
13 - 17 triệu                      37
7 - 18 triệu vnđ                   37
1,000 - 1,500 usd                  36
9 - 18 triệu vnđ                   36
15 - 48 triệu vnđ                  36
25 tr - 50 tr vnd                  35
8.5 - 15 triệu                     35
5 - 7 triệu                        35
30 - 35 triệu vnđ                  35
8 - 8 triệu vnđ                    35
9 - 18 triệu                       34
từ 3 triệu vnđ                     34
từ 2 triệu vnđ                     34
11 - 16 triệu vnđ                  34
đến 25 triệu vnđ                   34
2 tr - 3 tr vnd                    33
7 tr - 11 tr vnd                   33
15 tr - 23 tr vnd                  33
20 tr - 22 tr vnd                  32
15 - 35 triệu vnđ                  32
12 - 13 triệu vnđ                  32
14 - 25 triệu vnđ                  32
12 - 50 triệu vnđ                  32
từ 17 triệu vnđ                    32
7,5 tr - 8,5 tr vnd                31
12 - 30 triệu                      31
13 - 16 triệu                      31
7 - 25 triệu vnđ                   31
5 - 8 triệu                        30
từ 4 triệu vnđ                     30
11 - 20 triệu vnđ                  30
35 tr - 50 tr vnd                  29
11 tr - 20 tr vnd                  29
11 tr - 16 tr vnd                  29
6 - 20 triệu                       29
10 - 11 triệu                      29
12 - 13 triệu                      29
11 - 15 triệu                      29
9 - 35 triệu vnđ                   29
6 - 18 triệu vnđ                   29
25 - 45 triệu vnđ                  29
800 - 1,500 usd                    28
6 - 7 triệu                        28
20 - 60 triệu vnđ                  28
5 - 15 triệu vnđ                   28
16 - 18 triệu vnđ                  28
15 - 16 triệu vnđ                  28
10 - 40 triệu vnđ                  28
5 - 12 triệu vnđ                   28
22 tr - 25 tr vnd                  27
7,5 tr - 15 tr vnd                 27
7 - 11 triệu                       27
từ 1 triệu vnđ                     27
4 - 5 triệu vnđ                    27
30 - 45 triệu vnđ                  27
1 - 10 triệu vnđ                   27
8,5 tr - 10 tr vnd                 26
5 tr - 7 tr vnd                    26
10 - 17 triệu                      26
12 - 36 triệu vnđ                  26
7 - 14 triệu vnđ                   26
11 tr - 17 tr vnd                  25
lên đến 25 tr vnd                  25
8,5 tr - 12 tr vnd                 25
10 tr - 40 tr vnd                  25
5 - 9 triệu                        25
13 - 25 triệu                      25
đến 22 triệu vnđ                   25
tới 20 triệu                       25
25 tr - 45 tr vnd                  24
trên 11 tr vnd                     24
50 tr - 70 tr vnd                  24
20 tr - 24 tr vnd                  24
trên 6 tr vnd                      24
17 tr - 30 tr vnd                  24
12 tr - 22 tr vnd                  24
lên đến 12 tr vnd                  24
13 tr - 25 tr vnd                  24
5 tr - 10 tr vnd                   24
6 - 25 triệu vnđ                   24
4 - 6 triệu vnđ                    24
3 - 10 triệu vnđ                   24
20 tr - 23 tr vnd                  23
trên 18 tr vnd                     23
9 tr - 30 tr vnd                   23
13 tr - 19 tr vnd                  23
8 - 14 triệu                       23
20 - 45 triệu                      23
18 - 30 triệu                      23
14 - 17 triệu                      23
7.5 - 10 triệu                     23
6 - 25 triệu                       23
18 - 45 triệu                      23
30 - 40 triệu                      23
3 - 7 triệu vnđ                    23
14 - 15 triệu vnđ                  23
đến 14 triệu vnđ                   23
12 - 40 triệu vnđ                  23
đến 17 triệu vnđ                   23
đến 3 triệu vnđ                    23
15 - 15 triệu vnđ                  23
16 - 30 triệu vnđ                  23
16 - 40 triệu vnđ                  23
lên đến 40 tr vnd                  22
7 tr - 8,5 tr vnd                  22
6,5 tr - 7,5 tr vnd                22
20 tr - 28 tr vnd                  22
22 tr - 27 tr vnd                  22
800 - 1,200 usd                    22
50 tr - 80 tr vnd                  22
6 - 30 triệu                       22
5 - 6 triệu                        22
7 - 11 triệu vnđ                   22
17 - 22 triệu vnđ                  22
50 - 60 triệu vnđ                  22
40 - 50 triệu vnđ                  22
18 tr - 35 tr vnd                  21
7 tr - 7,5 tr vnd                  21
7 tr - 30 tr vnd                   21
2,000 - 4,000 usd                  21
8 - 17 triệu                       21
đến 10 triệu vnđ                   21
40 - 60 triệu vnđ                  21
18 - 35 triệu vnđ                  21
11 - 50 triệu vnđ                  21
12 - 12 triệu vnđ                  21
đến 18 triệu vnđ                   21
25 - 50 triệu vnđ                  21
trên 50 tr vnd                     20
600 - 1,000 usd                    20
15 tr - 16 tr vnd                  20
5 tr - 8 tr vnd                    20
6,5 tr - 7 tr vnd                  20
9 tr - 18 tr vnd                   20
9 - 30 triệu                       20
16 - 22 triệu                      20
30 - 50 triệu                      20
13 - 25 triệu vnđ                  20
3 - 8 triệu vnđ                    20
1 - 4 triệu vnđ                    20
30 - 60 triệu vnđ                  20
14 tr - 25 tr vnd                  19
6 tr - 7,5 tr vnd                  19
16 tr - 19 tr vnd                  19
11 tr - 18 tr vnd                  19
17 tr - 23 tr vnd                  19
15 tr - 19 tr vnd                  19
18 tr - 24 tr vnd                  19
8 tr - 18 tr vnd                   19
25 - 40 triệu                      19
50 - 100 triệu                     19
10 - 32 triệu                      19
12 - 50 triệu                      19
20 - 24 triệu vnđ                  19
20 - 22 triệu vnđ                  19
22 - 33 triệu vnđ                  19
20 - 77 triệu vnđ                  19
9 - 9 triệu vnđ                    19
8 - 35 triệu vnđ                   19
1,500 - 3,000 usd                  18
8,5 tr - 9 tr vnd                  18
450 - 800 usd                      18
8 tr - 16 tr vnd                   18
23 tr - 28 tr vnd                  18
5 - 30 triệu                       18
5 - 10 triệu                       18
25 - 35 triệu                      18
18 - 100 triệu vnđ                 18
trên 15 triệu                      18
14 tr - 22 tr vnd                  17
trên 14 tr vnd                     17
5 tr - 6 tr vnd                    17
14 tr - 19 tr vnd                  17
18 tr - 28 tr vnd                  17
lên đến 35 tr vnd                  17
8 tr - 17 tr vnd                   17
1,500 - 2,000 usd                  17
7 - 7.5 triệu                      17
3 - 5 triệu                        17
14 - 15 triệu                      17
6,3 tr - 9,3 tr vnd                17
9 - 16 triệu vnđ                   17
7 - 7 triệu vnđ                    17
từ 30 triệu vnđ                    17
20 - 20 triệu vnđ                  17
9 - 17 triệu vnđ                   17

In [70]:
print("Number of unique salary values:", clean_df["salary"].nunique())

Number of unique salary values: 2069

In [71]:
clean_df["salary_clean"] = (
    clean_df["salary"]
    .astype("string")
    .str.lower()
    .str.strip()
)|

SyntaxError: invalid syntax (1853645594.py, line 6)

In [72]:
clean_df["salary_clean"] = (
    clean_df["salary"]
    .astype("string")
    .str.lower()
    .str.strip()
)

In [73]:
clean_df["salary_clean"] = (
    clean_df["salary_clean"]
    .str.replace("vnđ", "vnd", regex=False)
    .str.replace("triệu", "tr", regex=False)
)

In [74]:
import re
import numpy as np

In [75]:
clean_df[
    clean_df["salary_min_vnd"].isna() &
    clean_df["salary_max_vnd"].isna()
]["salary"].value_counts().head(100)

KeyError: 'salary_min_vnd'

In [76]:

test_values = [
    "10 tr - 15 tr vnd",
    "2,5 tr - 15 tr vnd",
    "800 - 1,500 usd",
]

for value in test_values:
    numbers = re.findall(r"\d+(?:,\d+)?", value)
    print(value, "→", numbers)

10 tr - 15 tr vnd → ['10', '15']
2,5 tr - 15 tr vnd → ['2,5', '15']
800 - 1,500 usd → ['800', '1,500']

In [77]:
number = number.replace(",", ".")

NameError: name 'number' is not defined

In [78]:
value = "2,5"

number = float(value.replace(",", "."))

print(number)

2.5

In [79]:
def parse_number(value):
    value = value.strip()

    if "," in value and "." not in value:
        parts = value.split(",")

        # 2,5 → decimal
        if len(parts) == 2 and len(parts[1]) <= 2:
            return float(value.replace(",", "."))

        # 1,500 → thousands
        return float(value.replace(",", ""))

    return float(value.replace(",", ""))

In [80]:
print(parse_number("2,5"))
print(parse_number("1,500"))
print(parse_number("10"))

2.5
1500.0
10.0

In [81]:
numbers = re.findall(r"\d+(?:,\d+)?", salary)

numbers = [parse_number(n) for n in numbers]

NameError: name 'salary' is not defined

In [82]:
salary = "2,5 tr - 15 tr vnd"

numbers = re.findall(r"\d+(?:,\d+)?", salary)
numbers = [parse_number(n) for n in numbers]

print(numbers)

[2.5, 15.0]

In [83]:
def extract_numbers(salary):
    numbers = re.findall(r"\d+(?:,\d+)?", salary)
    return [parse_number(n) for n in numbers]

In [84]:
print(extract_numbers("10 tr - 15 tr vnd"))
print(extract_numbers("2,5 tr - 15 tr vnd"))
print(extract_numbers("800 - 1,500 usd"))

[10.0, 15.0]
[2.5, 15.0]
[800.0, 1500.0]

In [85]:
clean_df["salary_numbers"] = clean_df["salary"].apply(extract_numbers)

In [86]:
print(
    clean_df[["salary", "salary_numbers"]]
    .head(20)
    .to_string(index=False)
)

            salary  salary_numbers
 15 tr - 50 tr vnd    [15.0, 50.0]
  8 tr - 11 tr vnd     [8.0, 11.0]
 20 tr - 30 tr vnd    [20.0, 30.0]
   800 - 1,500 usd [800.0, 1500.0]
 10 tr - 50 tr vnd    [10.0, 50.0]
 15 tr - 40 tr vnd    [15.0, 40.0]
 15 tr - 50 tr vnd    [15.0, 50.0]
 10 tr - 18 tr vnd    [10.0, 18.0]
 15 tr - 20 tr vnd    [15.0, 20.0]
 17 tr - 22 tr vnd    [17.0, 22.0]
9,5 tr - 12 tr vnd     [9.5, 12.0]
 14 tr - 25 tr vnd    [14.0, 25.0]
 15 tr - 18 tr vnd    [15.0, 18.0]
  8 tr - 10 tr vnd     [8.0, 10.0]
 12 tr - 15 tr vnd    [12.0, 15.0]
 25 tr - 30 tr vnd    [25.0, 30.0]
 10 tr - 15 tr vnd    [10.0, 15.0]
 10 tr - 25 tr vnd    [10.0, 25.0]
8,5 tr - 10 tr vnd     [8.5, 10.0]
 10 tr - 15 tr vnd    [10.0, 15.0]

In [87]:
def get_currency(salary):
    salary = salary.lower()

    if "usd" in salary:
        return "USD"
    elif "vnd" in salary or "vnđ" in salary or "triệu" in salary or "tr" in salary:
        return "VND"
    else:
        return "UNKNOWN"

In [88]:
clean_df["salary_currency"] = clean_df["salary"].apply(get_currency)

In [89]:
print(
    clean_df[["salary", "salary_currency"]]
    .head(20)
    .to_string(index=False)
)

            salary salary_currency
 15 tr - 50 tr vnd             VND
  8 tr - 11 tr vnd             VND
 20 tr - 30 tr vnd             VND
   800 - 1,500 usd             USD
 10 tr - 50 tr vnd             VND
 15 tr - 40 tr vnd             VND
 15 tr - 50 tr vnd             VND
 10 tr - 18 tr vnd             VND
 15 tr - 20 tr vnd             VND
 17 tr - 22 tr vnd             VND
9,5 tr - 12 tr vnd             VND
 14 tr - 25 tr vnd             VND
 15 tr - 18 tr vnd             VND
  8 tr - 10 tr vnd             VND
 12 tr - 15 tr vnd             VND
 25 tr - 30 tr vnd             VND
 10 tr - 15 tr vnd             VND
 10 tr - 25 tr vnd             VND
8,5 tr - 10 tr vnd             VND
 10 tr - 15 tr vnd             VND

In [90]:
print(clean_df["salary_currency"].value_counts())

salary_currency
VND    84757
USD      713
Name: count, dtype: int64

In [91]:
USD_TO_VND = 25000

In [92]:
def convert_salary(numbers, currency):
    if currency == "VND":
        return [number * 1_000_000 for number in numbers]

    elif currency == "USD":
        return [number * USD_TO_VND for number in numbers]

    return []

In [93]:
clean_df["salary_vnd"] = clean_df.apply(
    lambda row: convert_salary(
        row["salary_numbers"],
        row["salary_currency"]
    ),
    axis=1
)

In [94]:
print(
    clean_df[["salary", "salary_currency", "salary_numbers", "salary_vnd"]]
    .head(20)
    .to_string(index=False)
)

            salary salary_currency  salary_numbers               salary_vnd
 15 tr - 50 tr vnd             VND    [15.0, 50.0] [15000000.0, 50000000.0]
  8 tr - 11 tr vnd             VND     [8.0, 11.0]  [8000000.0, 11000000.0]
 20 tr - 30 tr vnd             VND    [20.0, 30.0] [20000000.0, 30000000.0]
   800 - 1,500 usd             USD [800.0, 1500.0] [20000000.0, 37500000.0]
 10 tr - 50 tr vnd             VND    [10.0, 50.0] [10000000.0, 50000000.0]
 15 tr - 40 tr vnd             VND    [15.0, 40.0] [15000000.0, 40000000.0]
 15 tr - 50 tr vnd             VND    [15.0, 50.0] [15000000.0, 50000000.0]
 10 tr - 18 tr vnd             VND    [10.0, 18.0] [10000000.0, 18000000.0]
 15 tr - 20 tr vnd             VND    [15.0, 20.0] [15000000.0, 20000000.0]
 17 tr - 22 tr vnd             VND    [17.0, 22.0] [17000000.0, 22000000.0]
9,5 tr - 12 tr vnd             VND     [9.5, 12.0]  [9500000.0, 12000000.0]
 14 tr - 25 tr vnd             VND    [14.0, 25.0] [14000000.0, 25000000.0]
 15 tr - 18 tr vnd             VND    [15.0, 18.0] [15000000.0, 18000000.0]
  8 tr - 10 tr vnd             VND     [8.0, 10.0]  [8000000.0, 10000000.0]
 12 tr - 15 tr vnd             VND    [12.0, 15.0] [12000000.0, 15000000.0]
 25 tr - 30 tr vnd             VND    [25.0, 30.0] [25000000.0, 30000000.0]
 10 tr - 15 tr vnd             VND    [10.0, 15.0] [10000000.0, 15000000.0]
 10 tr - 25 tr vnd             VND    [10.0, 25.0] [10000000.0, 25000000.0]
8,5 tr - 10 tr vnd             VND     [8.5, 10.0]  [8500000.0, 10000000.0]
 10 tr - 15 tr vnd             VND    [10.0, 15.0] [10000000.0, 15000000.0]

In [95]:
clean_df["salary_min_vnd"] = clean_df["salary_vnd"].apply(
    lambda x: x[0] if len(x) >= 1 else None
)

clean_df["salary_max_vnd"] = clean_df["salary_vnd"].apply(
    lambda x: x[1] if len(x) >= 2 else None
)

In [96]:
print(
    clean_df[
        ["salary", "salary_currency", "salary_min_vnd", "salary_max_vnd"]
    ]
    .head(20)
    .to_string(index=False)
)

            salary salary_currency  salary_min_vnd  salary_max_vnd
 15 tr - 50 tr vnd             VND      15000000.0      50000000.0
  8 tr - 11 tr vnd             VND       8000000.0      11000000.0
 20 tr - 30 tr vnd             VND      20000000.0      30000000.0
   800 - 1,500 usd             USD      20000000.0      37500000.0
 10 tr - 50 tr vnd             VND      10000000.0      50000000.0
 15 tr - 40 tr vnd             VND      15000000.0      40000000.0
 15 tr - 50 tr vnd             VND      15000000.0      50000000.0
 10 tr - 18 tr vnd             VND      10000000.0      18000000.0
 15 tr - 20 tr vnd             VND      15000000.0      20000000.0
 17 tr - 22 tr vnd             VND      17000000.0      22000000.0
9,5 tr - 12 tr vnd             VND       9500000.0      12000000.0
 14 tr - 25 tr vnd             VND      14000000.0      25000000.0
 15 tr - 18 tr vnd             VND      15000000.0      18000000.0
  8 tr - 10 tr vnd             VND       8000000.0      10000000.0
 12 tr - 15 tr vnd             VND      12000000.0      15000000.0
 25 tr - 30 tr vnd             VND      25000000.0      30000000.0
 10 tr - 15 tr vnd             VND      10000000.0      15000000.0
 10 tr - 25 tr vnd             VND      10000000.0      25000000.0
8,5 tr - 10 tr vnd             VND       8500000.0      10000000.0
 10 tr - 15 tr vnd             VND      10000000.0      15000000.0

In [97]:
salary_length = clean_df["salary_numbers"].apply(len)

print(
    clean_df.loc[
        salary_length != 2,
        ["salary", "salary_numbers"]
    ]
    .value_counts()
    .to_string()
)

TypeError: unhashable type: 'list'

In [98]:
salary_length = clean_df["salary_numbers"].apply(len)

print(
    clean_df.loc[
        salary_length != 2,
        ["salary", "salary_numbers"]
    ]
    .value_counts()
    .to_string()
)

TypeError: unhashable type: 'list'

In [99]:
salary_length = clean_df["salary_numbers"].apply(len)

unusual_salary = clean_df.loc[
    salary_length != 2,
    ["salary", "salary_numbers"]
]

print(unusual_salary.to_string(index=False))

                 salary         salary_numbers
         trên 12 tr vnd                 [12.0]
      lên đến 30 tr vnd                 [30.0]
      lên đến 40 tr vnd                 [40.0]
         trên 15 tr vnd                 [15.0]
     lên đến 8,7 tr vnd                  [8.7]
         trên 4,000 usd               [4000.0]
         trên 50 tr vnd                 [50.0]
          trên 2 tr vnd                  [2.0]
         trên 15 tr vnd                 [15.0]
      lên đến 30 tr vnd                 [30.0]
         trên 14 tr vnd                 [14.0]
         trên 15 tr vnd                 [15.0]
          trên 8 tr vnd                  [8.0]
         trên 50 tr vnd                 [50.0]
        trên 3,5 tr vnd                  [3.5]
         trên 13 tr vnd                 [13.0]
         trên 20 tr vnd                 [20.0]
      lên đến 25 tr vnd                 [25.0]
         trên 15 tr vnd                 [15.0]
         trên 10 tr vnd                 [10.0]
      lên đến 23 tr vnd                 [23.0]
      lên đến 25 tr vnd                 [25.0]
         trên 10 tr vnd                 [10.0]
         trên 10 tr vnd                 [10.0]
         trên 12 tr vnd                 [12.0]
        trên 4,2 tr vnd                  [4.2]
         trên 15 tr vnd                 [15.0]
      lên đến 16 tr vnd                 [16.0]
         trên 20 tr vnd                 [20.0]
         trên 30 tr vnd                 [30.0]
         trên 10 tr vnd                 [10.0]
      lên đến 15 tr vnd                 [15.0]
         trên 12 tr vnd                 [12.0]
         trên 20 tr vnd                 [20.0]
       lên đến 3 tr vnd                  [3.0]
         trên 20 tr vnd                 [20.0]
         trên 12 tr vnd                 [12.0]
          trên 7 tr vnd                  [7.0]
         trên 20 tr vnd                 [20.0]
         trên 10 tr vnd                 [10.0]
          trên 9 tr vnd                  [9.0]
         trên 20 tr vnd                 [20.0]
         trên 20 tr vnd                 [20.0]
      lên đến 23 tr vnd                 [23.0]
     lên đến 8,7 tr vnd                  [8.7]
          trên 5 tr vnd                  [5.0]
         trên 11 tr vnd                 [11.0]
         trên 15 tr vnd                 [15.0]
        trên 5,5 tr vnd                  [5.5]
         trên 15 tr vnd                 [15.0]
          trên 9 tr vnd                  [9.0]
         trên 20 tr vnd                 [20.0]
         trên 13 tr vnd                 [13.0]
         trên 15 tr vnd                 [15.0]
      lên đến 30 tr vnd                 [30.0]
          trên 9 tr vnd                  [9.0]
         trên 13 tr vnd                 [13.0]
          trên 7 tr vnd                  [7.0]
          trên 8 tr vnd                  [8.0]
         trên 12 tr vnd                 [12.0]
         trên 15 tr vnd                 [15.0]
         trên 25 tr vnd                 [25.0]
          trên 6 tr vnd                  [6.0]
         trên 13 tr vnd                 [13.0]
         trên 11 tr vnd                 [11.0]
         trên 15 tr vnd                 [15.0]
        trên 9,3 tr vnd                  [9.3]
      lên đến 30 tr vnd                 [30.0]
      lên đến 50 tr vnd                 [50.0]
         trên 15 tr vnd                 [15.0]
      lên đến 15 tr vnd                 [15.0]
      lên đến 20 tr vnd                 [20.0]
         trên 12 tr vnd                 [12.0]
         trên 18 tr vnd                 [18.0]
         trên 15 tr vnd                 [15.0]
         trên 15 tr vnd                 [15.0]
          trên 8 tr vnd                  [8.0]
         trên 50 tr vnd                 [50.0]
         trên 18 tr vnd                 [18.0]
      lên đến 50 tr vnd                 [50.0]
      lên đến 1,800 usd               [1800.0]
          trên 8 tr vnd                  [8.0]
         trên 30 tr vnd                 [30.0]
         trên 12 tr vnd                 [12.0]
        trên 3,5 tr vnd                  [3.5]
         trên 15 tr vnd                 [15.0]
         trên 20 tr vnd                 [20.0]
         trên 1,000 usd               [1000.0]
          trên 8 tr vnd                  [8.0]
         trên 10 tr vnd                 [10.0]
         trên 25 tr vnd                 [25.0]
         trên 25 tr vnd                 [25.0]
         trên 16 tr vnd                 [16.0]
         trên 10 tr vnd                 [10.0]
          trên 5 tr vnd                  [5.0]
         trên 30 tr vnd                 [30.0]
         trên 15 tr vnd                 [15.0]
      lên đến 40 tr vnd                 [40.0]
          trên 8 tr vnd                  [8.0]
      lên đến 15 tr vnd                 [15.0]
         trên 20 tr vnd                 [20.0]
         trên 25 tr vnd                 [25.0]
         trên 12 tr vnd                 [12.0]
         trên 12 tr vnd                 [12.0]
      lên đến 50 tr vnd                 [50.0]
         trên 15 tr vnd                 [15.0]
         trên 20 tr vnd                 [20.0]
      lên đến 18 tr vnd                 [18.0]
         trên 12 tr vnd                 [12.0]
         trên 20 tr vnd                 [20.0]
         trên 30 tr vnd                 [30.0]
          trên 8 tr vnd                  [8.0]
          trên 9 tr vnd                  [9.0]
       lên đến 2 tr vnd                  [2.0]
      lên đến 23 tr vnd                 [23.0]
          trên 8 tr vnd                  [8.0]
         trên 10 tr vnd                 [10.0]
         trên 25 tr vnd                 [25.0]
         trên 15 tr vnd                 [15.0]
      lên đến 20 tr vnd                 [20.0]
         trên 13 tr vnd                 [13.0]
      lên đến 1,500 usd               [1500.0]
         trên 12 tr vnd                 [12.0]
      lên đến 22 tr vnd                 [22.0]
          trên 5 tr vnd                  [5.0]
         trên 50 tr vnd                 [50.0]
         trên 10 tr vnd                 [10.0]
      lên đến 35 tr vnd                 [35.0]
         trên 20 tr vnd                 [20.0]
         trên 15 tr vnd                 [15.0]
          trên 5 tr vnd                  [5.0]
      lên đến 25 tr vnd                 [25.0]
         trên 15 tr vnd                 [15.0]
         trên 12 tr vnd                 [12.0]
         trên 10 tr vnd                 [10.0]
         trên 20 tr vnd                 [20.0]
       lên đến 6 tr vnd                  [6.0]
       lên đến 2 tr vnd                  [2.0]
         trên 10 tr vnd                 [10.0]
          trên 8 tr vnd                  [8.0]
      lên đến 14 tr vnd                 [14.0]
          trên 8 tr vnd                  [8.0]
      lên đến 12 tr vnd                 [12.0]
      lên đến 17 tr vnd                 [17.0]
         trên 15 tr vnd                 [15.0]
      lên đến 15 tr vnd                 [15.0]
      lên đến 20 tr vnd                 [20.0]
         trên 20 tr vnd                 [20.0]
      lên đến 65 tr vnd                 [65.0]
      lên đến 10 tr vnd                 [10.0]
         trên 12 tr vnd                 [12.0]
      lên đến 30 tr vnd                 [30.0]
         trên 20 tr vnd                 [20.0]
         trên 15 tr vnd                 [15.0]
      lên đến 14 tr vnd                 [14.0]
         trên 13 tr vnd                 [13.0]
      lên đến 40 tr vnd                 [40.0]
      lên đến 25 tr vnd                 [25.0]
      lên đến 35 tr vnd                 [35.0]
          trên 8 tr vnd                  [8.0]
         trên 10 tr vnd                 [10.0]
          trên 8 tr vnd                  [8.0]
      lên đến 12 tr vnd                 [12.0]
      lên đến 40 tr vnd                 [40.0]
         trên 25 tr vnd                 [25.0]
         trên 30 tr vnd                 [30.0]
       lên đến 9 tr vnd                  [9.0]
         trên 12 tr vnd                 [12.0]
         trên 15 tr vnd                 [15.0]
      lên đến 12 tr vnd                 [12.0]
         trên 10 tr vnd                 [10.0]
         trên 13 tr vnd                 [13.0]
          trên 7 tr vnd                  [7.0]
          trên 9 tr vnd                  [9.0]
         trên 10 tr vnd                 [10.0]
         trên 10 tr vnd                 [10.0]
          trên 8 tr vnd                  [8.0]
      lên đến 40 tr vnd                 [40.0]
          trên 9 tr vnd                  [9.0]
         trên 12 tr vnd                 [12.0]
          trên 7 tr vnd                  [7.0]
         trên 20 tr vnd                 [20.0]
         trên 30 tr vnd                 [30.0]
      lên đến 10 tr vnd                 [10.0]
          trên 9 tr vnd                  [9.0]
         trên 12 tr vnd                 [12.0]
         trên 13 tr vnd                 [13.0]
      lên đến 16 tr vnd                 [16.0]
          trên 6 tr vnd                  [6.0]
      lên đến 23 tr vnd                 [23.0]
         trên 15 tr vnd                 [15.0]
      lên đến 14 tr vnd                 [14.0]
          trên 8 tr vnd                  [8.0]
         trên 20 tr vnd                 [20.0]
          trên 9 tr vnd                  [9.0]
         trên 15 tr vnd                 [15.0]
         trên 10 tr vnd                 [10.0]
      lên đến 40 tr vnd                 [40.0]
          trên 9 tr vnd                  [9.0]
         trên 10 tr vnd                 [10.0]
          trên 9 tr vnd                  [9.0]
         trên 12 tr vnd                 [12.0]
         trên 12 tr vnd                 [12.0]
         trên 25 tr vnd                 [25.0]
         trên 15 tr vnd                 [15.0]
     lên đến 3,6 tr vnd                  [3.6]
      lên đến 23 tr vnd                 [23.0]
         trên 17 tr vnd                 [17.0]
      lên đến 12 tr vnd                 [12.0]
      lên đến 30 tr vnd                 [30.0]
         trên 15 tr vnd                 [15.0]
         trên 15 tr vnd                 [15.0]
      lên đến 40 tr vnd                 [40.0]
         trên 12 tr vnd                 [12.0]
         trên 25 tr vnd                 [25.0]
      lên đến 30 tr vnd                 [30.0]
         trên 13 tr vnd                 [13.0]
          trên 8 tr vnd                  [8.0]
         trên 15 tr vnd                 [15.0]
         trên 13 tr vnd                 [13.0]
         trên 2,500 usd               [2500.0]
         trên 40 tr vnd                 [40.0]
          trên 9 tr vnd                  [9.0]
      lên đến 20 tr vnd                 [20.0]
         trên 50 tr vnd                 [50.0]
         trên 20 tr vnd                 [20.0]
         trên 25 tr vnd                 [25.0]
      lên đến 13 tr vnd                 [13.0]
         trên 17 tr vnd                 [17.0]
          trên 7 tr vnd                  [7.0]
         trên 20 tr vnd                 [20.0]
         trên 10 tr vnd                 [10.0]
         trên 30 tr vnd                 [30.0]
      lên đến 30 tr vnd                 [30.0]
         trên 20 tr vnd                 [20.0]
         trên 20 tr vnd                 [20.0]
         trên 10 tr vnd                 [10.0]
         trên 15 tr vnd                 [15.0]
         trên 15 tr vnd                 [15.0]
         trên 19 tr vnd                 [19.0]
         trên 12 tr vnd                 [12.0]
      lên đến 25 tr vnd                 [25.0]
         trên 13 tr vnd                 [13.0]
         trên 10 tr vnd                 [10.0]
         trên 35 tr vnd                 [35.0]
         trên 11 tr vnd                 [11.0]
         trên 13 tr vnd                 [13.0]
         trên 30 tr vnd                 [30.0]
         trên 16 tr vnd                 [16.0]
         trên 18 tr vnd                 [18.0]
         trên 10 tr vnd                 [10.0]
         trên 11 tr vnd                 [11.0]
         trên 12 tr vnd                 [12.0]
      lên đến 25 tr vnd                 [25.0]
      lên đến 15 tr vnd                 [15.0]
         trên 40 tr vnd                 [40.0]
       trên 730,000 vnd             [730000.0]
         trên 15 tr vnd                 [15.0]
         trên 10 tr vnd                 [10.0]
         trên 16 tr vnd                 [16.0]
      lên đến 2,300 usd               [2300.0]
          trên 9 tr vnd                  [9.0]
      lên đến 22 tr vnd                 [22.0]
          trên 7 tr vnd                  [7.0]
          trên 6 tr vnd                  [6.0]
      lên đến 25 tr vnd                 [25.0]
      lên đến 10 tr vnd                 [10.0]
      lên đến 12 tr vnd                 [12.0]
      lên đến 12 tr vnd                 [12.0]
         trên 12 tr vnd                 [12.0]
         trên 12 tr vnd                 [12.0]
          trên 8 tr vnd                  [8.0]
         trên 40 tr vnd                 [40.0]
      lên đến 30 tr vnd                 [30.0]
      lên đến 15 tr vnd                 [15.0]
         trên 60 tr vnd                 [60.0]
         trên 25 tr vnd                 [25.0]
         trên 10 tr vnd                 [10.0]
         trên 13 tr vnd                 [13.0]
      lên đến 26 tr vnd                 [26.0]
         trên 15 tr vnd                 [15.0]
         trên 15 tr vnd                 [15.0]
          trên 3 tr vnd                  [3.0]
          trên 7 tr vnd                  [7.0]
      lên đến 30 tr vnd                 [30.0]
         trên 12 tr vnd                 [12.0]
         trên 10 tr vnd                 [10.0]
      lên đến 35 tr vnd                 [35.0]
         trên 12 tr vnd                 [12.0]
      lên đến 23 tr vnd                 [23.0]
         trên 12 tr vnd                 [12.0]
         trên 12 tr vnd                 [12.0]
          trên 8 tr vnd                  [8.0]
      lên đến 25 tr vnd                 [25.0]
      lên đến 25 tr vnd                 [25.0]
         trên 35 tr vnd                 [35.0]
         trên 13 tr vnd                 [13.0]
         trên 12 tr vnd                 [12.0]
         trên 25 tr vnd                 [25.0]
         trên 12 tr vnd                 [12.0]
          trên 8 tr vnd                  [8.0]
         trên 20 tr vnd                 [20.0]
          trên 8 tr vnd                  [8.0]
         trên 25 tr vnd                 [25.0]
         trên 13 tr vnd                 [13.0]
      lên đến 35 tr vnd                 [35.0]
         trên 13 tr vnd                 [13.0]
          trên 8 tr vnd                  [8.0]
          trên 9 tr vnd                  [9.0]
         trên 10 tr vnd                 [10.0]
         trên 15 tr vnd                 [15.0]
         trên 10 tr vnd                 [10.0]
       lên đến 1 tr vnd                  [1.0]
          trên 7 tr vnd                  [7.0]
          trên 8 tr vnd                  [8.0]
      lên đến 12 tr vnd                 [12.0]
         trên 1,200 usd               [1200.0]
          trên 9 tr vnd                  [9.0]
         trên 18 tr vnd                 [18.0]
      lên đến 30 tr vnd                 [30.0]
          trên 5 tr vnd                  [5.0]
         trên 13 tr vnd                 [13.0]
         trên 15 tr vnd                 [15.0]
      lên đến 45 tr vnd                 [45.0]
         trên 10 tr vnd                 [10.0]
          trên 7 tr vnd                  [7.0]
         trên 60 tr vnd                 [60.0]
         trên 30 tr vnd                 [30.0]
         trên 25 tr vnd                 [25.0]
         trên 15 tr vnd                 [15.0]
         trên 50 tr vnd                 [50.0]
         trên 10 tr vnd                 [10.0]
          trên 5 tr vnd                  [5.0]
      lên đến 17 tr vnd                 [17.0]
         trên 11 tr vnd                 [11.0]
        trên 5,5 tr vnd                  [5.5]
         trên 20 tr vnd                 [20.0]
         trên 12 tr vnd                 [12.0]
      lên đến 30 tr vnd                 [30.0]
          trên 7 tr vnd                  [7.0]
         trên 12 tr vnd                 [12.0]
          trên 8 tr vnd                  [8.0]
          trên 7 tr vnd                  [7.0]
         trên 2,000 usd               [2000.0]
          trên 5 tr vnd                  [5.0]
      lên đến 12 tr vnd                 [12.0]
          trên 6 tr vnd                  [6.0]
      lên đến 14 tr vnd                 [14.0]
          trên 5 tr vnd                  [5.0]
      lên đến 12 tr vnd                 [12.0]
         trên 15 tr vnd                 [15.0]
      lên đến 40 tr vnd                 [40.0]
     lên đến 1,7 tr vnd                  [1.7]
         trên 25 tr vnd                 [25.0]
         trên 20 tr vnd                 [20.0]
         trên 25 tr vnd                 [25.0]
      lên đến 25 tr vnd                 [25.0]
         trên 10 tr vnd                 [10.0]
         trên 10 tr vnd                 [10.0]
         trên 12 tr vnd                 [12.0]
      lên đến 20 tr vnd                 [20.0]
         trên 20 tr vnd                 [20.0]
      lên đến 20 tr vnd                 [20.0]
      lên đến 16 tr vnd                 [16.0]
         trên 14 tr vnd                 [14.0]
      lên đến 15 tr vnd                 [15.0]
         trên 15 tr vnd                 [15.0]
         trên 20 tr vnd                 [20.0]
         trên 19 tr vnd                 [19.0]
      lên đến 50 tr vnd                 [50.0]
          trên 8 tr vnd                  [8.0]
          trên 8 tr vnd                  [8.0]
         trên 10 tr vnd                 [10.0]
      lên đến 15 tr vnd                 [15.0]
      lên đến 30 tr vnd                 [30.0]
      lên đến 16 tr vnd                 [16.0]
         trên 10 tr vnd                 [10.0]
         trên 15 tr vnd                 [15.0]
      lên đến 24 tr vnd                 [24.0]
         trên 2,000 usd               [2000.0]
          trên 7 tr vnd                  [7.0]
         trên 30 tr vnd                 [30.0]
         trên 20 tr vnd                 [20.0]
         trên 10 tr vnd                 [10.0]
          trên 9 tr vnd                  [9.0]
      lên đến 25 tr vnd                 [25.0]
         trên 25 tr vnd                 [25.0]
         trên 12 tr vnd                 [12.0]
         trên 25 tr vnd                 [25.0]
         trên 15 tr vnd                 [15.0]
         trên 20 tr vnd                 [20.0]
          trên 3 tr vnd                  [3.0]
         trên 20 tr vnd                 [20.0]
      lên đến 15 tr vnd                 [15.0]
      lên đến 3,500 usd               [3500.0]
         trên 25 tr vnd                 [25.0]
         trên 20 tr vnd                 [20.0]
         trên 25 tr vnd                 [25.0]
         trên 25 tr vnd                 [25.0]
          trên 8 tr vnd                  [8.0]
         trên 20 tr vnd                 [20.0]
      lên đến 30 tr vnd                 [30.0]
          trên 5 tr vnd                  [5.0]
         trên 12 tr vnd                 [12.0]
         trên 35 tr vnd                 [35.0]
         trên 12 tr vnd                 [12.0]
          trên 7 tr vnd                  [7.0]
          trên 7 tr vnd                  [7.0]
         trên 10 tr vnd                 [10.0]
      lên đến 15 tr vnd                 [15.0]
      lên đến 19 tr vnd                 [19.0]
         trên 10 tr vnd                 [10.0]
         trên 10 tr vnd                 [10.0]
         trên 11 tr vnd                 [11.0]
      lên đến 20 tr vnd                 [20.0]
          trên 8 tr vnd                  [8.0]
       lên đến 8 tr vnd                  [8.0]
         trên 13 tr vnd                 [13.0]
         trên 15 tr vnd                 [15.0]
         trên 13 tr vnd                 [13.0]
      lên đến 25 tr vnd                 [25.0]
          trên 7 tr vnd                  [7.0]
      lên đến 15 tr vnd                 [15.0]
         trên 12 tr vnd                 [12.0]

In [100]:
import re

def extract_numbers(salary):
    numbers = re.findall(r"\d+(?:[.,]\d+)?", salary)
    return [parse_number(n) for n in numbers]

In [101]:
test_salaries = [
    "10 tr - 15 tr vnd",
    "2,5 tr - 15 tr vnd",
    "1.5 triệu - 4 triệu vnđ",
    "9 - 10.8 triệu",
    "8.5 - 15 triệu",
    "6.5 - 9 triệu",
    "0.0 - 0.0 triệu",
    "800 - 1,500 usd",
    "tới 1,800 usd",
    "trên 8,5 tr vnd"
]

for salary in test_salaries:
    print(salary, "→", extract_numbers(salary))

10 tr - 15 tr vnd → [10.0, 15.0]
2,5 tr - 15 tr vnd → [2.5, 15.0]
1.5 triệu - 4 triệu vnđ → [1.5, 4.0]
9 - 10.8 triệu → [9.0, 10.8]
8.5 - 15 triệu → [8.5, 15.0]
6.5 - 9 triệu → [6.5, 9.0]
0.0 - 0.0 triệu → [0.0, 0.0]
800 - 1,500 usd → [800.0, 1500.0]
tới 1,800 usd → [1800.0]
trên 8,5 tr vnd → [8.5]

In [102]:
clean_df["salary_numbers"] = clean_df["salary"].apply(extract_numbers)

In [103]:
check_values = [
    "1.5 triệu - 4 triệu vnđ",
    "9 - 10.8 triệu",
    "8.5 - 15 triệu",
    "6.5 - 9 triệu",
    "0.0 - 0.0 triệu"
]

print(
    clean_df[
        clean_df["salary"].isin(check_values)
    ][["salary", "salary_numbers"]]
    .to_string(index=False)
)

                 salary salary_numbers
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
          6.5 - 9 triệu     [6.5, 9.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
          6.5 - 9 triệu     [6.5, 9.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
          6.5 - 9 triệu     [6.5, 9.0]
         8.5 - 15 triệu    [8.5, 15.0]
          6.5 - 9 triệu     [6.5, 9.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
         8.5 - 15 triệu    [8.5, 15.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
1.5 triệu - 4 triệu vnđ     [1.5, 4.0]
         9 - 10.8 triệu    [9.0, 10.8]
         8.5 - 15 triệu    [8.5, 15.0]
          6.5 - 9 triệu     [6.5, 9.0]
        0.0 - 0.0 triệu     [0.0, 0.0]
         9 - 10.8 triệu    [9.0, 10.8]
         8.5 - 15 triệu    [8.5, 15.0]
          6.5 - 9 triệu     [6.5, 9.0]
        0.0 - 0.0 triệu     [0.0, 0.0]
          6.5 - 9 triệu     [6.5, 9.0]
        0.0 - 0.0 triệu     [0.0, 0.0]
        0.0 - 0.0 triệu     [0.0, 0.0]

In [104]:
salary_length = clean_df["salary_numbers"].apply(len)

print(
    salary_length.value_counts().sort_index()
)

salary_numbers
1     5616
2    79854
Name: count, dtype: int64

In [105]:
unusual_salary = clean_df.loc[
    ~salary_length.isin([1, 2]),
    ["salary", "salary_numbers"]
]

print(
    unusual_salary["salary"]
    .value_counts()
    .to_string()
)

Series([], )

In [106]:
def convert_salary(numbers, currency):
    if currency == "VND":
        return [number * 1_000_000 for number in numbers]

    elif currency == "USD":
        return [number * USD_TO_VND for number in numbers]

    return []


clean_df["salary_vnd"] = clean_df.apply(
    lambda row: convert_salary(
        row["salary_numbers"],
        row["salary_currency"]
    ),
    axis=1
)

In [107]:
print(
    clean_df[
        ["salary", "salary_currency", "salary_numbers", "salary_vnd"]
    ]
    .head(20)
    .to_string(index=False)
)

            salary salary_currency  salary_numbers               salary_vnd
 15 tr - 50 tr vnd             VND    [15.0, 50.0] [15000000.0, 50000000.0]
  8 tr - 11 tr vnd             VND     [8.0, 11.0]  [8000000.0, 11000000.0]
 20 tr - 30 tr vnd             VND    [20.0, 30.0] [20000000.0, 30000000.0]
   800 - 1,500 usd             USD [800.0, 1500.0] [20000000.0, 37500000.0]
 10 tr - 50 tr vnd             VND    [10.0, 50.0] [10000000.0, 50000000.0]
 15 tr - 40 tr vnd             VND    [15.0, 40.0] [15000000.0, 40000000.0]
 15 tr - 50 tr vnd             VND    [15.0, 50.0] [15000000.0, 50000000.0]
 10 tr - 18 tr vnd             VND    [10.0, 18.0] [10000000.0, 18000000.0]
 15 tr - 20 tr vnd             VND    [15.0, 20.0] [15000000.0, 20000000.0]
 17 tr - 22 tr vnd             VND    [17.0, 22.0] [17000000.0, 22000000.0]
9,5 tr - 12 tr vnd             VND     [9.5, 12.0]  [9500000.0, 12000000.0]
 14 tr - 25 tr vnd             VND    [14.0, 25.0] [14000000.0, 25000000.0]
 15 tr - 18 tr vnd             VND    [15.0, 18.0] [15000000.0, 18000000.0]
  8 tr - 10 tr vnd             VND     [8.0, 10.0]  [8000000.0, 10000000.0]
 12 tr - 15 tr vnd             VND    [12.0, 15.0] [12000000.0, 15000000.0]
 25 tr - 30 tr vnd             VND    [25.0, 30.0] [25000000.0, 30000000.0]
 10 tr - 15 tr vnd             VND    [10.0, 15.0] [10000000.0, 15000000.0]
 10 tr - 25 tr vnd             VND    [10.0, 25.0] [10000000.0, 25000000.0]
8,5 tr - 10 tr vnd             VND     [8.5, 10.0]  [8500000.0, 10000000.0]
 10 tr - 15 tr vnd             VND    [10.0, 15.0] [10000000.0, 15000000.0]

In [108]:
clean_df["salary_min_vnd"] = clean_df["salary_vnd"].apply(
    lambda x: x[0]
)

clean_df["salary_max_vnd"] = clean_df["salary_vnd"].apply(
    lambda x: x[-1] if len(x) == 2 else x[0]
)

In [109]:
one_number_salary = clean_df[
    clean_df["salary_numbers"].apply(len) == 1
]

print(
    one_number_salary["salary"]
    .value_counts()
    .to_string()
)

salary
đến 20 triệu vnđ       1168
từ 10 triệu vnđ         343
từ 8 triệu vnđ          250
từ 20 triệu vnđ         216
từ 15 triệu vnđ         210
từ 12 triệu vnđ         173
trên 15 tr vnd          163
từ 9 triệu vnđ          152
trên 10 tr vnd          119
trên 20 tr vnd           96
đến 15 triệu vnđ         85
trên 12 tr vnd           79
từ 7 triệu vnđ           79
trên 8 tr vnd            78
trên 25 tr vnd           67
từ 11 triệu vnđ          60
từ 35 triệu vnđ          57
đến 35 triệu vnđ         57
đến 12 triệu vnđ         54
từ 18 triệu vnđ          52
đến 30 triệu vnđ         52
từ 16 triệu vnđ          52
trên 7 tr vnd            47
từ 6 triệu vnđ           46
lên đến 15 tr vnd        45
từ 25 triệu vnđ          45
trên 30 tr vnd           44
lên đến 20 tr vnd        44
lên đến 30 tr vnd        40
từ 14 triệu vnđ          40
từ 5 triệu vnđ           39
đến 2 triệu vnđ          39
từ 13 triệu vnđ          39
trên 13 tr vnd           38
trên 9 tr vnd            38
từ 3 triệu vnđ           34
từ 2 triệu vnđ           34
đến 25 triệu vnđ         34
từ 17 triệu vnđ          32
từ 4 triệu vnđ           30
từ 1 triệu vnđ           27
lên đến 25 tr vnd        25
đến 22 triệu vnđ         25
tới 20 triệu             25
trên 11 tr vnd           24
trên 6 tr vnd            24
lên đến 12 tr vnd        24
trên 18 tr vnd           23
đến 14 triệu vnđ         23
đến 17 triệu vnđ         23
đến 3 triệu vnđ          23
lên đến 40 tr vnd        22
đến 10 triệu vnđ         21
đến 18 triệu vnđ         21
trên 50 tr vnd           20
trên 15 triệu            18
trên 14 tr vnd           17
lên đến 35 tr vnd        17
từ 30 triệu vnđ          17
đến 1 triệu vnđ          17
tới 35 triệu             17
đến 8 triệu vnđ          16
đến 40 triệu vnđ         16
từ 40 triệu vnđ          15
đến 4 triệu vnđ          15
trên 5 tr vnd            13
lên đến 50 tr vnd        13
lên đến 16 tr vnd        12
lên đến 10 tr vnd        12
trên 35 tr vnd           12
đến 68 triệu vnđ         12
đến 13 triệu vnđ         12
trên 8 triệu             12
tới 1,000 usd            12
lên đến 14 tr vnd        11
lên đến 9 tr vnd         11
đến 16 triệu vnđ         11
từ 50 triệu vnđ          11
đến 9 triệu vnđ          11
đến 19 triệu vnđ         11
tới 30 triệu             11
trên 16 tr vnd           10
từ 183 triệu vnđ         10
tới 25 triệu             10
trên 22 tr vnd            9
từ 85 triệu vnđ           9
trên 10 triệu             9
lên đến 23 tr vnd         8
lên đến 18 tr vnd         8
lên đến 2 tr vnd          8
lên đến 22 tr vnd         8
trên 4 tr vnd             8
đến 7 triệu vnđ           8
trên 20 triệu             8
tới 15 triệu              8
trên 2 tr vnd             7
trên 3 tr vnd             7
đến 11 triệu vnđ          7
từ 573 triệu vnđ          7
trên 25 triệu             7
trên 13 triệu             7
trên 1,000 usd            6
lên đến 17 tr vnd         6
trên 17 tr vnd            6
trên 40 tr vnd            6
trên 60 tr vnd            6
lên đến 8 tr vnd          6
lên đến 80 tr vnd         6
đến 5 triệu vnđ           6
đến 29 triệu vnđ          6
từ 68 triệu vnđ           6
trên 12 triệu             6
tới 12 triệu              6
tới 2,500 usd             6
lên đến 8,7 tr vnd        5
trên 1,200 usd            5
đến 24 triệu vnđ          5
từ 165 triệu vnđ          5
đến 50 triệu vnđ          5
từ 100 triệu vnđ          5
từ 31 triệu vnđ           5
tới 2,000 usd             5
trên 5,5 tr vnd           4
lên đến 26 tr vnd         4
lên đến 45 tr vnd         4
trên 2,000 usd            4
lên đến 2,000 usd         4
trên 7,5 tr vnd           4
trên 6,5 tr vnd           4
lên đến 1,000 usd         4
lên đến 5 tr vnd          4
từ 459 triệu vnđ          4
từ 75 triệu vnđ           4
đến 6 triệu vnđ           4
tới 50 triệu              4
trên 9 triệu              4
lên đến 13 tr vnd         3
trên 19 tr vnd            3
trên 8,5 tr vnd           3
lên đến 9,6 tr vnd        3
trên 500 usd              3
trên 70 tr vnd            3
từ 712 triệu vnđ          3
từ 710 triệu vnđ          3
đến 33 triệu vnđ          3
từ 22 triệu vnđ           3
đến 70 triệu vnđ          3
từ 57 triệu vnđ           3
từ 2066 triệu vnđ         3
từ 79 triệu vnđ           3
đến 60 triệu vnđ          3
đến 27 triệu vnđ          3
từ 812 triệu vnđ          3
từ 93 triệu vnđ           3
đến 85 triệu vnđ          3
tới 26 triệu              3
trên 18 triệu             3
tới 75 triệu              3
trên 6 triệu              3
đến 75 triệu vnđ          3
trên 7 triệu              3
trên 3,5 tr vnd           2
trên 9,3 tr vnd           2
lên đến 2,300 usd         2
trên 1,500 usd            2
trên 12,5 tr vnd          2
lên đến 500,000 vnd       2
trên 9,5 tr vnd           2
trên 26 tr vnd            2
trên 33 tr vnd            2
trên 45 tr vnd            2
lên đến 11 tr vnd         2
trên 55 tr vnd            2
trên 700 usd              2
trên 3,000 usd            2
lên đến 60 tr vnd         2
trên 10,5 tr vnd          2
lên đến 9,3 tr vnd        2
từ 23 triệu vnđ           2
từ 28 triệu vnđ           2
từ 252 triệu vnđ          2
từ 713 triệu vnđ          2
từ 818 triệu vnđ          2
đến 45 triệu vnđ          2
trên 7.5 triệu            2
tới 27 triệu              2
tới 1,800 usd             2
tới 60 triệu              2
trên 30 triệu             2
tới 14 triệu              2
từ 1147 triệu vnđ         2
tới 16 triệu              2
tới 28 triệu              2
tới 13 triệu              2
trên 17 triệu             2
tới 10 triệu              2
trên 3 triệu              2
tới 18 triệu              2
tới 40 triệu              2
trên 4,000 usd            1
trên 4,2 tr vnd           1
lên đến 3 tr vnd          1
lên đến 1,800 usd         1
lên đến 1,500 usd         1
lên đến 6 tr vnd          1
lên đến 65 tr vnd         1
lên đến 3,6 tr vnd        1
trên 2,500 usd            1
trên 730,000 vnd          1
lên đến 1 tr vnd          1
lên đến 1,7 tr vnd        1
lên đến 24 tr vnd         1
lên đến 3,500 usd         1
lên đến 19 tr vnd         1
lên đến 600 usd           1
lên đến 4,000 usd         1
lên đến 2,0 tr vnd        1
lên đến 100 tr vnd        1
trên 1 tr vnd             1
lên đến 21 tr vnd         1
trên 21 tr vnd            1
trên 1,5 tr vnd           1
lên đến 32 tr vnd         1
lên đến 29 tr vnd         1
trên 11,5 tr vnd          1
trên 7,6 tr vnd           1
lên đến 6,7 tr vnd        1
lên đến 33 tr vnd         1
lên đến 12,5 tr vnd       1
trên 10,7 tr vnd          1
trên 29 tr vnd            1
trên 750 usd              1
lên đến 3,5 tr vnd        1
lên đến 28 tr vnd         1
trên 13,5 tr vnd          1
trên 400 usd              1
trên 90 tr vnd            1
trên 24 tr vnd            1
từ 527 triệu vnđ          1
tới 0.5 triệu             1
tới 21 triệu              1
tới 17 triệu              1
tới 11 triệu              1
trên 9.5 triệu            1
trên 3.5 triệu            1
trên 16 triệu             1
tới 4 triệu               1
tới 8 triệu               1
trên 50 triệu             1
tới 5 triệu               1
trên 4 triệu              1
tới 45 triệu              1
tới 3,000 usd             1
lên đến 70 tr vnd         1
tới 22 triệu              1

In [110]:
def get_salary_type(salary):
    salary = salary.lower().strip()

    if "từ" in salary:
        return "FROM"
    elif "trên" in salary:
        return "ABOVE"
    elif "đến" in salary or "tới" in salary:
        return "UP_TO"
    else:
        return "EXACT"


clean_df["salary_type"] = clean_df["salary"].apply(get_salary_type)

print(clean_df["salary_type"].value_counts())

salary_type
EXACT    79854
UP_TO     2338
FROM      2145
ABOVE     1133
Name: count, dtype: int64

In [111]:
print(
    clean_df[
        clean_df["salary_numbers"].apply(len) == 1
    ][["salary", "salary_type"]]
    .drop_duplicates()
    .sort_values(["salary_type", "salary"])
    .to_string(index=False)
)

             salary salary_type
      trên 1 tr vnd       ABOVE
     trên 1,000 usd       ABOVE
     trên 1,200 usd       ABOVE
    trên 1,5 tr vnd       ABOVE
     trên 1,500 usd       ABOVE
     trên 10 tr vnd       ABOVE
      trên 10 triệu       ABOVE
   trên 10,5 tr vnd       ABOVE
   trên 10,7 tr vnd       ABOVE
     trên 11 tr vnd       ABOVE
   trên 11,5 tr vnd       ABOVE
     trên 12 tr vnd       ABOVE
      trên 12 triệu       ABOVE
   trên 12,5 tr vnd       ABOVE
     trên 13 tr vnd       ABOVE
      trên 13 triệu       ABOVE
   trên 13,5 tr vnd       ABOVE
     trên 14 tr vnd       ABOVE
     trên 15 tr vnd       ABOVE
      trên 15 triệu       ABOVE
     trên 16 tr vnd       ABOVE
      trên 16 triệu       ABOVE
     trên 17 tr vnd       ABOVE
      trên 17 triệu       ABOVE
     trên 18 tr vnd       ABOVE
      trên 18 triệu       ABOVE
     trên 19 tr vnd       ABOVE
      trên 2 tr vnd       ABOVE
     trên 2,000 usd       ABOVE
     trên 2,500 usd       ABOVE
     trên 20 tr vnd       ABOVE
      trên 20 triệu       ABOVE
     trên 21 tr vnd       ABOVE
     trên 22 tr vnd       ABOVE
     trên 24 tr vnd       ABOVE
     trên 25 tr vnd       ABOVE
      trên 25 triệu       ABOVE
     trên 26 tr vnd       ABOVE
     trên 29 tr vnd       ABOVE
      trên 3 tr vnd       ABOVE
       trên 3 triệu       ABOVE
     trên 3,000 usd       ABOVE
    trên 3,5 tr vnd       ABOVE
     trên 3.5 triệu       ABOVE
     trên 30 tr vnd       ABOVE
      trên 30 triệu       ABOVE
     trên 33 tr vnd       ABOVE
     trên 35 tr vnd       ABOVE
      trên 4 tr vnd       ABOVE
       trên 4 triệu       ABOVE
     trên 4,000 usd       ABOVE
    trên 4,2 tr vnd       ABOVE
     trên 40 tr vnd       ABOVE
       trên 400 usd       ABOVE
     trên 45 tr vnd       ABOVE
      trên 5 tr vnd       ABOVE
    trên 5,5 tr vnd       ABOVE
     trên 50 tr vnd       ABOVE
      trên 50 triệu       ABOVE
       trên 500 usd       ABOVE
     trên 55 tr vnd       ABOVE
      trên 6 tr vnd       ABOVE
       trên 6 triệu       ABOVE
    trên 6,5 tr vnd       ABOVE
     trên 60 tr vnd       ABOVE
      trên 7 tr vnd       ABOVE
       trên 7 triệu       ABOVE
    trên 7,5 tr vnd       ABOVE
    trên 7,6 tr vnd       ABOVE
     trên 7.5 triệu       ABOVE
     trên 70 tr vnd       ABOVE
       trên 700 usd       ABOVE
   trên 730,000 vnd       ABOVE
       trên 750 usd       ABOVE
      trên 8 tr vnd       ABOVE
       trên 8 triệu       ABOVE
    trên 8,5 tr vnd       ABOVE
      trên 9 tr vnd       ABOVE
       trên 9 triệu       ABOVE
    trên 9,3 tr vnd       ABOVE
    trên 9,5 tr vnd       ABOVE
     trên 9.5 triệu       ABOVE
     trên 90 tr vnd       ABOVE
     từ 1 triệu vnđ        FROM
    từ 10 triệu vnđ        FROM
   từ 100 triệu vnđ        FROM
    từ 11 triệu vnđ        FROM
  từ 1147 triệu vnđ        FROM
    từ 12 triệu vnđ        FROM
    từ 13 triệu vnđ        FROM
    từ 14 triệu vnđ        FROM
    từ 15 triệu vnđ        FROM
    từ 16 triệu vnđ        FROM
   từ 165 triệu vnđ        FROM
    từ 17 triệu vnđ        FROM
    từ 18 triệu vnđ        FROM
   từ 183 triệu vnđ        FROM
     từ 2 triệu vnđ        FROM
    từ 20 triệu vnđ        FROM
  từ 2066 triệu vnđ        FROM
    từ 22 triệu vnđ        FROM
    từ 23 triệu vnđ        FROM
    từ 25 triệu vnđ        FROM
   từ 252 triệu vnđ        FROM
    từ 28 triệu vnđ        FROM
     từ 3 triệu vnđ        FROM
    từ 30 triệu vnđ        FROM
    từ 31 triệu vnđ        FROM
    từ 35 triệu vnđ        FROM
     từ 4 triệu vnđ        FROM
    từ 40 triệu vnđ        FROM
   từ 459 triệu vnđ        FROM
     từ 5 triệu vnđ        FROM
    từ 50 triệu vnđ        FROM
   từ 527 triệu vnđ        FROM
    từ 57 triệu vnđ        FROM
   từ 573 triệu vnđ        FROM
     từ 6 triệu vnđ        FROM
    từ 68 triệu vnđ        FROM
     từ 7 triệu vnđ        FROM
   từ 710 triệu vnđ        FROM
   từ 712 triệu vnđ        FROM
   từ 713 triệu vnđ        FROM
    từ 75 triệu vnđ        FROM
    từ 79 triệu vnđ        FROM
     từ 8 triệu vnđ        FROM
   từ 812 triệu vnđ        FROM
   từ 818 triệu vnđ        FROM
    từ 85 triệu vnđ        FROM
     từ 9 triệu vnđ        FROM
    từ 93 triệu vnđ        FROM
   lên đến 1 tr vnd       UP_TO
  lên đến 1,000 usd       UP_TO
  lên đến 1,500 usd       UP_TO
 lên đến 1,7 tr vnd       UP_TO
  lên đến 1,800 usd       UP_TO
  lên đến 10 tr vnd       UP_TO
 lên đến 100 tr vnd       UP_TO
  lên đến 11 tr vnd       UP_TO
  lên đến 12 tr vnd       UP_TO
lên đến 12,5 tr vnd       UP_TO
  lên đến 13 tr vnd       UP_TO
  lên đến 14 tr vnd       UP_TO
  lên đến 15 tr vnd       UP_TO
  lên đến 16 tr vnd       UP_TO
  lên đến 17 tr vnd       UP_TO
  lên đến 18 tr vnd       UP_TO
  lên đến 19 tr vnd       UP_TO
   lên đến 2 tr vnd       UP_TO
 lên đến 2,0 tr vnd       UP_TO
  lên đến 2,000 usd       UP_TO
  lên đến 2,300 usd       UP_TO
  lên đến 20 tr vnd       UP_TO
  lên đến 21 tr vnd       UP_TO
  lên đến 22 tr vnd       UP_TO
  lên đến 23 tr vnd       UP_TO
  lên đến 24 tr vnd       UP_TO
  lên đến 25 tr vnd       UP_TO
  lên đến 26 tr vnd       UP_TO
  lên đến 28 tr vnd       UP_TO
  lên đến 29 tr vnd       UP_TO
   lên đến 3 tr vnd       UP_TO
 lên đến 3,5 tr vnd       UP_TO
  lên đến 3,500 usd       UP_TO
 lên đến 3,6 tr vnd       UP_TO
  lên đến 30 tr vnd       UP_TO
  lên đến 32 tr vnd       UP_TO
  lên đến 33 tr vnd       UP_TO
  lên đến 35 tr vnd       UP_TO
  lên đến 4,000 usd       UP_TO
  lên đến 40 tr vnd       UP_TO
  lên đến 45 tr vnd       UP_TO
   lên đến 5 tr vnd       UP_TO
  lên đến 50 tr vnd       UP_TO
lên đến 500,000 vnd       UP_TO
   lên đến 6 tr vnd       UP_TO
 lên đến 6,7 tr vnd       UP_TO
  lên đến 60 tr vnd       UP_TO
    lên đến 600 usd       UP_TO
  lên đến 65 tr vnd       UP_TO
  lên đến 70 tr vnd       UP_TO
   lên đến 8 tr vnd       UP_TO
 lên đến 8,7 tr vnd       UP_TO
  lên đến 80 tr vnd       UP_TO
   lên đến 9 tr vnd       UP_TO
 lên đến 9,3 tr vnd       UP_TO
 lên đến 9,6 tr vnd       UP_TO
      tới 0.5 triệu       UP_TO
      tới 1,000 usd       UP_TO
      tới 1,800 usd       UP_TO
       tới 10 triệu       UP_TO
       tới 11 triệu       UP_TO
       tới 12 triệu       UP_TO
       tới 13 triệu       UP_TO
       tới 14 triệu       UP_TO
       tới 15 triệu       UP_TO
       tới 16 triệu       UP_TO
       tới 17 triệu       UP_TO
       tới 18 triệu       UP_TO
      tới 2,000 usd       UP_TO
      tới 2,500 usd       UP_TO
       tới 20 triệu       UP_TO
       tới 21 triệu       UP_TO
       tới 22 triệu       UP_TO
       tới 25 triệu       UP_TO
       tới 26 triệu       UP_TO
       tới 27 triệu       UP_TO
       tới 28 triệu       UP_TO
      tới 3,000 usd       UP_TO
       tới 30 triệu       UP_TO
       tới 35 triệu       UP_TO
        tới 4 triệu       UP_TO
       tới 40 triệu       UP_TO
       tới 45 triệu       UP_TO
        tới 5 triệu       UP_TO
       tới 50 triệu       UP_TO
       tới 60 triệu       UP_TO
       tới 75 triệu       UP_TO
        tới 8 triệu       UP_TO
    đến 1 triệu vnđ       UP_TO
   đến 10 triệu vnđ       UP_TO
   đến 11 triệu vnđ       UP_TO
   đến 12 triệu vnđ       UP_TO
   đến 13 triệu vnđ       UP_TO
   đến 14 triệu vnđ       UP_TO
   đến 15 triệu vnđ       UP_TO
   đến 16 triệu vnđ       UP_TO
   đến 17 triệu vnđ       UP_TO
   đến 18 triệu vnđ       UP_TO
   đến 19 triệu vnđ       UP_TO
    đến 2 triệu vnđ       UP_TO
   đến 20 triệu vnđ       UP_TO
   đến 22 triệu vnđ       UP_TO
   đến 24 triệu vnđ       UP_TO
   đến 25 triệu vnđ       UP_TO
   đến 27 triệu vnđ       UP_TO
   đến 29 triệu vnđ       UP_TO
    đến 3 triệu vnđ       UP_TO
   đến 30 triệu vnđ       UP_TO
   đến 33 triệu vnđ       UP_TO
   đến 35 triệu vnđ       UP_TO
    đến 4 triệu vnđ       UP_TO
   đến 40 triệu vnđ       UP_TO
   đến 45 triệu vnđ       UP_TO
    đến 5 triệu vnđ       UP_TO
   đến 50 triệu vnđ       UP_TO
    đến 6 triệu vnđ       UP_TO
   đến 60 triệu vnđ       UP_TO
   đến 68 triệu vnđ       UP_TO
    đến 7 triệu vnđ       UP_TO
   đến 70 triệu vnđ       UP_TO
   đến 75 triệu vnđ       UP_TO
    đến 8 triệu vnđ       UP_TO
   đến 85 triệu vnđ       UP_TO
    đến 9 triệu vnđ       UP_TO

In [112]:
def get_salary_type(salary):
    salary = salary.lower().strip()

    if "từ" in salary:
        return "FROM"
    elif "trên" in salary:
        return "ABOVE"
    elif "đến" in salary or "tới" in salary or "lên đến" in salary:
        return "UP_TO"
    else:
        return "RANGE"


clean_df["salary_type"] = clean_df["salary"].apply(get_salary_type)

In [113]:
def get_salary_min(row):
    numbers = row["salary_vnd"]
    salary_type = row["salary_type"]

    if salary_type in ["RANGE", "FROM", "ABOVE"]:
        return numbers[0]

    return None


def get_salary_max(row):
    numbers = row["salary_vnd"]
    salary_type = row["salary_type"]

    if salary_type == "RANGE":
        return numbers[1]

    elif salary_type == "UP_TO":
        return numbers[0]

    return None


clean_df["salary_min_vnd"] = clean_df.apply(get_salary_min, axis=1)
clean_df["salary_max_vnd"] = clean_df.apply(get_salary_max, axis=1)

In [114]:
print(
    clean_df[
        [
            "salary",
            "salary_type",
            "salary_vnd",
            "salary_min_vnd",
            "salary_max_vnd"
        ]
    ].head(30).to_string(index=False)
)

            salary salary_type               salary_vnd  salary_min_vnd  salary_max_vnd
 15 tr - 50 tr vnd       RANGE [15000000.0, 50000000.0]      15000000.0      50000000.0
  8 tr - 11 tr vnd       RANGE  [8000000.0, 11000000.0]       8000000.0      11000000.0
 20 tr - 30 tr vnd       RANGE [20000000.0, 30000000.0]      20000000.0      30000000.0
   800 - 1,500 usd       RANGE [20000000.0, 37500000.0]      20000000.0      37500000.0
 10 tr - 50 tr vnd       RANGE [10000000.0, 50000000.0]      10000000.0      50000000.0
 15 tr - 40 tr vnd       RANGE [15000000.0, 40000000.0]      15000000.0      40000000.0
 15 tr - 50 tr vnd       RANGE [15000000.0, 50000000.0]      15000000.0      50000000.0
 10 tr - 18 tr vnd       RANGE [10000000.0, 18000000.0]      10000000.0      18000000.0
 15 tr - 20 tr vnd       RANGE [15000000.0, 20000000.0]      15000000.0      20000000.0
 17 tr - 22 tr vnd       RANGE [17000000.0, 22000000.0]      17000000.0      22000000.0
9,5 tr - 12 tr vnd       RANGE  [9500000.0, 12000000.0]       9500000.0      12000000.0
 14 tr - 25 tr vnd       RANGE [14000000.0, 25000000.0]      14000000.0      25000000.0
 15 tr - 18 tr vnd       RANGE [15000000.0, 18000000.0]      15000000.0      18000000.0
  8 tr - 10 tr vnd       RANGE  [8000000.0, 10000000.0]       8000000.0      10000000.0
 12 tr - 15 tr vnd       RANGE [12000000.0, 15000000.0]      12000000.0      15000000.0
 25 tr - 30 tr vnd       RANGE [25000000.0, 30000000.0]      25000000.0      30000000.0
 10 tr - 15 tr vnd       RANGE [10000000.0, 15000000.0]      10000000.0      15000000.0
 10 tr - 25 tr vnd       RANGE [10000000.0, 25000000.0]      10000000.0      25000000.0
8,5 tr - 10 tr vnd       RANGE  [8500000.0, 10000000.0]       8500000.0      10000000.0
 10 tr - 15 tr vnd       RANGE [10000000.0, 15000000.0]      10000000.0      15000000.0
 15 tr - 30 tr vnd       RANGE [15000000.0, 30000000.0]      15000000.0      30000000.0
 12 tr - 20 tr vnd       RANGE [12000000.0, 20000000.0]      12000000.0      20000000.0
 18 tr - 35 tr vnd       RANGE [18000000.0, 35000000.0]      18000000.0      35000000.0
 30 tr - 35 tr vnd       RANGE [30000000.0, 35000000.0]      30000000.0      35000000.0
 15 tr - 25 tr vnd       RANGE [15000000.0, 25000000.0]      15000000.0      25000000.0
 10 tr - 13 tr vnd       RANGE [10000000.0, 13000000.0]      10000000.0      13000000.0
    trên 12 tr vnd       ABOVE             [12000000.0]      12000000.0             NaN
 25 tr - 45 tr vnd       RANGE [25000000.0, 45000000.0]      25000000.0      45000000.0
 10 tr - 15 tr vnd       RANGE [10000000.0, 15000000.0]      10000000.0      15000000.0
   8 tr - 9 tr vnd       RANGE   [8000000.0, 9000000.0]       8000000.0       9000000.0

In [115]:
vnd_without_million = clean_df[
    (
        clean_df["salary_currency"] == "VND"
    ) &
    ~clean_df["salary"].str.lower().str.contains(r"\btr\b|triệu", regex=True)
]

print(
    vnd_without_million["salary"]
    .value_counts()
    .to_string()
)

salary
lên đến 500,000 vnd      2
trên 730,000 vnd         1
500,000 - 500,000 vnd    1
700,000 - 700,000 vnd    1
8 - 15 vnd               1
6 - 10 vnd               1

In [116]:
raw_vnd_mask = (
    clean_df["salary"].str.lower().str.contains(r"\bvnd\b")
    & ~clean_df["salary"].str.lower().str.contains(r"\btr\b|triệu", regex=True)
    & ~clean_df["salary"].str.lower().str.contains(r"^\s*[68]\s*-\s*(10|15)\s*vnd", regex=True)
)

print(
    clean_df.loc[
        raw_vnd_mask,
        ["salary", "salary_numbers", "salary_vnd"]
    ].to_string(index=False)
)

               salary       salary_numbers                       salary_vnd
     trên 730,000 vnd           [730000.0]                 [730000000000.0]
500,000 - 500,000 vnd [500000.0, 500000.0] [500000000000.0, 500000000000.0]
700,000 - 700,000 vnd [700000.0, 700000.0] [700000000000.0, 700000000000.0]
  lên đến 500,000 vnd           [500000.0]                 [500000000000.0]
  lên đến 500,000 vnd           [500000.0]                 [500000000000.0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_15164\2895048151.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  & ~clean_df["salary"].str.lower().str.contains(r"^\s*[68]\s*-\s*(10|15)\s*vnd", regex=True)

In [117]:
print(
    clean_df[
        clean_df["salary"].isin(raw_vnd_values)
    ][
        [
            "salary",
            "salary_numbers",
            "salary_vnd"
        ]
    ].to_string(index=False)
)

NameError: name 'raw_vnd_values' is not defined

In [118]:
raw_vnd_mask = (
    clean_df["salary"].str.lower().str.contains(r"\bvnd\b")
    & ~clean_df["salary"].str.lower().str.contains(r"\btr\b|triệu", regex=True)
    & ~clean_df["salary"].str.lower().str.contains(
        r"^\s*[68]\s*-\s*(?:10|15)\s*vnd",
        regex=True
    )
)

In [119]:
clean_df.loc[
    clean_df["salary"].isin(raw_vnd_values),
    "salary_vnd"
] = clean_df.loc[
    clean_df["salary"].isin(raw_vnd_values),
    "salary_numbers"
    ]

NameError: name 'raw_vnd_values' is not defined

In [120]:
raw_vnd_values = [
    "lên đến 500,000 vnd",
    "trên 730,000 vnd",
    "500,000 - 500,000 vnd",
    "700,000 - 700,000 vnd"
]

In [121]:
clean_df.loc[
    clean_df["salary"].isin(raw_vnd_values),
    "salary_vnd"
] = clean_df.loc[
    clean_df["salary"].isin(raw_vnd_values),
    "salary_numbers"
    ]

In [122]:
print(
    clean_df[
        clean_df["salary"].isin(raw_vnd_values)
    ][
        [
            "salary",
            "salary_numbers",
            "salary_vnd"
        ]
    ].to_string(index=False)
)

               salary       salary_numbers           salary_vnd
     trên 730,000 vnd           [730000.0]           [730000.0]
500,000 - 500,000 vnd [500000.0, 500000.0] [500000.0, 500000.0]
700,000 - 700,000 vnd [700000.0, 700000.0] [700000.0, 700000.0]
  lên đến 500,000 vnd           [500000.0]           [500000.0]
  lên đến 500,000 vnd           [500000.0]           [500000.0]

In [123]:
for value in raw_vnd_values:
    mask = clean_df["salary"] == value

    clean_df.loc[mask, "salary_min_vnd"] = clean_df.loc[
        mask, "salary_vnd"
    ].apply(lambda x: x[0])

    clean_df.loc[mask, "salary_max_vnd"] = clean_df.loc[
        mask, "salary_vnd"
    ].apply(lambda x: x[-1] if len(x) == 2 else x[0])

In [124]:
def convert_raw_vnd(numbers):
    return numbers


raw_vnd_values = [
    "lên đến 500,000 vnd",
    "trên 730,000 vnd",
    "500,000 - 500,000 vnd",
    "700,000 - 700,000 vnd"
]

clean_df.loc[
    clean_df["salary"].isin(raw_vnd_values),
    "salary_vnd"
] = clean_df.loc[
    clean_df["salary"].isin(raw_vnd_values),
    "salary_numbers"
    ]

In [125]:
for value in raw_vnd_values:
    mask = clean_df["salary"] == value

    clean_df.loc[mask, "salary_min_vnd"] = clean_df.loc[
        mask, "salary_vnd"
    ].apply(lambda x: x[0])

    clean_df.loc[mask, "salary_max_vnd"] = clean_df.loc[
        mask, "salary_vnd"
    ].apply(lambda x: x[-1] if len(x) == 2 else x[0])

In [126]:
clean_df["salary_quality"] = "OK"

clean_df.loc[
    clean_df["salary"].isin([
        "8 - 15 vnd",
        "6 - 10 vnd"
    ]),
    "salary_quality"
] = "SUSPICIOUS"

In [127]:
print(
    clean_df[
        clean_df["salary_quality"] == "SUSPICIOUS"
    ][
        [
            "salary",
            "salary_currency",
            "salary_numbers",
            "salary_vnd",
            "salary_min_vnd",
            "salary_max_vnd",
            "salary_quality"
        ]
    ].to_string(index=False)
)

    salary salary_currency salary_numbers              salary_vnd  salary_min_vnd  salary_max_vnd salary_quality
8 - 15 vnd             VND    [8.0, 15.0] [8000000.0, 15000000.0]       8000000.0      15000000.0     SUSPICIOUS
6 - 10 vnd             VND    [6.0, 10.0] [6000000.0, 10000000.0]       6000000.0      10000000.0     SUSPICIOUS

In [128]:
suspicious_low_salary = clean_df[
    (
        clean_df["salary_currency"] == "VND"
    ) &
    (
        clean_df["salary_min_vnd"].notna()
    ) &
    (
        clean_df["salary_min_vnd"] < 1_000_000
    )
]

print(
    suspicious_low_salary[
        [
            "salary",
            "salary_type",
            "salary_vnd",
            "salary_min_vnd",
            "salary_max_vnd",
            "salary_quality"
        ]
    ].to_string(index=False)
)

               salary salary_type            salary_vnd  salary_min_vnd  salary_max_vnd salary_quality
     trên 730,000 vnd       ABOVE            [730000.0]        730000.0        730000.0             OK
500,000 - 500,000 vnd       RANGE  [500000.0, 500000.0]        500000.0        500000.0             OK
700,000 - 700,000 vnd       RANGE  [700000.0, 700000.0]        700000.0        700000.0             OK
  lên đến 500,000 vnd       UP_TO            [500000.0]        500000.0        500000.0             OK
  lên đến 500,000 vnd       UP_TO            [500000.0]        500000.0        500000.0             OK
        0.1 - 1 triệu       RANGE [100000.0, 1000000.0]        100000.0       1000000.0             OK
        0.1 - 2 triệu       RANGE [100000.0, 2000000.0]        100000.0       2000000.0             OK
      0.0 - 0.0 triệu       RANGE            [0.0, 0.0]             0.0             0.0             OK
      0.0 - 0.0 triệu       RANGE            [0.0, 0.0]             0.0             0.0             OK
      0.0 - 0.0 triệu       RANGE            [0.0, 0.0]             0.0             0.0             OK
      0.0 - 0.0 triệu       RANGE            [0.0, 0.0]             0.0             0.0             OK

In [129]:
suspicious_high_salary = clean_df[
    (
        clean_df["salary_max_vnd"].notna()
    ) &
    (
        clean_df["salary_max_vnd"] > 1_000_000_000
    )
]

print(
    suspicious_high_salary[
        [
            "salary",
            "salary_type",
            "salary_vnd",
            "salary_min_vnd",
            "salary_max_vnd"
        ]
    ].to_string(index=False)
)

Empty DataFrame
Columns: [salary, salary_type, salary_vnd, salary_min_vnd, salary_max_vnd]
Index: []

In [130]:
clean_df.loc[
    clean_df["salary_min_vnd"] == 0,
    "salary_quality"
] = "SUSPICIOUS"

In [131]:
print(
    clean_df[
        clean_df["salary_quality"] == "SUSPICIOUS"
    ][
        [
            "salary",
            "salary_type",
            "salary_vnd",
            "salary_min_vnd",
            "salary_max_vnd",
            "salary_quality"
        ]
    ].to_string(index=False)
)

         salary salary_type              salary_vnd  salary_min_vnd  salary_max_vnd salary_quality
     8 - 15 vnd       RANGE [8000000.0, 15000000.0]       8000000.0      15000000.0     SUSPICIOUS
0.0 - 0.0 triệu       RANGE              [0.0, 0.0]             0.0             0.0     SUSPICIOUS
0.0 - 0.0 triệu       RANGE              [0.0, 0.0]             0.0             0.0     SUSPICIOUS
     6 - 10 vnd       RANGE [6000000.0, 10000000.0]       6000000.0      10000000.0     SUSPICIOUS
0.0 - 0.0 triệu       RANGE              [0.0, 0.0]             0.0             0.0     SUSPICIOUS
0.0 - 0.0 triệu       RANGE              [0.0, 0.0]             0.0             0.0     SUSPICIOUS

In [132]:
def get_salary_min(row):
    numbers = row["salary_vnd"]
    salary_type = row["salary_type"]

    if salary_type in ["RANGE", "FROM", "ABOVE"]:
        return numbers[0]

    return None


def get_salary_max(row):
    numbers = row["salary_vnd"]
    salary_type = row["salary_type"]

    if salary_type == "RANGE":
        return numbers[1]

    elif salary_type == "UP_TO":
        return numbers[0]

    return None


clean_df["salary_min_vnd"] = clean_df.apply(
    get_salary_min,
    axis=1
)

clean_df["salary_max_vnd"] = clean_df.apply(
    get_salary_max,
    axis=1
)

In [133]:
print(
    clean_df[
        clean_df["salary"].isin([
            "lên đến 500,000 vnd",
            "trên 730,000 vnd",
            "500,000 - 500,000 vnd",
            "700,000 - 700,000 vnd"
        ])
    ][
        [
            "salary",
            "salary_type",
            "salary_vnd",
            "salary_min_vnd",
            "salary_max_vnd"
        ]
    ].to_string(index=False)
)

               salary salary_type           salary_vnd  salary_min_vnd  salary_max_vnd
     trên 730,000 vnd       ABOVE           [730000.0]        730000.0             NaN
500,000 - 500,000 vnd       RANGE [500000.0, 500000.0]        500000.0        500000.0
700,000 - 700,000 vnd       RANGE [700000.0, 700000.0]        700000.0        700000.0
  lên đến 500,000 vnd       UP_TO           [500000.0]             NaN        500000.0
  lên đến 500,000 vnd       UP_TO           [500000.0]             NaN        500000.0

In [134]:
invalid_ranges = clean_df[
    (
        clean_df["salary_min_vnd"].notna()
    ) &
    (
        clean_df["salary_max_vnd"].notna()
    ) &
    (
        clean_df["salary_min_vnd"] > clean_df["salary_max_vnd"]
    )
]

print(
    invalid_ranges[
        [
            "salary",
            "salary_type",
            "salary_min_vnd",
            "salary_max_vnd"
        ]
    ].to_string(index=False)
)

print("Invalid range count:", len(invalid_ranges))

              salary salary_type  salary_min_vnd  salary_max_vnd
 700,000 - 10 tr vnd       RANGE    7.000000e+11      10000000.0
  500,000 - 1 tr vnd       RANGE    5.000000e+11       1000000.0
900,000 - 1,5 tr vnd       RANGE    9.000000e+11       1500000.0
    12 - 3 triệu vnđ       RANGE    1.200000e+07       3000000.0
    75 - 9 triệu vnđ       RANGE    7.500000e+07       9000000.0
    75 - 8 triệu vnđ       RANGE    7.500000e+07       8000000.0
   76 - 15 triệu vnđ       RANGE    7.600000e+07      15000000.0
    17 - 9 triệu vnđ       RANGE    1.700000e+07       9000000.0
    45 - 5 triệu vnđ       RANGE    4.500000e+07       5000000.0
     7 - 6 triệu vnđ       RANGE    7.000000e+06       6000000.0
     7 - 6 triệu vnđ       RANGE    7.000000e+06       6000000.0
    45 - 5 triệu vnđ       RANGE    4.500000e+07       5000000.0
    55 - 8 triệu vnđ       RANGE    5.500000e+07       8000000.0
    45 - 5 triệu vnđ       RANGE    4.500000e+07       5000000.0
    75 - 8 triệu vnđ       RANGE    7.500000e+07       8000000.0
   14 - 10 triệu vnđ       RANGE    1.400000e+07      10000000.0
    45 - 5 triệu vnđ       RANGE    4.500000e+07       5000000.0
     7 - 2 triệu vnđ       RANGE    7.000000e+06       2000000.0
     7 - 6 triệu vnđ       RANGE    7.000000e+06       6000000.0
    75 - 8 triệu vnđ       RANGE    7.500000e+07       8000000.0
    65 - 8 triệu vnđ       RANGE    6.500000e+07       8000000.0
   50 - 11 triệu vnđ       RANGE    5.000000e+07      11000000.0
   85 - 11 triệu vnđ       RANGE    8.500000e+07      11000000.0
    75 - 8 triệu vnđ       RANGE    7.500000e+07       8000000.0
   85 - 11 triệu vnđ       RANGE    8.500000e+07      11000000.0
   85 - 12 triệu vnđ       RANGE    8.500000e+07      12000000.0
    25 - 3 triệu vnđ       RANGE    2.500000e+07       3000000.0
    10 - 4 triệu vnđ       RANGE    1.000000e+07       4000000.0
    75 - 8 triệu vnđ       RANGE    7.500000e+07       8000000.0
    25 - 3 triệu vnđ       RANGE    2.500000e+07       3000000.0
    45 - 5 triệu vnđ       RANGE    4.500000e+07       5000000.0
    45 - 5 triệu vnđ       RANGE    4.500000e+07       5000000.0
    25 - 3 triệu vnđ       RANGE    2.500000e+07       3000000.0
    75 - 9 triệu vnđ       RANGE    7.500000e+07       9000000.0
    15 - 3 triệu vnđ       RANGE    1.500000e+07       3000000.0
    75 - 9 triệu vnđ       RANGE    7.500000e+07       9000000.0
   13 - 12 triệu vnđ       RANGE    1.300000e+07      12000000.0
    17 - 9 triệu vnđ       RANGE    1.700000e+07       9000000.0
     7 - 6 triệu vnđ       RANGE    7.000000e+06       6000000.0
    75 - 9 triệu vnđ       RANGE    7.500000e+07       9000000.0
   76 - 15 triệu vnđ       RANGE    7.600000e+07      15000000.0
  135 - 18 triệu vnđ       RANGE    1.350000e+08      18000000.0
   78 - 13 triệu vnđ       RANGE    7.800000e+07      13000000.0
    17 - 9 triệu vnđ       RANGE    1.700000e+07       9000000.0
   75 - 10 triệu vnđ       RANGE    7.500000e+07      10000000.0
    15 - 2 triệu vnđ       RANGE    1.500000e+07       2000000.0
   13 - 12 triệu vnđ       RANGE    1.300000e+07      12000000.0
    75 - 9 triệu vnđ       RANGE    7.500000e+07       9000000.0
    10 - 4 triệu vnđ       RANGE    1.000000e+07       4000000.0
   76 - 15 triệu vnđ       RANGE    7.600000e+07      15000000.0
   13 - 12 triệu vnđ       RANGE    1.300000e+07      12000000.0
   85 - 12 triệu vnđ       RANGE    8.500000e+07      12000000.0
    15 - 2 triệu vnđ       RANGE    1.500000e+07       2000000.0
   28 - 15 triệu vnđ       RANGE    2.800000e+07      15000000.0
    15 - 3 triệu vnđ       RANGE    1.500000e+07       3000000.0
    15 - 3 triệu vnđ       RANGE    1.500000e+07       3000000.0
  135 - 18 triệu vnđ       RANGE    1.350000e+08      18000000.0
     7 - 2 triệu vnđ       RANGE    7.000000e+06       2000000.0
     7 - 2 triệu vnđ       RANGE    7.000000e+06       2000000.0
    75 - 9 triệu vnđ       RANGE    7.500000e+07       9000000.0
   13 - 12 triệu vnđ       RANGE    1.300000e+07      12000000.0
    75 - 8 triệu vnđ       RANGE    7.500000e+07       8000000.0
   28 - 15 triệu vnđ       RANGE    2.800000e+07      15000000.0
    15 - 2 triệu vnđ       RANGE    1.500000e+07       2000000.0
    12 - 3 triệu vnđ       RANGE    1.200000e+07       3000000.0
   28 - 15 triệu vnđ       RANGE    2.800000e+07      15000000.0
     7 - 2 triệu vnđ       RANGE    7.000000e+06       2000000.0
    15 - 2 triệu vnđ       RANGE    1.500000e+07       2000000.0
   78 - 13 triệu vnđ       RANGE    7.800000e+07      13000000.0
    12 - 3 triệu vnđ       RANGE    1.200000e+07       3000000.0
   14 - 10 triệu vnđ       RANGE    1.400000e+07      10000000.0
     7 - 6 triệu vnđ       RANGE    7.000000e+06       6000000.0
     7 - 2 triệu vnđ       RANGE    7.000000e+06       2000000.0
   85 - 12 triệu vnđ       RANGE    8.500000e+07      12000000.0
    26 - 6 triệu vnđ       RANGE    2.600000e+07       6000000.0
    26 - 6 triệu vnđ       RANGE    2.600000e+07       6000000.0
  100 - 20 triệu vnđ       RANGE    1.000000e+08      20000000.0
Invalid range count: 77

In [135]:
print(
    clean_df[
        [
            "salary_type",
            "salary_min_vnd",
            "salary_max_vnd"
        ]
    ]
    .isna()
    .groupby(clean_df["salary_type"])
    .sum()
)

             salary_type  salary_min_vnd  salary_max_vnd
salary_type
ABOVE                  0               0            1133
FROM                   0               0            2145
RANGE                  0               0               0
UP_TO                  0            2338               0

In [136]:
print(clean_df["salary_type"].value_counts())

salary_type
RANGE    79854
UP_TO     2338
FROM      2145
ABOVE     1133
Name: count, dtype: int64

In [137]:
print(clean_df["salary_currency"].value_counts())

salary_currency
VND    84757
USD      713
Name: count, dtype: int64

In [138]:
print(
    clean_df["salary_quality"].value_counts()
)

salary_quality
OK            85464
SUSPICIOUS        6
Name: count, dtype: int64

In [139]:
invalid_ranges_unique = (
    invalid_ranges[
        ["salary", "salary_min_vnd", "salary_max_vnd"]
    ]
    .drop_duplicates()
    .sort_values("salary")
)

print(invalid_ranges_unique.to_string(index=False))
print("Unique invalid salaries:", len(invalid_ranges_unique))

              salary  salary_min_vnd  salary_max_vnd
    10 - 4 triệu vnđ    1.000000e+07       4000000.0
  100 - 20 triệu vnđ    1.000000e+08      20000000.0
    12 - 3 triệu vnđ    1.200000e+07       3000000.0
   13 - 12 triệu vnđ    1.300000e+07      12000000.0
  135 - 18 triệu vnđ    1.350000e+08      18000000.0
   14 - 10 triệu vnđ    1.400000e+07      10000000.0
    15 - 2 triệu vnđ    1.500000e+07       2000000.0
    15 - 3 triệu vnđ    1.500000e+07       3000000.0
    17 - 9 triệu vnđ    1.700000e+07       9000000.0
    25 - 3 triệu vnđ    2.500000e+07       3000000.0
    26 - 6 triệu vnđ    2.600000e+07       6000000.0
   28 - 15 triệu vnđ    2.800000e+07      15000000.0
    45 - 5 triệu vnđ    4.500000e+07       5000000.0
   50 - 11 triệu vnđ    5.000000e+07      11000000.0
  500,000 - 1 tr vnd    5.000000e+11       1000000.0
    55 - 8 triệu vnđ    5.500000e+07       8000000.0
    65 - 8 triệu vnđ    6.500000e+07       8000000.0
     7 - 2 triệu vnđ    7.000000e+06       2000000.0
     7 - 6 triệu vnđ    7.000000e+06       6000000.0
 700,000 - 10 tr vnd    7.000000e+11      10000000.0
   75 - 10 triệu vnđ    7.500000e+07      10000000.0
    75 - 8 triệu vnđ    7.500000e+07       8000000.0
    75 - 9 triệu vnđ    7.500000e+07       9000000.0
   76 - 15 triệu vnđ    7.600000e+07      15000000.0
   78 - 13 triệu vnđ    7.800000e+07      13000000.0
   85 - 11 triệu vnđ    8.500000e+07      11000000.0
   85 - 12 triệu vnđ    8.500000e+07      12000000.0
900,000 - 1,5 tr vnd    9.000000e+11       1500000.0
Unique invalid salaries: 28

In [142]:
clean_df.loc[
    clean_df["salary"] == "500,000 - 1 tr vnd",
    "salary_vnd"
] = [[500_000, 1_000_000]]

clean_df.loc[
    clean_df["salary"] == "700,000 - 10 tr vnd",
    "salary_vnd"
] = [[700_000, 10_000_000]]

clean_df.loc[
    clean_df["salary"] == "900,000 - 1,5 tr vnd",
    "salary_vnd"
] = [[900_000, 1_500_000]]

ValueError: Must have equal len keys and value when setting with an ndarray

In [143]:
clean_df.loc[
    clean_df["salary"] == "500,000 - 1 tr vnd",
    "salary_vnd"
] = clean_df.loc[
    clean_df["salary"] == "500,000 - 1 tr vnd"
].apply(
    lambda x: [500_000, 1_000_000]
)

In [144]:
clean_df.loc[
    clean_df["salary"] == "700,000 - 10 tr vnd",
    "salary_vnd"
] = clean_df.loc[
    clean_df["salary"] == "700,000 - 10 tr vnd"
].apply(
    lambda x: [700_000, 10_000_000]
)

clean_df.loc[
    clean_df["salary"] == "900,000 - 1,5 tr vnd",
    "salary_vnd"
] = clean_df.loc[
    clean_df["salary"] == "900,000 - 1,5 tr vnd"
].apply(
    lambda x: [900_000, 1_500_000]
)

In [145]:
clean_df["salary_min_vnd"] = clean_df.apply(
    get_salary_min,
    axis=1
)

clean_df["salary_max_vnd"] = clean_df.apply(
    get_salary_max,
    axis=1
)

TypeError: 'float' object is not subscriptable

In [146]:
print(clean_df["salary_vnd"].apply(type).value_counts())

salary_vnd
<class 'list'>     85467
<class 'float'>        3
Name: count, dtype: int64

In [147]:
bad_salary_vnd = clean_df[
    clean_df["salary_vnd"].apply(lambda x: not isinstance(x, list))
]

print(
    bad_salary_vnd[
        ["salary", "salary_numbers", "salary_vnd"]
    ].to_string(index=False)
)

              salary   salary_numbers salary_vnd
 700,000 - 10 tr vnd [700000.0, 10.0]        NaN
  500,000 - 1 tr vnd  [500000.0, 1.0]        NaN
900,000 - 1,5 tr vnd  [900000.0, 1.5]        NaN

In [148]:
mask = clean_df["salary"] == "500,000 - 1 tr vnd"

for idx in clean_df.index[mask]:
    clean_df.at[idx, "salary_vnd"] = [500_000, 1_000_000]


mask = clean_df["salary"] == "700,000 - 10 tr vnd"

for idx in clean_df.index[mask]:
    clean_df.at[idx, "salary_vnd"] = [700_000, 10_000_000]


mask = clean_df["salary"] == "900,000 - 1,5 tr vnd"

for idx in clean_df.index[mask]:
    clean_df.at[idx, "salary_vnd"] = [900_000, 1_500_000]

In [149]:
print(clean_df["salary_vnd"].apply(type).value_counts())

salary_vnd
<class 'list'>    85470
Name: count, dtype: int64

In [150]:
clean_df["salary_min_vnd"] = clean_df.apply(
    get_salary_min,
    axis=1
)

clean_df["salary_max_vnd"] = clean_df.apply(
    get_salary_max,
    axis=1
)

In [151]:
invalid_ranges = clean_df[
    clean_df["salary_min_vnd"].notna()
    & clean_df["salary_max_vnd"].notna()
    & (clean_df["salary_min_vnd"] > clean_df["salary_max_vnd"])
]

print(
    invalid_ranges[
        ["salary", "salary_type", "salary_min_vnd", "salary_max_vnd"]
    ].drop_duplicates().to_string(index=False)
)

print("Invalid range count:", len(invalid_ranges))

            salary salary_type  salary_min_vnd  salary_max_vnd
  12 - 3 triệu vnđ       RANGE      12000000.0       3000000.0
  75 - 9 triệu vnđ       RANGE      75000000.0       9000000.0
  75 - 8 triệu vnđ       RANGE      75000000.0       8000000.0
 76 - 15 triệu vnđ       RANGE      76000000.0      15000000.0
  17 - 9 triệu vnđ       RANGE      17000000.0       9000000.0
  45 - 5 triệu vnđ       RANGE      45000000.0       5000000.0
   7 - 6 triệu vnđ       RANGE       7000000.0       6000000.0
  55 - 8 triệu vnđ       RANGE      55000000.0       8000000.0
 14 - 10 triệu vnđ       RANGE      14000000.0      10000000.0
   7 - 2 triệu vnđ       RANGE       7000000.0       2000000.0
  65 - 8 triệu vnđ       RANGE      65000000.0       8000000.0
 50 - 11 triệu vnđ       RANGE      50000000.0      11000000.0
 85 - 11 triệu vnđ       RANGE      85000000.0      11000000.0
 85 - 12 triệu vnđ       RANGE      85000000.0      12000000.0
  25 - 3 triệu vnđ       RANGE      25000000.0       3000000.0
  10 - 4 triệu vnđ       RANGE      10000000.0       4000000.0
  15 - 3 triệu vnđ       RANGE      15000000.0       3000000.0
 13 - 12 triệu vnđ       RANGE      13000000.0      12000000.0
135 - 18 triệu vnđ       RANGE     135000000.0      18000000.0
 78 - 13 triệu vnđ       RANGE      78000000.0      13000000.0
 75 - 10 triệu vnđ       RANGE      75000000.0      10000000.0
  15 - 2 triệu vnđ       RANGE      15000000.0       2000000.0
 28 - 15 triệu vnđ       RANGE      28000000.0      15000000.0
  26 - 6 triệu vnđ       RANGE      26000000.0       6000000.0
100 - 20 triệu vnđ       RANGE     100000000.0      20000000.0
Invalid range count: 74

In [152]:
clean_df.loc[
    invalid_ranges.index,
    "salary_quality"
] = "SUSPICIOUS"

In [153]:
print(clean_df["salary_quality"].value_counts())

salary_quality
OK            85390
SUSPICIOUS       80
Name: count, dtype: int64

In [154]:
print(
    clean_df[
        clean_df["salary_quality"] == "SUSPICIOUS"
    ][
        [
            "salary",
            "salary_type",
            "salary_min_vnd",
            "salary_max_vnd"
        ]
    ].drop_duplicates().to_string(index=False)
)

            salary salary_type  salary_min_vnd  salary_max_vnd
        8 - 15 vnd       RANGE       8000000.0      15000000.0
  12 - 3 triệu vnđ       RANGE      12000000.0       3000000.0
  75 - 9 triệu vnđ       RANGE      75000000.0       9000000.0
  75 - 8 triệu vnđ       RANGE      75000000.0       8000000.0
 76 - 15 triệu vnđ       RANGE      76000000.0      15000000.0
  17 - 9 triệu vnđ       RANGE      17000000.0       9000000.0
  45 - 5 triệu vnđ       RANGE      45000000.0       5000000.0
   7 - 6 triệu vnđ       RANGE       7000000.0       6000000.0
  55 - 8 triệu vnđ       RANGE      55000000.0       8000000.0
 14 - 10 triệu vnđ       RANGE      14000000.0      10000000.0
   7 - 2 triệu vnđ       RANGE       7000000.0       2000000.0
  65 - 8 triệu vnđ       RANGE      65000000.0       8000000.0
 50 - 11 triệu vnđ       RANGE      50000000.0      11000000.0
 85 - 11 triệu vnđ       RANGE      85000000.0      11000000.0
 85 - 12 triệu vnđ       RANGE      85000000.0      12000000.0
  25 - 3 triệu vnđ       RANGE      25000000.0       3000000.0
  10 - 4 triệu vnđ       RANGE      10000000.0       4000000.0
  15 - 3 triệu vnđ       RANGE      15000000.0       3000000.0
 13 - 12 triệu vnđ       RANGE      13000000.0      12000000.0
135 - 18 triệu vnđ       RANGE     135000000.0      18000000.0
 78 - 13 triệu vnđ       RANGE      78000000.0      13000000.0
 75 - 10 triệu vnđ       RANGE      75000000.0      10000000.0
  15 - 2 triệu vnđ       RANGE      15000000.0       2000000.0
 28 - 15 triệu vnđ       RANGE      28000000.0      15000000.0
   0.0 - 0.0 triệu       RANGE             0.0             0.0
  26 - 6 triệu vnđ       RANGE      26000000.0       6000000.0
        6 - 10 vnd       RANGE       6000000.0      10000000.0
100 - 20 triệu vnđ       RANGE     100000000.0      20000000.0

In [155]:
invalid_ranges = clean_df[
    clean_df["salary_min_vnd"].notna()
    & clean_df["salary_max_vnd"].notna()
    & (clean_df["salary_min_vnd"] > clean_df["salary_max_vnd"])
]

print("Invalid ranges:", len(invalid_ranges))

Invalid ranges: 74

In [156]:
print(
    clean_df[
        [
            "salary",
            "salary_currency",
            "salary_type",
            "salary_min_vnd",
            "salary_max_vnd",
            "salary_quality"
        ]
    ].isna().sum()
)

salary                0
salary_currency       0
salary_type           0
salary_min_vnd     2338
salary_max_vnd     3278
salary_quality        0
dtype: int64

In [157]:
print(clean_df.columns.tolist())

['job_title', 'job_type', 'position_level', 'city', 'experience', 'skills', 'job_fields', 'salary', 'salary_min', 'salary_max', 'unit', 'salary_clean', 'salary_numbers', 'salary_currency', 'salary_vnd', 'salary_min_vnd', 'salary_max_vnd', 'salary_type', 'salary_quality']

In [158]:
clean_df = clean_df.drop(
    columns=[
        "salary_numbers",
        "salary_vnd"
    ]
)

In [159]:
print(clean_df.columns.tolist())

['job_title', 'job_type', 'position_level', 'city', 'experience', 'skills', 'job_fields', 'salary', 'salary_min', 'salary_max', 'unit', 'salary_clean', 'salary_currency', 'salary_min_vnd', 'salary_max_vnd', 'salary_type', 'salary_quality']

In [160]:
print("Original rows:", len(raw_df))
print("Cleaned rows:", len(clean_df))

Original rows: 85470
Cleaned rows: 85470

In [161]:
clean_df.to_csv(
    "vietnam_jobs_cleaned.csv",
    index=False,
    encoding="utf-8-sig"
)

In [162]:
import os

print(os.path.abspath("vietnam_jobs_cleaned.csv"))
print("File exists:", os.path.exists("vietnam_jobs_cleaned.csv"))

C:\Users\Admin\Documents\VS code\Python\vietnam_jobs_cleaned.csv
File exists: True

In [163]:
test_df = pd.read_csv("vietnam_jobs_cleaned.csv")

print("Saved rows:", len(test_df))
print(test_df.columns.tolist())

Saved rows: 85470
['job_title', 'job_type', 'position_level', 'city', 'experience', 'skills', 'job_fields', 'salary', 'salary_min', 'salary_max', 'unit', 'salary_clean', 'salary_currency', 'salary_min_vnd', 'salary_max_vnd', 'salary_type', 'salary_quality']