In [1]:
print(clean_df.shape)
print(clean_df.columns.tolist())

clean_df.info()

NameError: name 'clean_df' is not defined

In [2]:
import pandas as pd

clean_df = pd.read_csv("vietnam_jobs_cleaned.csv")

print(clean_df.shape)
clean_df.head()

(85470, 17)

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit,salary_clean,salary_currency,salary_min_vnd,salary_max_vnd,salary_type,salary_quality
0,trưởng phòng kinh doanh,nhân viên chính thức,"trưởng nhóm , giám sát",Ho Chi Minh City,lên đến 1 năm,NaN,"kinh doanh, bán hàng, nội ngoại thất, xây dựng",15 tr - 50 tr vnd,15.0,50.0,vnd,15 tr - 50 tr vnd,VND,15000000.0,50000000.0,RANGE,OK
1,nhân viên qc ngành cơ khí,nhân viên chính thức,nhân viên,Ho Chi Minh City,trên 1 năm,"production planning staff, chuyên viên iso, th...","vận hành sản xuất, sản xuất, qc), quản lý chất...",8 tr - 11 tr vnd,8.0,11.0,vnd,8 tr - 11 tr vnd,VND,8000000.0,11000000.0,RANGE,OK
2,trưởng phòng đấu thầu,nhân viên chính thức,"trưởng nhóm , giám sát",Ho Chi Minh City,5 - 7 năm,"trưởng phòng xây dựng, trưởng phòng đấu thầu, ...","điện, xây dựng, điện tử, điện lạnh, dầu khí, đ...",20 tr - 30 tr vnd,20.0,30.0,vnd,20 tr - 30 tr vnd,VND,20000000.0,30000000.0,RANGE,OK
3,home textile designer,nhân viên chính thức,nhân viên,Hung Yen,5 - 15 năm,NaN,"dệt may, nghệ thuật, da giày, thiết kế, mỹ thu...","800 - 1,500 usd",20.0,37.5,usd,"800 - 1,500 usd",USD,20000000.0,37500000.0,RANGE,OK
4,nhân viên kinh doanh,nhân viên chính thức,nhân viên,Ho Chi Minh City,trên 1 năm,NaN,"tư vấn, bán sỉ, bán lẻ, kinh doanh, bán hàng",10 tr - 50 tr vnd,10.0,50.0,vnd,10 tr - 50 tr vnd,VND,10000000.0,50000000.0,RANGE,OK

In [3]:
import pandas as pd
import numpy as np

salary = clean_df['salary_max_vnd'].dropna()

print("Number of salary observations:", len(salary))
print("Minimum:", salary.min())
print("Median:", salary.median())
print("Maximum:", salary.max())
print("Mean:", salary.mean())

Number of salary observations: 82192
Minimum: 0.0
Median: 15000000.0
Maximum: 600000000.0
Mean: 19979352.00506132

In [4]:
salary.describe()

count    8.219200e+04
mean     1.997935e+07
std      1.541328e+07
min      0.000000e+00
25%      1.200000e+07
50%      1.500000e+07
75%      2.300000e+07
max      6.000000e+08
Name: salary_max_vnd, dtype: float64

In [5]:
Q1 = salary.quantile(0.25)
Q3 = salary.quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

iqr_outliers = clean_df[
    (clean_df['salary_max_vnd'] < lower_bound) |
    (clean_df['salary_max_vnd'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of IQR outliers:", len(iqr_outliers))

Q1: 12000000.0
Q3: 23000000.0
IQR: 11000000.0
Lower bound: -4500000.0
Upper bound: 39500000.0
Number of IQR outliers: 5511

In [6]:
iqr_outliers[
    ['job_title', 'city', 'experience', 'salary',
     'salary_min_vnd', 'salary_max_vnd']
].sort_values('salary_max_vnd', ascending=False).head(20)

,job_title,city,experience,salary,salary_min_vnd,salary_max_vnd
18583,môi giới nhà dân hcm tự do thời gian đào tạo p...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0
23463,môi giới nhà hcm hỗ trợ 90 marketing việc làm ...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0
19697,môi giới nhà dân hcm tự do thời gian đào tạo p...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0
3657,ceo stainless steel manufacturing,Ha Nam,20 - 35 năm,"15,000 - 20,000 usd",375000000.0,500000000.0
42362,chuyên viên kinh doanh tư vấn bán hàng lương c...,Hung Yen,không yêu cầu,10 - 500 triệu,10000000.0,500000000.0
41427,chuyên viên kinh doanh phú mỹ hưng,Ho Chi Minh City,không yêu cầu,8 - 500 triệu,8000000.0,500000000.0
41337,chuyên viên kinh doanh phú mỹ hưng,Ho Chi Minh City,không yêu cầu,8 - 500 triệu,8000000.0,500000000.0
2048,tổng giám đốc karofi,Hanoi,10 - 15 năm,"10,000 - 20,000 usd",250000000.0,500000000.0
25098,nhân viên kinh doanh bất động sản lương cứng t...,Binh Duong,không yêu cầu,50 - 500 triệu,50000000.0,500000000.0
41504,chuyên viên kinh doanh tư vấn bán hàng lương c...,Hung Yen,không yêu cầu,10 - 500 triệu,10000000.0,500000000.0
25503,nhân viên kinh doanh bất động sản lương cứng t...,Binh Duong,không yêu cầu,50 - 500 triệu,50000000.0,500000000.0
82684,chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...,Hanoi,không yêu cầu,100 tr - 500 tr vnd,100000000.0,500000000.0
42285,chuyên viên kinh doanh phú mỹ hưng,Ho Chi Minh City,không yêu cầu,8 - 500 triệu,8000000.0,500000000.0
42195,chuyên viên kinh doanh phú mỹ hưng,Ho Chi Minh City,không yêu cầu,8 - 500 triệu,8000000.0,500000000.0
24169,nhân viên kinh doanh bất động sản lương cứng t...,Binh Duong,không yêu cầu,50 - 500 triệu,50000000.0,500000000.0
40022,ceo stainless steel manufacturing,Ha Nam,20 - 35 năm,"15,000 - 20,000 usd",375000000.0,500000000.0
18445,nhân viên kinh doanh bất động sản lương cứng t...,Binh Duong,không yêu cầu,50 - 500 triệu,50000000.0,500000000.0
80495,chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...,Hanoi,không yêu cầu,100 tr - 500 tr vnd,100000000.0,500000000.0
5164,phó tổng giám đốc công nghệ,Hanoi,10 - 20 năm,"10,000 - 20,000 usd",250000000.0,500000000.0
6425,工厂财务 主管 tài chính nhà máy trưởng ban tài chính...,Long An,2 - 8 năm,140 tr - 300 tr vnd,140000000.0,300000000.0

In [7]:
mean_salary = salary.mean()
std_salary = salary.std()

clean_df['salary_zscore'] = (
    clean_df['salary_max_vnd'] - mean_salary
) / std_salary

In [8]:
zscore_outliers = clean_df[
    clean_df['salary_zscore'].abs() > 3
]

print("Number of Z-score outliers:", len(zscore_outliers))

Number of Z-score outliers: 1056

In [9]:
zscore_outliers[
    ['job_title', 'city', 'experience', 'salary',
     'salary_max_vnd', 'salary_zscore']
].sort_values('salary_zscore', ascending=False).head(20)

,job_title,city,experience,salary,salary_max_vnd,salary_zscore
19697,môi giới nhà dân hcm tự do thời gian đào tạo p...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,600000000.0,37.631239
23463,môi giới nhà hcm hỗ trợ 90 marketing việc làm ...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,600000000.0,37.631239
18583,môi giới nhà dân hcm tự do thời gian đào tạo p...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,600000000.0,37.631239
82684,chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...,Hanoi,không yêu cầu,100 tr - 500 tr vnd,500000000.0,31.143325
41504,chuyên viên kinh doanh tư vấn bán hàng lương c...,Hung Yen,không yêu cầu,10 - 500 triệu,500000000.0,31.143325
80495,chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...,Hanoi,không yêu cầu,100 tr - 500 tr vnd,500000000.0,31.143325
3657,ceo stainless steel manufacturing,Ha Nam,20 - 35 năm,"15,000 - 20,000 usd",500000000.0,31.143325
42362,chuyên viên kinh doanh tư vấn bán hàng lương c...,Hung Yen,không yêu cầu,10 - 500 triệu,500000000.0,31.143325
25503,nhân viên kinh doanh bất động sản lương cứng t...,Binh Duong,không yêu cầu,50 - 500 triệu,500000000.0,31.143325
18445,nhân viên kinh doanh bất động sản lương cứng t...,Binh Duong,không yêu cầu,50 - 500 triệu,500000000.0,31.143325
2048,tổng giám đốc karofi,Hanoi,10 - 15 năm,"10,000 - 20,000 usd",500000000.0,31.143325
5164,phó tổng giám đốc công nghệ,Hanoi,10 - 20 năm,"10,000 - 20,000 usd",500000000.0,31.143325
40022,ceo stainless steel manufacturing,Ha Nam,20 - 35 năm,"15,000 - 20,000 usd",500000000.0,31.143325
25098,nhân viên kinh doanh bất động sản lương cứng t...,Binh Duong,không yêu cầu,50 - 500 triệu,500000000.0,31.143325
24169,nhân viên kinh doanh bất động sản lương cứng t...,Binh Duong,không yêu cầu,50 - 500 triệu,500000000.0,31.143325
42285,chuyên viên kinh doanh phú mỹ hưng,Ho Chi Minh City,không yêu cầu,8 - 500 triệu,500000000.0,31.143325
41337,chuyên viên kinh doanh phú mỹ hưng,Ho Chi Minh City,không yêu cầu,8 - 500 triệu,500000000.0,31.143325
41427,chuyên viên kinh doanh phú mỹ hưng,Ho Chi Minh City,không yêu cầu,8 - 500 triệu,500000000.0,31.143325
42195,chuyên viên kinh doanh phú mỹ hưng,Ho Chi Minh City,không yêu cầu,8 - 500 triệu,500000000.0,31.143325
25068,cộng tác viên kinh doanh bđs thời gian linh động,Hanoi,không yêu cầu,50 - 300 triệu,300000000.0,18.167498

In [10]:
print("IQR outliers:", len(iqr_outliers))
print("Z-score outliers:", len(zscore_outliers))

iqr_indices = set(iqr_outliers.index)
z_indices = set(zscore_outliers.index)

print("Detected by both:", len(iqr_indices & z_indices))
print("Only IQR:", len(iqr_indices - z_indices))
print("Only Z-score:", len(z_indices - iqr_indices))

IQR outliers: 5511
Z-score outliers: 1056
Detected by both: 1056
Only IQR: 4455
Only Z-score: 0

In [11]:
top5_outliers = clean_df[
    clean_df['salary_max_vnd'].notna()
].sort_values(
    'salary_max_vnd',
    ascending=False
).head(5)

top5_outliers[
    ['job_title',
     'job_type',
     'position_level',
     'city',
     'experience',
     'salary',
     'salary_min_vnd',
     'salary_max_vnd',
     'salary_currency',
     'salary_quality']
    ]

,job_title,job_type,position_level,city,experience,salary,salary_min_vnd,salary_max_vnd,salary_currency,salary_quality
18583,môi giới nhà dân hcm tự do thời gian đào tạo p...,bán thời gian cố định,"chuyên viên, nhân viên",Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,OK
23463,môi giới nhà hcm hỗ trợ 90 marketing việc làm ...,bán thời gian cố định,"chuyên viên, nhân viên",Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,OK
19697,môi giới nhà dân hcm tự do thời gian đào tạo p...,bán thời gian cố định,"chuyên viên, nhân viên",Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,OK
82684,chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...,nhân viên chính thức,mới tốt nghiệp,Hanoi,không yêu cầu,100 tr - 500 tr vnd,100000000.0,500000000.0,VND,OK
3657,ceo stainless steel manufacturing,nhân viên chính thức,tổng giám đốc,Ha Nam,20 - 35 năm,"15,000 - 20,000 usd",375000000.0,500000000.0,USD,OK

In [12]:
raw_df = df.copy()
clean_df = df.copy()

NameError: name 'df' is not defined

In [13]:
os.listdir()

NameError: name 'os' is not defined

In [14]:
import os

os.listdir()

['.git',
 '.ipynb_checkpoints',
 '.venv',
 '.venv-1',
 'california_cities.csv',
 'CMC',
 'env_202',
 'jobs.csv',
 'jobz_cleaned.csv',
 'Products.txt',
 'Random',
 'SBD_Hoten.zip',
 'Student.json',
 'Test',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'utils.py',
 'vietnam_jobs_cleaned.csv']

In [15]:
import pandas as pd

# Original dataset
raw_df = pd.read_csv("jobs.csv")

# Cleaned dataset from our previous work
clean_df = pd.read_csv("vietnam_jobs_cleaned.csv")

print("Original dataset:", raw_df.shape)
print("Cleaned dataset:", clean_df.shape)

print("\nCleaned columns:")
print(clean_df.columns.tolist())

Original dataset: (85470, 11)
Cleaned dataset: (85470, 17)

Cleaned columns:
['job_title', 'job_type', 'position_level', 'city', 'experience', 'skills', 'job_fields', 'salary', 'salary_min', 'salary_max', 'unit', 'salary_clean', 'salary_currency', 'salary_min_vnd', 'salary_max_vnd', 'salary_type', 'salary_quality']

In [16]:
top5_outliers = clean_df[
    clean_df['salary_max_vnd'].notna()
].sort_values(
    'salary_max_vnd',
    ascending=False
).head(5)

top5_outliers[
    [
        'job_title',
        'job_type',
        'position_level',
        'city',
        'experience',
        'salary',
        'salary_min_vnd',
        'salary_max_vnd',
        'salary_currency',
        'salary_type',
        'salary_quality'
    ]
    ]

,job_title,job_type,position_level,city,experience,salary,salary_min_vnd,salary_max_vnd,salary_currency,salary_type,salary_quality
18583,môi giới nhà dân hcm tự do thời gian đào tạo p...,bán thời gian cố định,"chuyên viên, nhân viên",Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,RANGE,OK
23463,môi giới nhà hcm hỗ trợ 90 marketing việc làm ...,bán thời gian cố định,"chuyên viên, nhân viên",Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,RANGE,OK
19697,môi giới nhà dân hcm tự do thời gian đào tạo p...,bán thời gian cố định,"chuyên viên, nhân viên",Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,RANGE,OK
82684,chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...,nhân viên chính thức,mới tốt nghiệp,Hanoi,không yêu cầu,100 tr - 500 tr vnd,100000000.0,500000000.0,VND,RANGE,OK
3657,ceo stainless steel manufacturing,nhân viên chính thức,tổng giám đốc,Ha Nam,20 - 35 năm,"15,000 - 20,000 usd",375000000.0,500000000.0,USD,RANGE,OK

In [17]:
print(top5_outliers.index)

Index([18583, 23463, 19697, 82684, 3657], dtype='int64')

In [18]:
raw_df.loc[top5_outliers.index]

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit
18583,môi giới nhà dân hcm tự do thời gian đào tạo p...,bán thời gian cố định,"chuyên viên, nhân viên",hồ chí minh,không yêu cầu,", bất động sản, bán hàng kinh doanh, tài chính...",", bất động sản, bán hàng - kinh doanh, tài chí...",36 - 600 triệu,36.0,600.0,vnd
23463,môi giới nhà hcm hỗ trợ 90 marketing việc làm ...,bán thời gian cố định,"chuyên viên, nhân viên",hồ chí minh,không yêu cầu,", bất động sản, bán hàng kinh doanh, tài chính...",", bất động sản, bán hàng - kinh doanh, tài chí...",36 - 600 triệu,36.0,600.0,vnd
19697,môi giới nhà dân hcm tự do thời gian đào tạo p...,bán thời gian cố định,"chuyên viên, nhân viên",hồ chí minh,không yêu cầu,", bất động sản, bán hàng kinh doanh, tài chính...",", bất động sản, bán hàng - kinh doanh, tài chí...",36 - 600 triệu,36.0,600.0,vnd
82684,chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...,nhân viên chính thức,mới tốt nghiệp,hà nội,không yêu cầu,"nhân viên bán hàng qua điện thoại, chuyên viên...",NaN,100 tr - 500 tr vnd,100.0,500.0,vnd
3657,ceo stainless steel manufacturing,nhân viên chính thức,tổng giám đốc,hà nam,20 - 35 năm,"steel, boat, export, vietnam, manufacturing, c...","cơ khí, hàng hải, tự động hóa, ô tô, vận hành ...","15,000 - 20,000 usd",375.0,500.0,usd

In [19]:
for idx, row in top5_outliers.iterrows():
    matches = raw_df[
        (raw_df['job_title'] == row['job_title']) &
        (raw_df['city'] == row['city']) &
        (raw_df['salary'] == row['salary'])
    ]

    print("\n" + "="*80)
    print("CLEANED RECORD")
    print(row[
        ['job_title', 'city', 'experience',
         'salary', 'salary_min_vnd', 'salary_max_vnd']
    ])

    print("\nORIGINAL RECORD(S)")
    print(matches[['job_title', 'city', 'experience', 'salary']])

================================================================================
CLEANED RECORD
job_title         môi giới nhà dân hcm tự do thời gian đào tạo p...
city                                               Ho Chi Minh City
experience                                            không yêu cầu
salary                                               36 - 600 triệu
salary_min_vnd                                           36000000.0
salary_max_vnd                                          600000000.0
Name: 18583, dtype: object

ORIGINAL RECORD(S)
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

================================================================================
CLEANED RECORD
job_title         môi giới nhà hcm hỗ trợ 90 marketing việc làm ...
city                                               Ho Chi Minh City
experience                                            không yêu cầu
salary                                               36 - 600 triệu
salary_min_vnd                                           36000000.0
salary_max_vnd                                          600000000.0
Name: 23463, dtype: object

ORIGINAL RECORD(S)
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

================================================================================
CLEANED RECORD
job_title         môi giới nhà dân hcm tự do thời gian đào tạo p...
city                                               Ho Chi Minh City
experience                                            không yêu cầu
salary                                               36 - 600 triệu
salary_min_vnd                                           36000000.0
salary_max_vnd                                          600000000.0
Name: 19697, dtype: object

ORIGINAL RECORD(S)
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

================================================================================
CLEANED RECORD
job_title         chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...
city                                                          Hanoi
experience                                            không yêu cầu
salary                                          100 tr - 500 tr vnd
salary_min_vnd                                          100000000.0
salary_max_vnd                                          500000000.0
Name: 82684, dtype: object

ORIGINAL RECORD(S)
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

================================================================================
CLEANED RECORD
job_title         ceo stainless steel manufacturing
city                                         Ha Nam
experience                              20 - 35 năm
salary                          15,000 - 20,000 usd
salary_min_vnd                          375000000.0
salary_max_vnd                          500000000.0
Name: 3657, dtype: object

ORIGINAL RECORD(S)
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

In [20]:
top5_outliers[
    [
        'job_title',
        'city',
        'experience',
        'salary',
        'salary_min_vnd',
        'salary_max_vnd',
        'salary_currency',
        'salary_quality'
    ]
    ]

,job_title,city,experience,salary,salary_min_vnd,salary_max_vnd,salary_currency,salary_quality
18583,môi giới nhà dân hcm tự do thời gian đào tạo p...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,OK
23463,môi giới nhà hcm hỗ trợ 90 marketing việc làm ...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,OK
19697,môi giới nhà dân hcm tự do thời gian đào tạo p...,Ho Chi Minh City,không yêu cầu,36 - 600 triệu,36000000.0,600000000.0,VND,OK
82684,chuyên viên tư vấn bất động sản căn hộ hỗ trợ ...,Hanoi,không yêu cầu,100 tr - 500 tr vnd,100000000.0,500000000.0,VND,OK
3657,ceo stainless steel manufacturing,Ha Nam,20 - 35 năm,"15,000 - 20,000 usd",375000000.0,500000000.0,USD,OK

In [21]:
# Find the original records corresponding to the 5 outliers

for idx, row in top5_outliers.iterrows():
    matches = raw_df[
        (raw_df['job_title'] == row['job_title']) &
        (raw_df['city'] == row['city']) &
        (raw_df['salary'] == row['salary'])
    ]

    print("\n" + "=" * 100)
    print("OUTLIER:", idx)
    print("Cleaned salary:", row['salary'])
    print("Cleaned min VND:", row['salary_min_vnd'])
    print("Cleaned max VND:", row['salary_max_vnd'])

    print("\nORIGINAL RECORD:")
    print(matches[['job_title', 'city', 'experience', 'salary']].to_string(index=False))

====================================================================================================
OUTLIER: 18583
Cleaned salary: 36 - 600 triệu
Cleaned min VND: 36000000.0
Cleaned max VND: 600000000.0

ORIGINAL RECORD:
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

====================================================================================================
OUTLIER: 23463
Cleaned salary: 36 - 600 triệu
Cleaned min VND: 36000000.0
Cleaned max VND: 600000000.0

ORIGINAL RECORD:
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

====================================================================================================
OUTLIER: 19697
Cleaned salary: 36 - 600 triệu
Cleaned min VND: 36000000.0
Cleaned max VND: 600000000.0

ORIGINAL RECORD:
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

====================================================================================================
OUTLIER: 82684
Cleaned salary: 100 tr - 500 tr vnd
Cleaned min VND: 100000000.0
Cleaned max VND: 500000000.0

ORIGINAL RECORD:
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

====================================================================================================
OUTLIER: 3657
Cleaned salary: 15,000 - 20,000 usd
Cleaned min VND: 375000000.0
Cleaned max VND: 500000000.0

ORIGINAL RECORD:
Empty DataFrame
Columns: [job_title, city, experience, salary]
Index: []

In [22]:
for idx, row in top5_outliers.iterrows():
    matches = raw_df[
        raw_df['salary'].astype(str).str.strip() == str(row['salary']).strip()
    ]

    print("\n" + "=" * 100)
    print("OUTLIER:", idx)
    print("Cleaned job title:", row['job_title'])
    print("Salary:", row['salary'])
    print("Number of original matches:", len(matches))

    print(matches[
        ['job_title', 'city', 'experience', 'salary']
    ].head(10).to_string(index=False))

====================================================================================================
OUTLIER: 18583
Cleaned job title: môi giới nhà dân hcm tự do thời gian đào tạo pháp lý bđs trên 36tr giao dịch cho sale không doanh số nguồn khách nguồn nhà có sẵn
Salary: 36 - 600 triệu
Number of original matches: 3
                                                                                                                        job_title        city    experience         salary
môi giới nhà dân hcm tự do thời gian đào tạo pháp lý bđs trên 36tr giao dịch cho sale không doanh số nguồn khách nguồn nhà có sẵn hồ chí minh không yêu cầu 36 - 600 triệu
môi giới nhà dân hcm tự do thời gian đào tạo pháp lý bđs trên 36tr giao dịch cho sale không doanh số nguồn khách nguồn nhà có sẵn hồ chí minh không yêu cầu 36 - 600 triệu
                              môi giới nhà hcm hỗ trợ 90 marketing việc làm thêm được hướng dẫn làm việc đội nhóm tự do thời gian hồ chí minh không yêu cầu 36 - 600 triệu

====================================================================================================
OUTLIER: 23463
Cleaned job title: môi giới nhà hcm hỗ trợ 90 marketing việc làm thêm được hướng dẫn làm việc đội nhóm tự do thời gian
Salary: 36 - 600 triệu
Number of original matches: 3
                                                                                                                        job_title        city    experience         salary
môi giới nhà dân hcm tự do thời gian đào tạo pháp lý bđs trên 36tr giao dịch cho sale không doanh số nguồn khách nguồn nhà có sẵn hồ chí minh không yêu cầu 36 - 600 triệu
môi giới nhà dân hcm tự do thời gian đào tạo pháp lý bđs trên 36tr giao dịch cho sale không doanh số nguồn khách nguồn nhà có sẵn hồ chí minh không yêu cầu 36 - 600 triệu
                              môi giới nhà hcm hỗ trợ 90 marketing việc làm thêm được hướng dẫn làm việc đội nhóm tự do thời gian hồ chí minh không yêu cầu 36 - 600 triệu

====================================================================================================
OUTLIER: 19697
Cleaned job title: môi giới nhà dân hcm tự do thời gian đào tạo pháp lý bđs trên 36tr giao dịch cho sale không doanh số nguồn khách nguồn nhà có sẵn
Salary: 36 - 600 triệu
Number of original matches: 3
                                                                                                                        job_title        city    experience         salary
môi giới nhà dân hcm tự do thời gian đào tạo pháp lý bđs trên 36tr giao dịch cho sale không doanh số nguồn khách nguồn nhà có sẵn hồ chí minh không yêu cầu 36 - 600 triệu
môi giới nhà dân hcm tự do thời gian đào tạo pháp lý bđs trên 36tr giao dịch cho sale không doanh số nguồn khách nguồn nhà có sẵn hồ chí minh không yêu cầu 36 - 600 triệu
                              môi giới nhà hcm hỗ trợ 90 marketing việc làm thêm được hướng dẫn làm việc đội nhóm tự do thời gian hồ chí minh không yêu cầu 36 - 600 triệu

====================================================================================================
OUTLIER: 82684
Cleaned job title: chuyên viên tư vấn bất động sản căn hộ hỗ trợ data marketing đào tạo
Salary: 100 tr - 500 tr vnd
Number of original matches: 2
                                                           job_title   city    experience              salary
chuyên viên tư vấn bất động sản căn hộ hỗ trợ data marketing đào tạo hà nội không yêu cầu 100 tr - 500 tr vnd
chuyên viên tư vấn bất động sản căn hộ hỗ trợ data marketing đào tạo hà nội không yêu cầu 100 tr - 500 tr vnd

====================================================================================================
OUTLIER: 3657
Cleaned job title: ceo stainless steel manufacturing
Salary: 15,000 - 20,000 usd
Number of original matches: 2
                        job_title   city  experience              salary
ceo stainless steel manufacturing hà nam 20 - 35 năm 15,000 - 20,000 usd
ceo stainless steel manufacturing hà nam 20 - 35 năm 15,000 - 20,000 usd

In [23]:
search_title = top5_outliers.iloc[0]['job_title']

raw_df[
    raw_df['job_title'].astype(str).str.contains(
        search_title[:30],
        case=False,
        na=False
    )
][['job_title', 'city', 'experience', 'salary']].head(20)

,job_title,city,experience,salary
18583,môi giới nhà dân hcm tự do thời gian đào tạo p...,hồ chí minh,không yêu cầu,36 - 600 triệu
19697,môi giới nhà dân hcm tự do thời gian đào tạo p...,hồ chí minh,không yêu cầu,36 - 600 triệu

In [24]:
#4.3

In [25]:
print("CITY")
print("Before:", raw_df['city'].nunique())
print("After :", clean_df['city'].nunique())

print("\nJOB FIELDS")
print("Before:", raw_df['job_fields'].nunique())
print("After :", clean_df['job_fields'].nunique())

CITY
Before: 466
After : 88

JOB FIELDS
Before: 7491
After : 7491

In [26]:
text_columns = [
    'job_title',
    'job_type',
    'position_level',
    'city',
    'experience',
    'skills',
    'job_fields'
]

for col in text_columns:
    print(
        f"{col:20} "
        f"Before: {raw_df[col].nunique():5} | "
        f"After: {clean_df[col].nunique():5}"
    )

job_title            Before: 23576 | After: 23576
job_type             Before:    27 | After:    27
position_level       Before:    26 | After:    26
city                 Before:   466 | After:    88
experience           Before:   181 | After:   181
skills               Before: 20484 | After: 20484
job_fields           Before:  7491 | After:  7491

In [27]:
print("Original job_type values:")
print(raw_df['job_type'].dropna().unique())

Original job_type values:
<StringArray>
[                                              'nhân viên chính thức',
                                     'nhân viên chính thức, thực tập',
                                                           'thực tập',
                                'nhân viên chính thức, bán thời gian',
                          'nhân viên chính thức, thời vụ, nghề tự do',
                                                'thời vụ, nghề tự do',
                       'bán thời gian, thời vụ, nghề tự do, thực tập',
                                                      'bán thời gian',
 'nhân viên chính thức, bán thời gian, thời vụ, nghề tự do, thực tập',
                                                              'error',
                                            'bán thời gian, thực tập',
                                 'bán thời gian, thời vụ, nghề tự do',
           'nhân viên chính thức, bán thời gian, thời vụ, nghề tự do',
                                      'thời vụ, nghề tự do, thực tập',
                      'nhân viên chính thức, bán thời gian, thực tập',
                'nhân viên chính thức, thời vụ, nghề tự do, thực tập',
                                             'toàn thời gian cố định',
                                                               'khác',
                                            'toàn thời gian tạm thời',
                                              'bán thời gian cố định',
                                               'theo hợp đồng tư vấn',
                                             'bán thời gian tạm thời',
                                                          'full-time',
                                              'full-time , part-time',
                                                          'part-time',
                                                     'toàn thời gian',
                                                                  ' ']
Length: 27, dtype: str

In [28]:
print("\nCleaned job_type values:")
print(clean_df['job_type'].dropna().unique())

Cleaned job_type values:
<StringArray>
[                                              'nhân viên chính thức',
                                     'nhân viên chính thức, thực tập',
                                                           'thực tập',
                                'nhân viên chính thức, bán thời gian',
                          'nhân viên chính thức, thời vụ, nghề tự do',
                                                'thời vụ, nghề tự do',
                       'bán thời gian, thời vụ, nghề tự do, thực tập',
                                                      'bán thời gian',
 'nhân viên chính thức, bán thời gian, thời vụ, nghề tự do, thực tập',
                                                              'error',
                                            'bán thời gian, thực tập',
                                 'bán thời gian, thời vụ, nghề tự do',
           'nhân viên chính thức, bán thời gian, thời vụ, nghề tự do',
                                      'thời vụ, nghề tự do, thực tập',
                      'nhân viên chính thức, bán thời gian, thực tập',
                'nhân viên chính thức, thời vụ, nghề tự do, thực tập',
                                             'toàn thời gian cố định',
                                                               'khác',
                                            'toàn thời gian tạm thời',
                                              'bán thời gian cố định',
                                               'theo hợp đồng tư vấn',
                                             'bán thời gian tạm thời',
                                                          'full-time',
                                              'full-time , part-time',
                                                          'part-time',
                                                     'toàn thời gian',
                                                                  ' ']
Length: 27, dtype: str

In [29]:
clean_df['job_type'] = (
    clean_df['job_type']
    .astype('string')
    .str.strip()
    .str.lower()
    .str.replace(r'\s+', ' ', regex=True)
)

In [30]:
print("job_type distinct values")
print("Before:", raw_df['job_type'].nunique())
print("After :", clean_df['job_type'].nunique())

job_type distinct values
Before: 27
After : 27

In [31]:
print(clean_df['job_type'].value_counts())

job_type
full-time                                                             37135
nhân viên chính thức                                                  28859
toàn thời gian cố định                                                14225
toàn thời gian                                                         1526
part-time                                                              1071
full-time , part-time                                                   942
thực tập                                                                536
khác                                                                    228
bán thời gian                                                           166
toàn thời gian tạm thời                                                 155
bán thời gian cố định                                                   106
nhân viên chính thức, bán thời gian                                      96
theo hợp đồng tư vấn                                                     87
thời vụ, nghề tự do                                                      65
nhân viên chính thức, thời vụ, nghề tự do                                56
nhân viên chính thức, thực tập                                           54
bán thời gian tạm thời                                                   53
nhân viên chính thức, bán thời gian, thời vụ, nghề tự do, thực tập       29
bán thời gian, thực tập                                                  21
bán thời gian, thời vụ, nghề tự do                                       15
bán thời gian, thời vụ, nghề tự do, thực tập                             13
nhân viên chính thức, bán thời gian, thời vụ, nghề tự do                 12
nhân viên chính thức, bán thời gian, thực tập                             8
nhân viên chính thức, thời vụ, nghề tự do, thực tập                       5
thời vụ, nghề tự do, thực tập                                             4
error                                                                     2
                                                                          1
Name: count, dtype: Int64

In [32]:
print("Before:", raw_df['job_type'].nunique())
print("After :", clean_df['job_type'].nunique())

Before: 27
After : 27

In [33]:
print(raw_df['experience'].dropna().value_counts().head(30))

experience
không yêu cầu                36050
1 - 2 năm                     7191
trên 1 năm                    7038
trên 2 năm                    4206
1 - 3 năm                     3163
2 - 3 năm                     2947
3 - 5 năm                     2936
2 - 5 năm                     2931
dưới 1 năm                    2885
1 - 5 năm                     2245
trên 3 năm                    2187
dưới 5 năm                    1605
trên 5 năm                     878
lên đến 1 năm                  796
trên 0.5 năm                   776
0.5 - 1 năm                    484
2 năm                          429
1 năm                          416
5 - 10 năm                     389
3 - 4 năm                      344
dưới 2 năm                     342
2 - 4 năm                      341
1 - 1 năm                      334
chưa có kinh nghiệm            281
không yêu cầu kinh nghiệm      280
5 - 7 năm                      264
3 - 10 năm                     224
3 năm                          217
2 - 10 năm                     211
4 - 5 năm                      191
Name: count, dtype: int64

In [34]:
print(clean_df['experience'].dropna().value_counts().head(30))

experience
không yêu cầu                36050
1 - 2 năm                     7191
trên 1 năm                    7038
trên 2 năm                    4206
1 - 3 năm                     3163
2 - 3 năm                     2947
3 - 5 năm                     2936
2 - 5 năm                     2931
dưới 1 năm                    2885
1 - 5 năm                     2245
trên 3 năm                    2187
dưới 5 năm                    1605
trên 5 năm                     878
lên đến 1 năm                  796
trên 0.5 năm                   776
0.5 - 1 năm                    484
2 năm                          429
1 năm                          416
5 - 10 năm                     389
3 - 4 năm                      344
dưới 2 năm                     342
2 - 4 năm                      341
1 - 1 năm                      334
chưa có kinh nghiệm            281
không yêu cầu kinh nghiệm      280
5 - 7 năm                      264
3 - 10 năm                     224
3 năm                          217
2 - 10 năm                     211
4 - 5 năm                      191
Name: count, dtype: int64

In [35]:
# Find rows where job_type changed during standardization

changed_job_type = raw_df['job_type'].fillna('').astype(str) != clean_df['job_type'].fillna('').astype(str)

print("Rows changed:", changed_job_type.sum())

Rows changed: 1

In [36]:
comparison = pd.DataFrame({
    'Before': raw_df.loc[changed_job_type, 'job_type'],
    'After': clean_df.loc[changed_job_type, 'job_type']
})

comparison.head(20)

      Before After
83295

In [37]:
comparison = pd.DataFrame({
    'Before': raw_df.loc[changed_job_type, 'job_type'],
    'After': clean_df.loc[changed_job_type, 'job_type']
})

comparison

      Before After
83295

In [38]:
print("Missing values:")
print(clean_df.isna().sum().sort_values(ascending=False))

Missing values:
skills             11294
job_fields          7625
salary_max_vnd      3278
salary_min_vnd      2338
city                  32
job_title              7
position_level         0
experience             0
job_type               0
salary_min             0
salary                 0
salary_max             0
unit                   0
salary_currency        0
salary_clean           0
salary_type            0
salary_quality         0
dtype: int64

In [39]:
print("Salary quality:")
print(clean_df['salary_quality'].value_counts(dropna=False))

Salary quality:
salary_quality
OK            85390
SUSPICIOUS       80
Name: count, dtype: int64